BEGIN;

CREATE TABLE IF NOT EXISTS invoices (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  invoice_type TEXT NOT NULL DEFAULT 'personal',
  title TEXT NOT NULL,
  tax_number TEXT NOT NULL DEFAULT '',
  recipient_email TEXT NOT NULL,
  amount INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  invoice_number TEXT NOT NULL DEFAULT '',
  file_url TEXT NOT NULL DEFAULT '',
  rejection_reason TEXT NOT NULL DEFAULT '',
  admin_note TEXT NOT NULL DEFAULT '',
  requested_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  issued_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS invoices_member_idx ON invoices (member_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS invoices_status_idx ON invoices (status, requested_at DESC);

ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS due_at TEXT;

CREATE TABLE IF NOT EXISTS support_canned_replies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

INSERT INTO support_canned_replies (title, content) VALUES
  ('已收到问题', '您好，我们已经收到您的问题，客服正在核实相关信息，会尽快回复您。'),
  ('订单处理中', '您好，您的订单正在处理中。我们会持续跟进，并在状态更新后第一时间通知您。'),
  ('请补充信息', '您好，为了更快处理您的问题，请补充订单号、问题描述以及相关照片或凭证，谢谢。')
ON CONFLICT(title) DO NOTHING;

CREATE INDEX IF NOT EXISTS support_threads_due_idx ON support_threads (due_at, status);

COMMIT;
