BEGIN;

ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS experience_skin_type TEXT NOT NULL DEFAULT '';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS experience_usage_period TEXT NOT NULL DEFAULT '';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS experience_scene TEXT NOT NULL DEFAULT '';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS experience_rating INTEGER;
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS experience_highlights_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS experience_cautions TEXT NOT NULL DEFAULT '';
ALTER TABLE community_posts DROP CONSTRAINT IF EXISTS community_posts_experience_rating_check;
ALTER TABLE community_posts ADD CONSTRAINT community_posts_experience_rating_check
  CHECK (experience_rating IS NULL OR experience_rating BETWEEN 1 AND 5);

CREATE TABLE IF NOT EXISTS community_member_interests (
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  interest_type TEXT NOT NULL CHECK (interest_type IN ('topic')),
  interest_key TEXT NOT NULL,
  weight INTEGER NOT NULL DEFAULT 5 CHECK (weight BETWEEN 1 AND 10),
  source TEXT NOT NULL DEFAULT 'onboarding' CHECK (source IN ('onboarding', 'behavior')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (member_id, interest_type, interest_key)
);

CREATE INDEX IF NOT EXISTS community_member_interests_member_idx
  ON community_member_interests (member_id, weight DESC, updated_at DESC);

CREATE TABLE IF NOT EXISTS community_purchase_share_tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  order_id TEXT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_slug TEXT NOT NULL REFERENCES products(slug) ON DELETE RESTRICT,
  post_id TEXT UNIQUE REFERENCES community_posts(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'available' CHECK (status IN ('available', 'submitted', 'completed')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  submitted_at TEXT,
  completed_at TEXT,
  UNIQUE (member_id, order_id, product_slug)
);

CREATE INDEX IF NOT EXISTS community_purchase_share_tasks_member_idx
  ON community_purchase_share_tasks (member_id, status, created_at DESC);

ALTER TABLE community_content_events ADD COLUMN IF NOT EXISTS source TEXT NOT NULL DEFAULT '';
ALTER TABLE community_content_events DROP CONSTRAINT IF EXISTS community_content_events_event_type_check;
ALTER TABLE community_content_events DROP CONSTRAINT IF EXISTS community_content_events_check;
ALTER TABLE community_content_events ADD CONSTRAINT community_content_events_event_type_check
  CHECK (event_type IN ('post_impression', 'product_click', 'add_to_cart', 'share_poster', 'share_open', 'checkout_started'));
ALTER TABLE community_content_events ADD CONSTRAINT community_content_events_product_check
  CHECK ((event_type IN ('product_click', 'add_to_cart') AND product_slug IS NOT NULL)
    OR (event_type IN ('post_impression', 'share_poster', 'share_open', 'checkout_started') AND product_slug IS NULL));

CREATE TABLE IF NOT EXISTS community_order_attributions (
  order_id TEXT PRIMARY KEY REFERENCES orders(id) ON DELETE CASCADE,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE RESTRICT,
  member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  source TEXT NOT NULL CHECK (source IN ('wechat', 'copy_link', 'community')),
  status TEXT NOT NULL DEFAULT 'created' CHECK (status IN ('created', 'paid', 'refunded')),
  revenue_fen INTEGER NOT NULL DEFAULT 0 CHECK (revenue_fen >= 0),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  paid_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_order_attributions_post_idx
  ON community_order_attributions (post_id, status, created_at DESC);

COMMIT;
