BEGIN;

CREATE TABLE IF NOT EXISTS member_task_completions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  task_key TEXT NOT NULL,
  period_key TEXT NOT NULL DEFAULT 'lifetime',
  points INTEGER NOT NULL DEFAULT 0,
  reference_id TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  completed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, task_key, period_key)
);

CREATE INDEX IF NOT EXISTS member_task_completions_member_idx
  ON member_task_completions (member_id, completed_at DESC);

CREATE TABLE IF NOT EXISTS member_referral_codes (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  code TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  referred_member_id INTEGER NOT NULL UNIQUE REFERENCES members(id) ON DELETE CASCADE,
  referral_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'registered' CHECK (status IN ('registered', 'rewarded', 'invalid')),
  qualifying_order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  registered_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  rewarded_at TEXT,
  CHECK (referrer_member_id <> referred_member_id)
);

CREATE INDEX IF NOT EXISTS member_referrals_referrer_idx
  ON member_referrals (referrer_member_id, status, registered_at DESC);

CREATE TABLE IF NOT EXISTS member_benefit_grants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  benefit_key TEXT NOT NULL,
  benefit_year INTEGER NOT NULL,
  coupon_id INTEGER REFERENCES coupons(id) ON DELETE SET NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  granted_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, benefit_key, benefit_year)
);

CREATE INDEX IF NOT EXISTS member_benefit_grants_member_idx
  ON member_benefit_grants (member_id, granted_at DESC);

ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS images_json TEXT NOT NULL DEFAULT '[]';

COMMIT;
