-- Refresh Chinese ingredient translations for the 2026-08-29 catalog while preserving a recoverable source snapshot.
CREATE TABLE IF NOT EXISTS product_ingredient_translation_backups (
  batch_id TEXT NOT NULL,
  product_id BIGINT NOT NULL,
  slug TEXT NOT NULL,
  ingredients TEXT,
  old_updated_at TEXT,
  backed_up_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (batch_id, product_id)
);

CREATE TEMP TABLE product_ingredient_translation_payload_20260829 (
  slug TEXT PRIMARY KEY,
  source_ingredients TEXT,
  ingredients_zh TEXT NOT NULL,
  translation_status TEXT NOT NULL
) ON COMMIT DROP;

INSERT INTO product_ingredient_translation_payload_20260829 (slug, source_ingredients, ingredients_zh, translation_status) VALUES
  (E'maslo-dlya-gub-black-chernyiy-100710', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Octyldodecanol, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, May Contain, CI 15985, CI 15850, CI 77499.', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、辛基十二醇、角鲨烷、甜扁桃油、向日葵籽油、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、可能含有、着色剂 CI 15985、着色剂 CI 15850、着色剂 CI 77499', E'已翻译'),
  (E'maslo-dlya-gub-red-krasnyiy-100711', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Octyldodecanol, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, May Contain, CI 15985, CI 15850, CI 77499', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、辛基十二醇、角鲨烷、甜扁桃油、向日葵籽油、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、可能含有、着色剂 CI 15985、着色剂 CI 15850、着色剂 CI 77499', E'已翻译'),
  (E'maslo-dlya-gub-chocolate-shokoladnyiy-100707', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 77492, CI 77499, CI 16035', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 77492、着色剂 CI 77499、着色剂 CI 16035', E'已翻译'),
  (E'maslo-dlya-gub-crystal-prozrachnyiy-100709', E'Hydrogenated Polyisobutene, Ethylhexyl Palmitate, Polybutene, Pentaerythrityl Tetraisostearate, Tridecyl Trimellitate, Caprylic/Capric Triglyceride, Hydrogenated Styrene/Isoprene Copolymer, Polyglyceryl-2 Triisostearate, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum', E'氢化聚异丁烯、棕榈酸乙基己酯、聚丁烯、四异硬脂酸季戊四醇酯、偏苯三酸十三烷基酯、辛酸/癸酸甘油三酯、氢化苯乙烯/异戊二烯共聚物、三异硬脂酸聚甘油-2、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精', E'已翻译'),
  (E'maslo-dlya-gub-apricot-abrikosovyiy-100708', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 15850, CI 19140, CI 77499', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 15850、着色剂 CI 19140、着色剂 CI 77499', E'已翻译'),
  (E'maslo-dlya-gub-purple-1-100706', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 15850, CI 42090', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 15850、着色剂 CI 42090', E'已翻译'),
  (E'gel-maslo-dlya-dusha-pusy-shower-body-oil-200ml-100164', E'Glycine Soja (Soybean) Oil, Ricinus Communis (Castor) Seed Oil, Caprylic/Capric Triglyceride, MIPA-Laureth Sulfate, Laureth-3, Polyglyceryl-3 Diisostearate, Parfum, Laureth-7 Citrate, PEG-7 Glyceryl Cocoate, Propylene Glycol, Brassica Oleracea Italica (Brocoli) Seed Oil, Simmondsia Chinensis (Jojoba) Seed Oil, Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate, Benzyl Benzoate.', E'大豆油、蓖麻籽油、辛酸/癸酸甘油三酯、MIPA-月桂醇聚醚硫酸酯、月桂醇聚醚-3、二异硬脂酸聚甘油-3、香精、柠檬酸月桂醇聚醚-7、PEG-7 甘油椰油酸酯、丙二醇、西兰花籽油、霍霍巴籽油、四（双-叔丁基羟基氢化肉桂酸）季戊四醇酯、苯甲酸苄酯', E'已翻译'),
  (E'karandash-dlya-gub-pusy-strawberry-100464', E'Synthetic Wax, Copernicia Cerifera Wax, Microcrystalline Wax, Ethylhexyl Palmitate, Parfum, Hexyl Cinnamal, Geraniol, Benzyl Alcohol, Phenoxyethanol, Sorbic Acid, CI 77891, CI 77491, CI 77499, CI 15850:1, CI 77492', E'合成蜡、巴西棕榈树蜡、微晶蜡、棕榈酸乙基己酯、香精、己基肉桂醛、香叶醇、苄醇、苯氧乙醇、山梨酸、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 77499、着色剂 CI 15850:1、着色剂 CI 77492', E'已翻译'),
  (E'karandash-dlya-gub-pusy-morning-100461', E'Synthetic Wax, Copernicia Cerifera Wax, Microcrystalline Wax, Ethylhexyl Palmitate, Parfum, Hexyl Cinnamal, Geraniol, Benzyl Alcohol, Phenoxyethanol, Sorbic Acid, CI 77891, CI 77491, CI 15850:1, CI 77499, CI 77492.', E'合成蜡、巴西棕榈树蜡、微晶蜡、棕榈酸乙基己酯、香精、己基肉桂醛、香叶醇、苄醇、苯氧乙醇、山梨酸、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 15850:1、着色剂 CI 77499、着色剂 CI 77492', E'已翻译'),
  (E'karandash-dlya-gub-pusy-passion-100463', E'Synthetic Wax, Copernicia Cerifera Wax, Microcrystalline Wax, Ethylhexyl Palmitate, Parfum, Hexyl Cinnamal, Geraniol, Benzyl Alcohol, Phenoxyethanol, Sorbic Acid, CI 77491, CI 77499, CI 77891, CI 77492', E'合成蜡、巴西棕榈树蜡、微晶蜡、棕榈酸乙基己酯、香精、己基肉桂醛、香叶醇、苄醇、苯氧乙醇、山梨酸、着色剂 CI 77491、着色剂 CI 77499、着色剂 CI 77891、着色剂 CI 77492', E'已翻译'),
  (E'karandash-dlya-gub-pusy-mommy-100462', E'Synthetic Wax, Copernicia Cerifera Wax, Microcrystalline Wax, Ethylhexyl Palmitate, Parfum, Hexyl Cinnamal, Geraniol, Benzyl Alcohol, Phenoxyethanol, Sorbic Acid, CI 77891, CI 77491, CI 15850:1, CI 77499', E'合成蜡、巴西棕榈树蜡、微晶蜡、棕榈酸乙基己酯、香精、己基肉桂醛、香叶醇、苄醇、苯氧乙醇、山梨酸、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 15850:1、着色剂 CI 77499', E'已翻译'),
  (E'klassicheskaya-tush-dlya-resnic-pusy-light-brown-10-ml-100363', E'Aqua, Styrene/Acrylates Copolymer, Paraffin, Microcrystalline Wax, Propylene Glycol, Ozokerite, Polyisobutene, Euphorbia Cerifera Wax, Stearic Acid, Glyceryl Stearate, Cetearyl Alcohol, Hydroxyethylcellulose, PEG-100 Stearate, Phenoxyethanol, Polysorbate 60, 1,2-Hexanediol, Caprylyl Glycol, Tromethamine, Ethylhexylglycerin, Synthetic Fluorphlogopite, Aluminum Hydroxide, Panthenol, Mel, Butyrospermum Parkii Butter, Butyrospermum Parkii Butter Unsaponifiables, Tin Oxide, CI 77499, CI 77492, CI 77891, CI 77491.', E'水、苯乙烯/丙烯酸（酯）类共聚物、石蜡、微晶蜡、丙二醇、地蜡、聚异丁烯、小烛树蜡、硬脂酸、甘油硬脂酸酯、鲸蜡硬脂醇、羟乙基纤维素、PEG-100 硬脂酸酯、苯氧乙醇、聚山梨醇酯-60、1,2-己二醇、辛甘醇、氨丁三醇、乙基己基甘油、合成氟金云母、氢氧化铝、泛醇、蜂蜜、乳木果油、乳木果油不皂化物、氧化锡、着色剂 CI 77499、着色剂 CI 77492、着色剂 CI 77891、着色剂 CI 77491', E'已翻译'),
  (E'klassicheskaya-tush-dlya-resnic-pusy-dark-brown-10-ml-100364', E'Aqua, Styrene/Acrylates Copolymer, Paraffin, Microcrystalline Wax, Ozokerite, Propylene Glycol, Polyisobutene, Euphorbia Cerifera Wax, Stearic Acid, Glyceryl Stearate, Cetearyl Alcohol, Hydroxyethylcellulose, PEG-100 Stearate, Phenoxyethanol, Polysorbate 60, 1,2-Hexanediol, Caprylyl Glycol, Tromethamine, Ethylhexylglycerin, Panthenol, Mel, Butyrospermum Parkii Butter, Butyrospermum Parkii Butter Unsaponifiables, CI 77499, CI 77491, CI 77492.', E'水、苯乙烯/丙烯酸（酯）类共聚物、石蜡、微晶蜡、地蜡、丙二醇、聚异丁烯、小烛树蜡、硬脂酸、甘油硬脂酸酯、鲸蜡硬脂醇、羟乙基纤维素、PEG-100 硬脂酸酯、苯氧乙醇、聚山梨醇酯-60、1,2-己二醇、辛甘醇、氨丁三醇、乙基己基甘油、泛醇、蜂蜜、乳木果油、乳木果油不皂化物、着色剂 CI 77499、着色剂 CI 77491、着色剂 CI 77492', E'已翻译'),
  (E'karandash-dlya-gub-pusy-paradise-100459', E'Synthetic Wax, Copernicia Cerifera Wax, Microcrystalline Wax, Ethylhexyl Palmitate, Parfum, Hexyl Cinnamal, Geraniol, Benzyl Alcohol, Phenoxyethanol, Sorbic Acid, CI 77891, CI 77491, CI 77499, CI 15850:1, CI 77492', E'合成蜡、巴西棕榈树蜡、微晶蜡、棕榈酸乙基己酯、香精、己基肉桂醛、香叶醇、苄醇、苯氧乙醇、山梨酸、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 77499、着色剂 CI 15850:1、着色剂 CI 77492', E'已翻译'),
  (E'kokosovaya-micellyarnaya-voda-pusy-100-ml-micellar-cocowater-pusy-100-ml-100171', E'Aqua, Cocos Nucifera Water, Peg-6 Caprylic / Capric Glycerides, Propylene Glycol, Glycerin, Cucumis Sativus Fruit Water, Potassium Sorbate, Sodium Cocoamphoacetate, Panthenol, Disodium EDTA, Caprylyl Glycol, Methy|propanediol, Didecyldimonium Chloride, Polyqua-ternium-80, Citric Acid, Parfum', E'水、椰子水、PEG-6 辛酸/癸酸甘油酯类、丙二醇、甘油、黄瓜果水、山梨酸钾、椰油酰两性基乙酸钠、泛醇、乙二胺四乙酸二钠、辛甘醇、甲基丙二醇、二癸基二甲基氯化铵、聚季铵盐-80、柠檬酸、香精', E'已翻译'),
  (E'rebrending-prozrachnyiy-super-gel-fiksator-dlya-broveiy-super-fix-brow-gel-pusy-5-ml-10-100344', E'Aqua, VP/VA Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid.', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸', E'已翻译'),
  (E'rebrending-prozrachnyiy-gel-fiksator-dlya-jestkih-broveiy-pusy-5-ml-6-100345', E'Aqua, VP/VA, Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethypropanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸', E'已翻译'),
  (E'rebrending-vosstanavlivayshchiiy-gel-fiksator-dlya-broveiy-pusy-5-ml-13-100346', E'Aqua, VP/VA Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethyl Propanol, Biotinoyl Tripeptide-1, 1,2-Hexanediol, Arginine, Lactic Acid, Glycine Soja Germ Extract, Triticum Vulgare Germ Extract, Scutellaria Baicalensis Root Extract, Gluconolactone, Calcium Gluconate, Serenoa Serrulata Fruit Extract, Panthenol, Hydrolyzed Keratin, Biotin, Niacinamide, Camellia Sinensis Leaf Water, Aloe Barbadensis Leaf Juice, Sodium Hyaluronate, PEG-40 Hydrogenated Castor Oil, Propanediol, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid, Dehydroacetic Acid, Benzyl Alcohol, Potassium Sorbate, Sodium Benzoate.', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、生物素酰三肽-1、1,2-己二醇、精氨酸、乳酸、大豆胚芽提取物、小麦胚芽提取物、黄芩根提取物、葡糖酸内酯、葡糖酸钙、锯叶棕果提取物、泛醇、水解角蛋白、生物素、烟酰胺、茶叶水、库拉索芦荟叶汁、透明质酸钠、PEG-40 氢化蓖麻油、丙二醇、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸、脱氢乙酸、苄醇、山梨酸钾、苯甲酸钠', E'已翻译'),
  (E'rebrending-prozrachnyiy-gel-fiksator-dlya-broveiy-pusy-5ml-1-100347', E'Aqua, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl\nMethacrylate, Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Disodium EDTA, Citric Acid, Parfum, Limonene, Eugenol, Coumarin', E'水、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷醇丙烯酸酯交联聚合物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、乙二胺四乙酸二钠、柠檬酸、香精、柠檬烯、丁香酚、香豆素', E'已翻译'),
  (E'sekretnyiy-boks-vsye-vklycheno-m-100729', NULL, E'礼盒内容按所选规格随机组合，完整成分请以收到的各单品包装标注为准。', E'礼盒说明'),
  (E'sekretnyiy-boks-otpusk-dlya-sebya-s-100731', NULL, E'礼盒内容按所选规格随机组合，完整成分请以收到的各单品包装标注为准。', E'礼盒说明'),
  (E'sekretnyiy-boks-siyaiy-bez-sprosa-3-100738', NULL, E'礼盒内容按所选规格随机组合，完整成分请以收到的各单品包装标注为准。', E'礼盒说明'),
  (E'nabor-dlya-tela-i-rasslableniya-plys-vaiyb-100676', NULL, E'本套装包含多件产品，完整成分请分别参见套装内各单品包装及对应商品页面。', E'套装说明'),
  (E'kondicioner-dlya-volos-pusy-base-hair-750-ml-1-1-100579', NULL, E'原品牌页面暂未公开完整成分表，请以中国销售实物包装的成分标注为准。', E'待品牌确认'),
  (E'klassicheskaya-tush-dlya-resnic-pusy-black-10-ml-100365', E'Aqua, Styrene/Acrylates Copolymer, Paraffin, Microcrystalline Wax, Propylene Glycol, Ozokerite, Polyisobutene, Stearic Acid, Euphorbia Cerifera Wax, Glyceryl Stearate, Cetearyl Alcohol, Hydroxyethylcellulose, PEG-100 Stearate, Phenoxyethanol, Polysorbate 60, Acrylates Copolymer, Glycerin, 1,2-Hexanediol, Caprylyl Glycol, Tromethamine, Ethylhexylglycerin, Mel, Panthenol, Butyrospermum Parkii Butter, Butyrospermum Parkii Butter Unsaponifiables, CI 77266.', E'水、苯乙烯/丙烯酸（酯）类共聚物、石蜡、微晶蜡、丙二醇、地蜡、聚异丁烯、硬脂酸、小烛树蜡、甘油硬脂酸酯、鲸蜡硬脂醇、羟乙基纤维素、PEG-100 硬脂酸酯、苯氧乙醇、聚山梨醇酯-60、丙烯酸（酯）类共聚物、甘油、1,2-己二醇、辛甘醇、氨丁三醇、乙基己基甘油、蜂蜜、泛醇、乳木果油、乳木果油不皂化物、着色剂 CI 77266', E'已翻译'),
  (E'maslo-dlya-gub-apricot-1-100778', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 15850, CI 19140, CI 77499', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 15850、着色剂 CI 19140、着色剂 CI 77499', E'已翻译'),
  (E'glyancevyiy-tint-dlya-gub-berry-glaze-vinnyiy-100844', E'Aqua, Dimethicone, Isononyl Isononanoate, Dicaprylyl Carbonate, Propylene Glycol, Glycerin, Butylene Glycol, Bis -Diglyceryl Polyacyladipate -2, Synthetic Beeswax, Polyglyceryl -10 Myristate, Polyacrylate Crosspolymer -6, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, Parfum, 1,2 -Hexanediol, Isohexadecane, Potassium Acesulfame, Caprylhydroxamic Acid, Polysorbate 80, Disodium EDTA, Sodium Sulfate, Sodium Chloride, CI 17200, CI 42090.', E'水、聚二甲基硅氧烷、异壬酸异壬酯、碳酸二辛酯、丙二醇、甘油、丁二醇、聚己二酸双-二甘油酯-2、合成蜂蜡、聚甘油-10 肉豆蔻酸酯、聚丙烯酸酯交联聚合物-6、丙烯酸钠/丙烯酰二甲基牛磺酸钠共聚物、香精、1,2-己二醇、异十六烷、乙酰磺胺酸钾、辛酰羟肟酸、聚山梨醇酯-80、乙二胺四乙酸二钠、硫酸钠、氯化钠、着色剂 CI 17200、着色剂 CI 42090', E'已翻译'),
  (E'maslo-dlya-gub-black-chernyiy-100779', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Octyldodecanol, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, May Contain, CI 15985, CI 15850, CI 77499.', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、辛基十二醇、角鲨烷、甜扁桃油、向日葵籽油、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、可能含有、着色剂 CI 15985、着色剂 CI 15850、着色剂 CI 77499', E'已翻译'),
  (E'kapsulnaya-tush-dlya-resnic-black-100670', E'Aqua, Styrene/Acrylates Copolymer, Copernicia Cerifera (Carnauba) Wax, Synthetic Wax, Isododecane, Glycerin, Lauric/Myristic/Palmitic/Stearic Glycerides, Stearic Acid, Palmitic Acid, Glyceryl Stearate, Aminomethyl Propanol, Phenoxyethanol, Stearyl Alcohol, Cetyl Alcohol, Ethylhexylglycerin, Panthenol, Sodium Dehydroacetate, Tocopheryl Acetate, Lepidium Meyenii Root Extract, Maltodextrin, Myristoyl Pentapeptide-4, 1,2-Hexanediol, CI 77492, CI 77499, CI 77491.', E'水、苯乙烯/丙烯酸（酯）类共聚物、巴西棕榈树蜡、合成蜡、异十二烷、甘油、月桂酸/肉豆蔻酸/棕榈酸/硬脂酸甘油酯类、硬脂酸、棕榈酸、甘油硬脂酸酯、氨甲基丙醇、苯氧乙醇、硬脂醇、鲸蜡醇、乙基己基甘油、泛醇、脱氢乙酸钠、生育酚乙酸酯、玛咖根提取物、麦芽糊精、肉豆蔻酰五肽-4、1,2-己二醇、着色剂 CI 77492、着色剂 CI 77499、着色剂 CI 77491', E'已翻译'),
  (E'kremovye-rumyana-pusy-blood-mary-25-gr-8-1-100361', E'Isononyl Isononanoate, Octyldodecyl Stearoyl Stearate, Cera Microcristallina, Dimethicone/Vinyl Dimethicone Crosspolymer, Dimethicone, Tribehenin, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Ci 77499, Ci 77891, Ci 15850:2, Ci 77491, Ci 77492.', E'异壬酸异壬酯、硬脂酰硬脂酸辛基十二醇酯、微晶蜡、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、聚二甲基硅氧烷、山嵛酸甘油三酯、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、着色剂 CI 77499、着色剂 CI 77891、着色剂 CI 15850:2、着色剂 CI 77491、着色剂 CI 77492', E'已翻译'),
  (E'karandash-plamper-dlya-gub-pusy-chili-100455', E'Diisostearyl Malate, Polyglyceryl-2 Triisostearate, Methyl Trimethicone, Synthetic Wax, Trimethylsiloxysilicate, Isononyl Isononanoate, Caprylic/Capric Triglyceride, Vanillyl Butyl Ether, Silica, Copernicia Cerifera Cera, Cera Microcristallina, Disteardimonium Hectorite, Caprylyl Glycol, Triethoxycaprylylsilane, Tocopheryl Acetate, Propylene Carbonate, Myrothamnus Flabellifolia Leaf/Stem Extract, BHT, CI 77891, CI 77491, CI 77499, CI 15850.', E'苹果酸二异硬脂醇酯、三异硬脂酸聚甘油-2、甲基聚三甲基硅氧烷、合成蜡、三甲基硅烷氧基硅酸酯、异壬酸异壬酯、辛酸/癸酸甘油三酯、香兰基丁基醚、二氧化硅、巴西棕榈树蜡、微晶蜡、二硬脂二甲铵锂蒙脱石、辛甘醇、三乙氧基辛基硅烷、生育酚乙酸酯、碳酸丙烯酯、密罗木叶/茎提取物、丁羟甲苯、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 77499、着色剂 CI 15850', E'已翻译'),
  (E'maslo-dlya-gub-chocolate-shokoladnyiy-100782', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 77492, CI 77499, CI 16035', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 77492、着色剂 CI 77499、着色剂 CI 16035', E'已翻译'),
  (E'glyancevyiy-tint-dlya-gub-cold-brew-korichnevyiy-100843', E'Aqua, Dimethicone, Dicaprylyl Carbonate, Isononyl Isononanoate, Propylene Glycol, Glycerin, Butylene Glycol, Bis-Diglyceryl Polyacyladipate-2, Synthetic Beeswax, Polyglyceryl-10 Myristate, Polyacrylate Crosspolymer-6, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, 1,2-Hexanediol, Parfum, Isohexadecane, Potassium Acesulfame, Caprylhydroxamic Acid, Polysorbate 80, Disodium EDTA, Sodium Chloride, Sodium Sulfate, CI 17200, CI 15985, CI 42090, CI 19140, CI 16185.', E'水、聚二甲基硅氧烷、碳酸二辛酯、异壬酸异壬酯、丙二醇、甘油、丁二醇、聚己二酸双-二甘油酯-2、合成蜂蜡、聚甘油-10 肉豆蔻酸酯、聚丙烯酸酯交联聚合物-6、丙烯酸钠/丙烯酰二甲基牛磺酸钠共聚物、1,2-己二醇、香精、异十六烷、乙酰磺胺酸钾、辛酰羟肟酸、聚山梨醇酯-80、乙二胺四乙酸二钠、氯化钠、硫酸钠、着色剂 CI 17200、着色剂 CI 15985、着色剂 CI 42090、着色剂 CI 19140、着色剂 CI 16185', E'已翻译'),
  (E'karandash-dlya-gub-pusy-cream-100460', E'Synthetic Wax, Copernicia Cerifera Wax, Microcrystalline Wax, Ethylhexyl Palmitate, Parfum, Hexyl Cinnamal, Geraniol, Benzyl Alcohol, Phenoxyethanol, Sorbic Acid, CI 77492, CI 77499, CI 15985, CI 77491, CI 15850:1', E'合成蜡、巴西棕榈树蜡、微晶蜡、棕榈酸乙基己酯、香精、己基肉桂醛、香叶醇、苄醇、苯氧乙醇、山梨酸、着色剂 CI 77492、着色剂 CI 77499、着色剂 CI 15985、着色剂 CI 77491、着色剂 CI 15850:1', E'已翻译'),
  (E'maslo-dlya-gub-crystal-prozrachnyiy-100780', E'Hydrogenated Polyisobutene, Ethylhexyl Palmitate, Polybutene, Pentaerythrityl Tetraisostearate, Tridecyl Trimellitate, Caprylic/Capric Triglyceride, Hydrogenated Styrene/Isoprene Copolymer, Polyglyceryl-2 Triisostearate, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum', E'氢化聚异丁烯、棕榈酸乙基己酯、聚丁烯、四异硬脂酸季戊四醇酯、偏苯三酸十三烷基酯、辛酸/癸酸甘油三酯、氢化苯乙烯/异戊二烯共聚物、三异硬脂酸聚甘油-2、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精', E'已翻译'),
  (E'maslo-dlya-gub-crystal-pink-svetlo-rozovyiy-100783', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 45410, CI 15850', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 45410、着色剂 CI 15850', E'已翻译'),
  (E'mercayshchie-teni-sparkly-dlya-vek-pusy-dangerous-100467', E'Calcium Aluminum Borosilicate, Dimethicone, Mica, Boron Nitride, Triethylhexanoin, Talc, Caprylic/Capric Triglyceride, Stearyl Dimethicone, Dimethicone/Vinyl Dimethicone Crosspolymer, Tridecyl Trimellitate, Kaolin, Octyldodecanol, Magnesium Stearate, Diisostearyl Malate, Phenyl Trimethicone, Hydrogenated Sunflower Seed Oil, Octadecene, C10-18 Triglycerides, Phenoxyethanol, Tocopheryl Acetate, Tin Oxide, Ethylhexylglycerin, CI 77891, CI 15850, CI 19140, CI 15985, CI 77499, CI 45410.', E'硼硅酸铝钙、聚二甲基硅氧烷、云母、氮化硼、三乙基己酸甘油酯、滑石粉、辛酸/癸酸甘油三酯、硬脂基聚二甲硅氧烷、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、偏苯三酸十三烷基酯、高岭土、辛基十二醇、硬脂酸镁、苹果酸二异硬脂醇酯、苯基聚三甲基硅氧烷、氢化向日葵籽油、十八碳烯、C10-18 脂酸甘油三酯类、苯氧乙醇、生育酚乙酸酯、氧化锡、乙基己基甘油、着色剂 CI 77891、着色剂 CI 15850、着色剂 CI 19140、着色剂 CI 15985、着色剂 CI 77499、着色剂 CI 45410', E'已翻译'),
  (E'mercayshchie-teni-sparkly-dlya-vek-pusy-diamond-100470', E'Polymethylsilsesquioxane, Diisostearyl Malate, Calcium Sodium Borosilicate, Dimethicone, Dimethicone/Vinyl Dimethicone Crosspolymer, Hydrogenated Polyisobutene, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Caprylyl Glycol, Tin Oxide, CI 77891.', E'聚甲基倍半硅氧烷、苹果酸二异硬脂醇酯、硼硅酸钙钠、聚二甲基硅氧烷、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、氢化聚异丁烯、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、辛甘醇、氧化锡、着色剂 CI 77891', E'已翻译'),
  (E'kremovye-rumyana-pusy-flower-25-gr-9-100359', E'Isononyl Isononanoate, Octyldodecyl Stearoyl Stearate, Cera Microcristallina, Dimethicone/Vinyl Dimethicone Crosspolymer, Dimethicone, Tribehenin, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Ci 77891, Ci 15850:1, Ci 15850:2, Ci 77491.', E'异壬酸异壬酯、硬脂酰硬脂酸辛基十二醇酯、微晶蜡、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、聚二甲基硅氧烷、山嵛酸甘油三酯、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、着色剂 CI 77891、着色剂 CI 15850:1、着色剂 CI 15850:2、着色剂 CI 77491', E'已翻译'),
  (E'kremovye-rumyana-pusy-honey-25-gr-5-100362', E'Isononyl Isononanoate, Octyldodecyl Stearoyl Stearate, Cera Microcristallina, Dimethicone/Vinyl Dimethicone Crosspolymer, Dimethicone, Tribehenin, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Ci 77891, Ci 15850:2, Ci 77491, Ci 19140:1.', E'异壬酸异壬酯、硬脂酰硬脂酸辛基十二醇酯、微晶蜡、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、聚二甲基硅氧烷、山嵛酸甘油三酯、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、着色剂 CI 77891、着色剂 CI 15850:2、着色剂 CI 77491、着色剂 CI 19140:1', E'已翻译'),
  (E'haiylaiyter-sufle-pusy-ice-baby-4-g-1-100693', E'Mica, Polymethylsilsesquioxane, Synthetic Fluorphlogopite, Paraffinum Liquidum, Isononyl Isononanoate, Calcium Aluminum Borosilicate, Synthetic Wax, Hydrogenated Styrene/Isoprene Copolymer, Silica, Zinc Oxide, Phenoxyethanol, CI 77891.', E'云母、聚甲基倍半硅氧烷、合成氟金云母、矿油、异壬酸异壬酯、硼硅酸铝钙、合成蜡、氢化苯乙烯/异戊二烯共聚物、二氧化硅、氧化锌、苯氧乙醇、着色剂 CI 77891', E'已翻译'),
  (E'termogel-dlya-resnic-pusy-black-5-ml-13-100413', E'Aqua, Ceteareth 30, Ceteareth 20, Propylene Glycol, PEG-7 Glyceryl Cocoate, Acrylates, Ethylhexyl Acrylates Copolymer! Phenoxyethanol, Ethylhexylglycerin, Xanthan Gum, Chacroal Powder, Polyglyceryl-10 stearate, Polyglyceryl-10 Myristate, Polyglycerin-10, Laureth-21, Sodium Dehydroacetate, Citric Acid', E'水、鲸蜡硬脂醇聚醚-30、鲸蜡硬脂醇聚醚-20、丙二醇、PEG-7 甘油椰油酸酯、丙烯酸（酯）类、丙烯酸乙基己酯共聚物；苯氧乙醇、乙基己基甘油、黄原胶、炭粉、聚甘油-10 硬脂酸酯、聚甘油-10 肉豆蔻酸酯、聚甘油-10、月桂醇聚醚-21、脱氢乙酸钠、柠檬酸', E'已翻译'),
  (E'mercayshchie-teni-sparkly-dlya-vek-pusy-magic-flower-100469', E'Calcium Aluminum Borosilicate, Dimethicone, Mica, Boron Nitride, Talc, Triethylhexanoin, Caprylic/Capric Triglyceride, Dimethicone/Vinyl Dimethicone Crosspolymer, Stearyl Dimethicone, Tridecyl Trimellitate, Kaolin, Octyldodecanol, Magnesium Stearate, Diisostearyl Malate, Phenyl Trimethicone, Silica, Hydrogenated Sunflower Seed Oil, Octadecene, C10-18 Triglycerides, Phenoxyethanol, Tocopheryl Acetate, Tin Oxide, Ethylhexylglycerin, CI 77891, CI 15850, CI 45410.', E'硼硅酸铝钙、聚二甲基硅氧烷、云母、氮化硼、滑石粉、三乙基己酸甘油酯、辛酸/癸酸甘油三酯、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、硬脂基聚二甲硅氧烷、偏苯三酸十三烷基酯、高岭土、辛基十二醇、硬脂酸镁、苹果酸二异硬脂醇酯、苯基聚三甲基硅氧烷、二氧化硅、氢化向日葵籽油、十八碳烯、C10-18 脂酸甘油三酯类、苯氧乙醇、生育酚乙酸酯、氧化锡、乙基己基甘油、着色剂 CI 77891、着色剂 CI 15850、着色剂 CI 45410', E'已翻译'),
  (E'jidkie-rumyana-dlya-lica-peachland-100768', E'Aqua，Isohexadecane，Isododecane，Dimethicone，Butylene Glycol，Tridecyl Trimellitate，Kaolin，Lauryl Peg-10 Tris(Trimethylsiloxy)Silylethyl Dimethicone, Polyglyceryl-2 Triisostearate，Trimethylsiloxysilicate，Mica，Disteardimonium Hectorite，Silica, Cetyl Peg/Ppg-10/1 Dimethicone，Sodium Chloride，Phenoxyethanol，Tribehenin，Sorbitan Sesquioleate，1,2-Hexanediol，Dimethicone/Vinyl Dimethicone Crosspolymer，Propylene Carbonate，Caprylyl Glycol，Tocopheryl Acetate，Xanthan Gum，Olea Europaea (Olive) Fruit Oil，Parfum，Sodium Hyaluronate，Benzyl Alcohol，Vanillin， CI 77891，CI 77492，CI 77491, CI 15850，CI 77499.', E'水、异十六烷、异十二烷、聚二甲基硅氧烷、丁二醇、偏苯三酸十三烷基酯、高岭土、月桂基 PEG-10 三（三甲基硅氧基）甲硅烷基乙基聚二甲基硅氧烷、三异硬脂酸聚甘油-2、三甲基硅烷氧基硅酸酯、云母、二硬脂二甲铵锂蒙脱石、二氧化硅、鲸蜡基 PEG/PPG-10/1 聚二甲基硅氧烷、氯化钠、苯氧乙醇、山嵛酸甘油三酯、倍半油酸山梨坦、1,2-己二醇、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、碳酸丙烯酯、辛甘醇、生育酚乙酸酯、黄原胶、油橄榄果油、香精、透明质酸钠、苄醇、香兰素、着色剂 CI 77891、着色剂 CI 77492、着色剂 CI 77491、着色剂 CI 15850、着色剂 CI 77499', E'已翻译'),
  (E'glyancevyiy-tint-dlya-gub-pink-jam-rozovyiy-100842', E'Aqua, Dimethicone, Dicaprylyl Carbonate, Isononyl Isononanoate, Propylene Glycol, Glycerin, Butylene Glycol, Bis -Diglyceryl Polyacyladipate -2, Synthetic Beeswax, Polyglyceryl -10 Myristate, Polyacrylate Crosspolymer -6, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, 1,2 -Hexanediol, Parfum, Isohexadecane, Potassium Acesulfame, Caprylhydroxamic Acid, Polysorbate 80, Disodium EDTA, Sodium Chloride, Sodium Sulfate, CI 17200, CI 19140, CI 42090, CI 15985, CI 16185.', E'水、聚二甲基硅氧烷、碳酸二辛酯、异壬酸异壬酯、丙二醇、甘油、丁二醇、聚己二酸双-二甘油酯-2、合成蜂蜡、聚甘油-10 肉豆蔻酸酯、聚丙烯酸酯交联聚合物-6、丙烯酸钠/丙烯酰二甲基牛磺酸钠共聚物、1,2-己二醇、香精、异十六烷、乙酰磺胺酸钾、辛酰羟肟酸、聚山梨醇酯-80、乙二胺四乙酸二钠、氯化钠、硫酸钠、着色剂 CI 17200、着色剂 CI 19140、着色剂 CI 42090、着色剂 CI 15985、着色剂 CI 16185', E'已翻译'),
  (E'maslo-dlya-gub-purple-rozovyiy-100781', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 Triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Octyldodecanol, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, CI 15850, CI 42090', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、角鲨烷、甜扁桃油、向日葵籽油、辛基十二醇、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、着色剂 CI 15850、着色剂 CI 42090', E'已翻译'),
  (E'kremovye-rumyana-pusy-pusyboy-25-gr-20-100360', E'Isononyl Isononanoate, Octyldodecyl Stearoyl Stearate, Cera Microcristallina, Dimethicone/Vinyl Dimethicone Crosspolymer, Dimethicone, Tribehenin, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Ci 77891, Ci 45410:2, Ci 45380:3.', E'异壬酸异壬酯、硬脂酰硬脂酸辛基十二醇酯、微晶蜡、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、聚二甲基硅氧烷、山嵛酸甘油三酯、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、着色剂 CI 77891、着色剂 CI 45410:2、着色剂 CI 45380:3', E'已翻译'),
  (E'maslo-dlya-gub-red-krasnyiy-100784', E'Hydrogenated Polyisobutene, Polybutene, Ethylhexyl Palmitate, Pentaerythrityl Tetraisostearate, Caprylic/Capric Triglyceride, Tridecyl Trimellitate, Polyglyceryl-2 triisostearate, Hydrogenated Styrene/Isoprene Copolymer, Simmondsia Chinensis (Jojoba) Seed Oil, Octyldodecanol, Squalane, Prunus Amygdalus Dulcis (Sweet Almond) Oil, Helianthus Annuus (Sunflower) Seed Oil, Bisabolol, Phenoxyethanol, Tocopheryl Acetate, Ethylhexylglycerin, Parfum, May Contain, CI 15985, CI 15850, CI 77499', E'氢化聚异丁烯、聚丁烯、棕榈酸乙基己酯、四异硬脂酸季戊四醇酯、辛酸/癸酸甘油三酯、偏苯三酸十三烷基酯、三异硬脂酸聚甘油-2、氢化苯乙烯/异戊二烯共聚物、霍霍巴籽油、辛基十二醇、角鲨烷、甜扁桃油、向日葵籽油、红没药醇、苯氧乙醇、生育酚乙酸酯、乙基己基甘油、香精、可能含有、着色剂 CI 15985、着色剂 CI 15850、着色剂 CI 77499', E'已翻译'),
  (E'mercayshchie-teni-sparkly-dlya-vek-pusy-sand-100466', E'Calcium Aluminum Borosilicate, Polymethylsilsesquioxane, Octyldodecanol, Synthetic Fluorphlogopite, Dimethicone, Triethylhexanoin, Caprylic/Capric Triglyceride, Dimethicone/Vinyl Dimethicone Crosspolymer, Mica, Tridecyl Trimellitate, Stearyl Dimethicone, Octadecene, C10-18 Triglycerides, Phenoxyethanol, Tocopheryl Acetate, Hydrogenated Sunflower Seed Oil, Tin Oxide, Ethylhexylglycerin, CI 77891, CI 16035, CI 19140, CI 45410, CI 77266, CI 77499.', E'硼硅酸铝钙、聚甲基倍半硅氧烷、辛基十二醇、合成氟金云母、聚二甲基硅氧烷、三乙基己酸甘油酯、辛酸/癸酸甘油三酯、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、云母、偏苯三酸十三烷基酯、硬脂基聚二甲硅氧烷、十八碳烯、C10-18 脂酸甘油三酯类、苯氧乙醇、生育酚乙酸酯、氢化向日葵籽油、氧化锡、乙基己基甘油、着色剂 CI 77891、着色剂 CI 16035、着色剂 CI 19140、着色剂 CI 45410、着色剂 CI 77266、着色剂 CI 77499', E'已翻译'),
  (E'mercayshchie-teni-sparkly-dlya-vek-pusy-secret-garden-100468', E'Calcium Aluminum Borosilicate, Dimethicone, Triethylhexanoin, Caprylic/Capric Triglyceride, Dimethicone/Vinyl Dimethicone Crosspolymer, Tridecyl Trimellitate, Stearyl Dimethicone, Octyldodecanol, Kaolin, Mica, Silica, Octadecene, Calcium Sodium Borosilicate, C10-18 Triglycerides, Magnesium Stearate, Boron Nitride, Hydrogenated Sunflower Seed Oil, Phenoxyethanol, Tocopheryl Acetate, Tin Oxide, Ethylhexylglycerin, CI 77163, CI 77891, CI 77491, CI 45410.', E'硼硅酸铝钙、聚二甲基硅氧烷、三乙基己酸甘油酯、辛酸/癸酸甘油三酯、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、偏苯三酸十三烷基酯、硬脂基聚二甲硅氧烷、辛基十二醇、高岭土、云母、二氧化硅、十八碳烯、硼硅酸钙钠、C10-18 脂酸甘油三酯类、硬脂酸镁、氮化硼、氢化向日葵籽油、苯氧乙醇、生育酚乙酸酯、氧化锡、乙基己基甘油、着色剂 CI 77163、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 45410', E'已翻译'),
  (E'jidkie-rumyana-dlya-lica-sleepy-morning-pylnaya-roza-100769', E'Aqua，Isohexadecane，Isododecane，Dimethicone，Butylene Glycol，Tridecyl Trimellitate，Kaolin，Lauryl Peg-10 Tris(Trimethylsiloxy)Silylethyl Dimethicone, Polyglyceryl-2 Triisostearate，Trimethylsiloxysilicate，Mica，Disteardimonium Hectorite，Silica, Cetyl Peg/Ppg-10/1 Dimethicone，Sodium Chloride，Phenoxyethanol，Tribehenin，Sorbitan Sesquioleate，1,2-Hexanediol，Dimethicone/Vinyl Dimethicone Crosspolymer，Propylene Carbonate，Caprylyl Glycol，Tocopheryl Acetate，Xanthan Gum，Olea Europaea (Olive) Fruit Oil，Parfum，Sodium Hyaluronate，Benzyl Alcohol，Vanillin， CI 77891，CI 77491, CI 77492，CI 15850，CI 15985, CI 77499.', E'水、异十六烷、异十二烷、聚二甲基硅氧烷、丁二醇、偏苯三酸十三烷基酯、高岭土、月桂基 PEG-10 三（三甲基硅氧基）甲硅烷基乙基聚二甲基硅氧烷、三异硬脂酸聚甘油-2、三甲基硅烷氧基硅酸酯、云母、二硬脂二甲铵锂蒙脱石、二氧化硅、鲸蜡基 PEG/PPG-10/1 聚二甲基硅氧烷、氯化钠、苯氧乙醇、山嵛酸甘油三酯、倍半油酸山梨坦、1,2-己二醇、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、碳酸丙烯酯、辛甘醇、生育酚乙酸酯、黄原胶、油橄榄果油、香精、透明质酸钠、苄醇、香兰素、着色剂 CI 77891、着色剂 CI 77491、着色剂 CI 77492、着色剂 CI 15850、着色剂 CI 15985、着色剂 CI 77499', E'已翻译'),
  (E'jidkie-rumyana-dlya-lica-smoochies-rozovyiy-100770', E'Aqua，Isohexadecane，Isododecane，Dimethicone，Butylene Glycol，Tridecyl Trimellitate，Kaolin，Lauryl Peg-10 Tris(Trimethylsiloxy)Silylethyl Dimethicone, Polyglyceryl-2 Triisostearate，Trimethylsiloxysilicate，Mica，Disteardimonium Hectorite，Silica, Cetyl Peg/Ppg-10/1 Dimethicone，Sodium Chloride，Phenoxyethanol，Tribehenin，Sorbitan Sesquioleate，1,2-Hexanediol，Dimethicone/Vinyl Dimethicone Crosspolymer，Propylene Carbonate，Caprylyl Glycol，Tocopheryl Acetate，Xanthan Gum，Olea Europaea (Olive) Fruit Oil，Parfum，Sodium Hyaluronate，Benzyl Alcohol，Vanillin， CI 77891，CI 77492，CI 15850，CI 77499.', E'水、异十六烷、异十二烷、聚二甲基硅氧烷、丁二醇、偏苯三酸十三烷基酯、高岭土、月桂基 PEG-10 三（三甲基硅氧基）甲硅烷基乙基聚二甲基硅氧烷、三异硬脂酸聚甘油-2、三甲基硅烷氧基硅酸酯、云母、二硬脂二甲铵锂蒙脱石、二氧化硅、鲸蜡基 PEG/PPG-10/1 聚二甲基硅氧烷、氯化钠、苯氧乙醇、山嵛酸甘油三酯、倍半油酸山梨坦、1,2-己二醇、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、碳酸丙烯酯、辛甘醇、生育酚乙酸酯、黄原胶、油橄榄果油、香精、透明质酸钠、苄醇、香兰素、着色剂 CI 77891、着色剂 CI 77492、着色剂 CI 15850、着色剂 CI 77499', E'已翻译'),
  (E'glyancevyiy-tint-dlya-gub-sugar-plum-1-100841', E'Aqua, Dimethicone, Dicaprylyl Carbonate, Isononyl Isononanoate, Propylene Glycol, Glycerin, Butylene Glycol, Bis -Diglyceryl Polyacyladipate -2, Synthetic Beeswax, Polyglyceryl -10 Myristate, Polyacrylate Crosspolymer -6, Sodium Acrylate/Sodium Acryloyldimethyl Taurate Copolymer, 1,2 -Hexanediol, Parfum, Isohexadecane, Potassium Acesulfame, Caprylhydroxamic Acid, Polysorbate 80, Disodium EDTA, Sodium Chloride, Sodium Sulfate, CI 17200, CI 19140, CI 42090.', E'水、聚二甲基硅氧烷、碳酸二辛酯、异壬酸异壬酯、丙二醇、甘油、丁二醇、聚己二酸双-二甘油酯-2、合成蜂蜡、聚甘油-10 肉豆蔻酸酯、聚丙烯酸酯交联聚合物-6、丙烯酸钠/丙烯酰二甲基牛磺酸钠共聚物、1,2-己二醇、香精、异十六烷、乙酰磺胺酸钾、辛酰羟肟酸、聚山梨醇酯-80、乙二胺四乙酸二钠、氯化钠、硫酸钠、着色剂 CI 17200、着色剂 CI 19140、着色剂 CI 42090', E'已翻译'),
  (E'jidkie-rumyana-dlya-lica-toasty-korichnevyiy-100771', E'Aqua，Isohexadecane，Isododecane，Dimethicone，Butylene Glycol，Tridecyl Trimellitate，Kaolin，Lauryl Peg-10 Tris(Trimethylsiloxy)Silylethyl Dimethicone, Polyglyceryl-2 Triisostearate，Trimethylsiloxysilicate，Mica，Disteardimonium Hectorite，Silica, Cetyl Peg/Ppg-10/1 Dimethicone，Sodium Chloride，Phenoxyethanol，Tribehenin，Sorbitan Sesquioleate，1,2-Hexanediol，Dimethicone/Vinyl Dimethicone Crosspolymer，Propylene Carbonate，Caprylyl Glycol，Tocopheryl Acetate，Xanthan Gum，Olea Europaea (Olive) Fruit Oil，Parfum，Sodium Hyaluronate，Benzyl Alcohol，Vanillin， CI 77891，CI 77492，CI 77491, CI 77499, CI 15850.', E'水、异十六烷、异十二烷、聚二甲基硅氧烷、丁二醇、偏苯三酸十三烷基酯、高岭土、月桂基 PEG-10 三（三甲基硅氧基）甲硅烷基乙基聚二甲基硅氧烷、三异硬脂酸聚甘油-2、三甲基硅烷氧基硅酸酯、云母、二硬脂二甲铵锂蒙脱石、二氧化硅、鲸蜡基 PEG/PPG-10/1 聚二甲基硅氧烷、氯化钠、苯氧乙醇、山嵛酸甘油三酯、倍半油酸山梨坦、1,2-己二醇、聚二甲基硅氧烷/乙烯基聚二甲基硅氧烷交联聚合物、碳酸丙烯酯、辛甘醇、生育酚乙酸酯、黄原胶、油橄榄果油、香精、透明质酸钠、苄醇、香兰素、着色剂 CI 77891、着色剂 CI 77492、着色剂 CI 77491、着色剂 CI 77499、着色剂 CI 15850', E'已翻译'),
  (E'jele-dlya-gub-autumn-1-100675', E'Octyldodecanol, Hydrogenated Polyisobutene, Bis-Behenyl/Isostearyl/Phytosteryl Dimer Dilinoleyl Dimer Dilinoleate, Polyglyceryl-2 Triisostearate, Ethylcellulose, Microcrystalline Wax, Phenoxyethanol, Ethylene/Propylene Copolymer, Caprylyl Glycol, Hydrogenated Polydecene, Ethylhexyl Palmitate, Polybutene, Pentaerythrityl Tetra-Di-T-Butyl Hydroxyhydrocinnamate, Tocopheryl Acetate, Sorbitan Sesquioleate, CI 15850, CI 77499, CI 77491.', E'辛基十二醇、氢化聚异丁烯、双-山嵛醇/异硬脂醇/植物甾醇二聚亚油醇二聚亚油酸酯、三异硬脂酸聚甘油-2、乙基纤维素、微晶蜡、苯氧乙醇、乙烯/丙烯共聚物、辛甘醇、氢化聚癸烯、棕榈酸乙基己酯、聚丁烯、四（双-叔丁基羟基氢化肉桂酸）季戊四醇酯、生育酚乙酸酯、倍半油酸山梨坦、着色剂 CI 15850、着色剂 CI 77499、着色剂 CI 77491', E'已翻译'),
  (E'uvlajnyayshchiiy-mist-dlya-lica-pusy-moisturizing-face-mist-pusy-100-ml-100201', E'Aqua, Cocos Nucifera Water, Cucumis Sativus Fruit Water, 1,2-Hexanediol, Propylene glycol, Glycerin, Biosaccharide Gum-1, Polysorbate 20, Sodium Hyaluronate, Disodium EDTA, Ethylhexylglycerin, Phenoxyethanol, Ceramide 1, Ceramide 2, Ceramide 3, Ceramide 6 Il, Butylene Glycol, Hydrogenated Lecithin, Caprylic/Capric Glycerides Polyglyceryl-10 Esters, Pentylene Glycol, Citrus Aurantifolia Fruit Extract, Potassium sorbate, Sodium benzoate, Sodium Hydroxide, Parfum.', E'水、椰子水、黄瓜果水、1,2-己二醇、丙二醇、甘油、生物糖胶-1、聚山梨醇酯-20、透明质酸钠、乙二胺四乙酸二钠、乙基己基甘油、苯氧乙醇、神经酰胺 1、神经酰胺 2、神经酰胺 3、神经酰胺 6 II、丁二醇、氢化卵磷脂、辛酸/癸酸甘油酯类聚甘油-10 酯类、戊二醇、来檬果提取物、山梨酸钾、苯甲酸钠、氢氧化钠、香精', E'已翻译'),
  (E'gialuronovyiy-krem-dlya-lica-pusy-pusy-hyaluronic-face-cream-50-ml-8-100496', E'Aqua, Dicaprylyl Carbonate, Coco-Caprylate, Cetearyl Alcohol, Cetearyl Glucoside, Caprylic/Capric Triglyceride, Glycerin, Simmondsia Chinensis (Jojoba) Seed Oil, Cupressus Sempervirens Leaf Water, Hydrogenated Starch Hydrolysate, Aphanizomenon Flosa-quae Extract, Caprylic/Capric Glycerides, Polyglyceryl-10 Esters, Pentylene Glycol, Butyrospermum Parkii (Shea Butter), Theobroma Cacao Seed Butter, Sodium Hyaluronate, Panthenol, Phenoxyethanol, Ethylhexylglycerin, Myristyl Myristate, Carbomer, Ceramide 1, Ceramide 2, Ceramide 3, Ceramide 6 li, Butylene Glycol, Hydrogenated Lecithin, Sodium Hydroxide, Parfum, Alpha-Isomethyl lonone, Hexyl Cinnamal, Limonene, Linalool.', E'水、碳酸二辛酯、椰油醇-辛酸酯、鲸蜡硬脂醇、鲸蜡硬脂基葡糖苷、辛酸/癸酸甘油三酯、甘油、霍霍巴籽油、地中海柏木叶水、氢化淀粉水解物、水华束丝藻提取物、辛酸/癸酸甘油酯类、聚甘油-10 酯类、戊二醇、乳木果油、可可籽脂、透明质酸钠、泛醇、苯氧乙醇、乙基己基甘油、肉豆蔻醇肉豆蔻酸酯、卡波姆、神经酰胺 1、神经酰胺 2、神经酰胺 3、神经酰胺 6 II、丁二醇、氢化卵磷脂、氢氧化钠、香精、α-异甲基紫罗兰酮、己基肉桂醛、柠檬烯、芳樟醇', E'已翻译'),
  (E'rebrending-utrenniiy-ohlajdayshchiiy-tonik-dlya-koji-lica-i-shei-pusy150ml-100232', E'Aqua, Pinus Sylvestris Wood Extract, Propylene Glycol, Glycerin, Biosaccharide Gum-1, Chondrus Crispus Extract, Palmaria Palmata Extract, Panthenol, Citrus Aurantium Dulcis Juice, Citrus Limon Juice, Zingiber Officinale Root Juice, Polysorbate 20, Ethyl Menthane Carboxamide, Disodium EDTA, Ethylhexylglycerin, Phenoxyethanol, Caffeine, Sodium Hydroxide, Sodium Benzoate, Citric Acid, Potassium Sorbate, Parfum, Benzyl Salicylate, Hexyl Cinnamaldehyd.', E'水、欧洲赤松木提取物、丙二醇、甘油、生物糖胶-1、皱波角叉菜提取物、掌状红皮藻提取物、泛醇、甜橙汁、柠檬汁、姜根汁、聚山梨醇酯-20、乙基薄荷烷甲酰胺、乙二胺四乙酸二钠、乙基己基甘油、苯氧乙醇、咖啡因、氢氧化钠、苯甲酸钠、柠檬酸、山梨酸钾、香精、水杨酸苄酯、己基肉桂醛', E'已翻译'),
  (E'rebrending-micellyarnaya-voda-pusy-300-ml-100192', E'Aqua, Peg-6 Caprylic / Capric Glycerides, Pinus Sylvestris Wood Extract, Propylene Glycol, Glycerin, Tilia Cordata Flower Water, Mentha Piperita Flower / Leaf / Stem Water, Cucumis Sativus Extract, Potassium Sorbate, Sodium Benzoate, Rosmarinus Officinalis Water, Panthenol, Disodium EDTA, Parfum, Caprylyl Glycol, Methylpropanediol, Didecyldimonium Chloride, Polyquaternium-80, Sodium Hydroxide, Benzyl Alcohol, Dehydroacetic Acid', E'水、PEG-6 辛酸/癸酸甘油酯类、欧洲赤松木提取物、丙二醇、甘油、小叶椴花水、辣薄荷花/叶/茎水、黄瓜提取物、山梨酸钾、苯甲酸钠、迷迭香水、泛醇、乙二胺四乙酸二钠、香精、辛甘醇、甲基丙二醇、二癸基二甲基氯化铵、聚季铵盐-80、氢氧化钠、苄醇、脱氢乙酸', E'已翻译'),
  (E'rebrending-penka-dlya-umyvaniya-pusy150ml-100227', E'Aqua, Sodium Cocoamphoacetate, Hydroxyethyl urea, Cocamidopropyl Betaine, Decyl Glucoside, PEG-7 Glyceryl Cocoate, Coco-Glucoside, Glyceryl Oleate, Avena Sativa Leaf/Stalk Extract, Saccharomyces Ferment Lysate Filtrate, Laminaria Digitata Extract, Citrus Aurantium Dulcis Juice, Citrus Limon Juice, Zingiber Officinale Root Juice, Parfum, Panthenol, Glycerin, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Chloride, Disodium EDTA.', E'水、椰油酰两性基乙酸钠、羟乙基脲、椰油酰胺丙基甜菜碱、癸基葡糖苷、PEG-7 甘油椰油酸酯、椰油基葡糖苷、油酸甘油酯、燕麦叶/茎提取物、酵母菌发酵产物溶胞产物滤液、掌状海带提取物、甜橙汁、柠檬汁、姜根汁、香精、泛醇、甘油、苯氧乙醇、乙基己基甘油、柠檬酸、苯甲酸钠、山梨酸钾、氯化钠、乙二胺四乙酸二钠', E'已翻译'),
  (E'ochishchayshchiiy-gel-dlya-umyvaniya-pusy-purifying-facial-cleanser-pusy-110-ml-1-1-100481', E'Aqua, Acrylates/ Palmeth-25 Acrylate Copolymer, Disodium Laureth Sulfosuccinate, PEG-7 Glyceryl Cocoate, Cocamidopropyl Betaine, Sodium Coco-Sulfate, Biosaccharide Gum-1, Panthenol, Centella Asiatica Extract, Actinidia Chinensis Extract, Sodium Hydroxide, Phenoxyethanol, Ethylhexylglycerin, Sodium Cocoamphoacetate, Rosmarinus Officinalis Water, Citrus Aurantifolia Fruit Extract, Carica Papaya Fruit Extract, Sodium chloride, Glycerin, Palmaria Palmata Extract, Melaleuca Аlternifolia (Tea tree) Leaf Water, Sodium Benzoate, Citric Acid, 1,2-Hexanediol, Disodium EDTA, Potassium Sorbate, Benzyl Alcohol, Dehydroacetic Acid, Propylene Glycol, Parfum, Limonene, Linalool, Citronellol', E'水、丙烯酸（酯）类/棕榈醇聚醚-25 丙烯酸酯共聚物、月桂醇聚醚磺基琥珀酸酯二钠、PEG-7 甘油椰油酸酯、椰油酰胺丙基甜菜碱、椰油醇硫酸酯钠、生物糖胶-1、泛醇、积雪草提取物、中华猕猴桃提取物、氢氧化钠、苯氧乙醇、乙基己基甘油、椰油酰两性基乙酸钠、迷迭香水、来檬果提取物、番木瓜果提取物、氯化钠、甘油、掌状红皮藻提取物、互生叶白千层叶水、苯甲酸钠、柠檬酸、1,2-己二醇、乙二胺四乙酸二钠、山梨酸钾、苄醇、脱氢乙酸、丙二醇、香精、柠檬烯、芳樟醇、香茅醇', E'已翻译'),
  (E'rebrending-gialuronovaya-emulsiya-dlya-lica-pusy50ml-100191', E'Aqua, Dicaprylyl Carbonate, Glycerin, Coco-Caprylate/Caprate, Coco-Caprylate, Caprylic/Capric Triglyceride, Squalane, Cetearyl Alcohol, Panthenol, Myristyl Myristate, Snail Secretion Filtrate, Phenethyl Alcohol, Caprylyl Glycol, Butyrospermum Parkii (Shea) Butter, Nicotinamide, D-Biotin, Sodium Polyacrylate, Avena Sativa Leaf/Stalk Extract, Saccharomyces Ferment Lysate Filtrate, Tocopheryl Acetate, Sodium Hyaluronate, Simmondsia Chinensis (Jojoba) Seed Oil, Disodium Cetearyl Sulfosuccinate, Phenoxyethanol, Ethylhexylglycerin, Ceramide 1, Ceramide 2, Ceramide 3, Ceramide 6 ll, Butylene Glycol, Hydrogenated Lecithin, Caprylic/Capric Glycerides Polyglyceryl-10 Esters, Pentylene Glycol, Citric Acid, Sodium Benzoate, Potassium Sorbate, Parfum, Benzyl Benzoate, Hexyl Cinnamal, Limonene.', E'水、碳酸二辛酯、甘油、椰油醇-辛酸酯/癸酸酯、椰油醇-辛酸酯、辛酸/癸酸甘油三酯、角鲨烷、鲸蜡硬脂醇、泛醇、肉豆蔻醇肉豆蔻酸酯、蜗牛分泌物滤液、苯乙醇、辛甘醇、乳木果油、烟酰胺、生物素、聚丙烯酸钠、燕麦叶/茎提取物、酵母菌发酵产物溶胞产物滤液、生育酚乙酸酯、透明质酸钠、霍霍巴籽油、鲸蜡硬脂醇磺基琥珀酸酯二钠、苯氧乙醇、乙基己基甘油、神经酰胺 1、神经酰胺 2、神经酰胺 3、神经酰胺 6 II、丁二醇、氢化卵磷脂、辛酸/癸酸甘油酯类聚甘油-10 酯类、戊二醇、柠檬酸、苯甲酸钠、山梨酸钾、香精、苯甲酸苄酯、己基肉桂醛、柠檬烯', E'已翻译'),
  (E'rebrending-piling-skatka-pusy100ml-100193', E'Aqua, Propylene Glycol, Microcrystalline cellulose, Citrus Aurantium Dulcis Juice, Citrus Limon Juice, Zingiber Officinale Root Juice, Cetrimonium Chloride, Carbomer, Phenoxyethanol, Ethylhexylglycerin, PEG-40 Hydrogenated Castor Oil, Citric Acid, Sodium Benzoate, Potassium Sorbate, Partum, Hexyl Cinnamal, Linalool.', E'水、丙二醇、微晶纤维素、甜橙汁、柠檬汁、姜根汁、西曲氯铵、卡波姆、苯氧乙醇、乙基己基甘油、PEG-40 氢化蓖麻油、柠檬酸、苯甲酸钠、山梨酸钾、香精、己基肉桂醛、芳樟醇', E'已翻译'),
  (E'gidrofilnoe-maslo-dlya-lica-pusy-110-ml-100733', E'Caprylic/Capric Triglyceride, Glycine Soja (Soybean) Oil, Sorbeth-30 Tetraoleate, Silica Dimethyl Silylate, Coco-Caprylate/Caprate, Isononyl Isononanoate, Simmondsia Chinensis (Jojoba) Seed Oil, Squalane, Crambe Abyssinica Seed Oil, Glycine Soja Oil, Amaranthus Caudatus Seed Extract, Аesculus Hippocastanum Fruit Extract, Rosmarinus Officinalis (Rosemary) Leaf Extract, Tocopheryl Acetate, Parfum, Citral, Citronellol, Hydroxycitronellal, Limonene, Linalool.', E'辛酸/癸酸甘油三酯、大豆油、山梨醇聚醚-30 四油酸酯、甲硅烷基化硅石、椰油醇-辛酸酯/癸酸酯、异壬酸异壬酯、霍霍巴籽油、角鲨烷、深海两节荠籽油、大豆油、尾穗苋籽提取物、七叶树果提取物、迷迭香叶提取物、生育酚乙酸酯、香精、柠檬醛、香茅醇、羟基香茅醛、柠檬烯、芳樟醇', E'已翻译'),
  (E'avtozagar-dlya-lica-pusy-magic-water-face-self-tanner-pusy-magic-water-100-ml-25-100566', E'Aqua, Dihydroxyacetone, Propylene Glycol, Polysorbate 20, Erythrulose, Glycerin, Laminaria Digitata Extract, Citric Acid, Centella Asiatica Extract, Panthenol, Mentha Perita Flower/Leaf/Stem Water, Anthemis Nobilis Flower Water, Sodium Hyaluronate, Ethylhexylglycerin, Phenoxyethanol, Sodium benzoate, Potassium Sorbate, Benzyl Alcohol, Dehydroacetic Acid, Parfum, Benzyl Salicylate, Linalool, Limonene.', E'水、二羟基丙酮、丙二醇、聚山梨醇酯-20、赤藓酮糖、甘油、掌状海带提取物、柠檬酸、积雪草提取物、泛醇、辣薄荷花/叶/茎水、白花春黄菊花水、透明质酸钠、乙基己基甘油、苯氧乙醇、苯甲酸钠、山梨酸钾、苄醇、脱氢乙酸、香精、水杨酸苄酯、芳樟醇、柠檬烯', E'已翻译'),
  (E'gel-massajer-pusy-refresh-face-gel-75-ml-26-100375', E'Aqua, Glycerin, Propylene, Glycol, Polysorbate 20, Sodium PCA, Glucose, Urea, Glutamic Acid, Lysine, Glycine, Allantoin, Lactic Acid, Potassium Sorbate, Sodium Benzoate, Gluconolactone, Calcium Gluconate, Aesculus Hippocastanum Seed Extract, Ruscus Aculeatus Root Extract, Centella Asiatica Extract, Vitis Vinifera Extract, Hedera Helix Leaf Extract, Polygonum Fagopyrum (Buckwheat) Leaf Extract, Troxerutin, Ethyl Menthane Carboxamide, Phenoxyethanol, Ethylhexylglycerin, Caffeine, Sodium Hydroxide, Parfum, Benzyl Salicylate, Hydroxycitronellal, Limonene, Linalool, Disodium EDTA, Sodium Hyaluronate, Carbomer', E'水、甘油、丙二醇、聚山梨醇酯-20、PCA 钠、葡萄糖、尿素、谷氨酸、赖氨酸、甘氨酸、尿囊素、乳酸、山梨酸钾、苯甲酸钠、葡糖酸内酯、葡糖酸钙、七叶树籽提取物、假叶树根提取物、积雪草提取物、葡萄提取物、常春藤叶提取物、荞麦叶提取物、曲克芦丁、乙基薄荷烷甲酰胺、苯氧乙醇、乙基己基甘油、咖啡因、氢氧化钠、香精、水杨酸苄酯、羟基香茅醛、柠檬烯、芳樟醇、乙二胺四乙酸二钠、透明质酸钠、卡波姆', E'已翻译'),
  (E'pena-dlya-vanny-psy-bath-foam-200-ml-100187', E'Aqua; Coco-Glucoside; Sodium Сoco-sulfate; Cocamidopropyl Betaine; parfum; glycerin; Panthenol; Phenoxyethanol; Ethylhexylglycerin; Citric Acid; Disodium; EDTA; СI 14720', E'水、椰油基葡糖苷、椰油醇硫酸酯钠、椰油酰胺丙基甜菜碱、香精、甘油、泛醇、苯氧乙醇、乙基己基甘油、柠檬酸、EDTA 二钠、着色剂 CI 14720', E'已翻译'),
  (E'pusy-home-sol-dlya-vanny-bath-salt-400g-100160', E'Sodium Chloride (Sea Salt), Sodium Chloride (Himalayan Salt), Parfum.', E'氯化钠（海盐）、氯化钠（喜马拉雅盐）、香精', E'已翻译'),
  (E'gel-dlya-jestkih-broveiy-100799', E'Aqua, VP/VA, Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethypropanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸', E'已翻译'),
  (E'karandash-dlya-broveiy-s-refilom-medium-brown-100758', E'C10-18 Triglycerides, Copernicia Cerifera (Carnauba) Wax, Hydrogenated Coco-Glycerides, Hydrogenated C12-18 Triglycerides, Hydrogenated Rapeseed Oil, Hydrogenated Palm Kernel Oil, Mica, Paraffin, Hydrogenated Soybean Oil, Microcrystalline Wax, Bis-Diglyceryl Polyacyladipate-2, Glyceryl Stearates, Triethoxycaprylylsilane, Rhus Succedanea Fruit Wax, Stearic Acid, Caprylyl Glycol, CI 77499, CI 77492, CI 77491, CI 77163, CI 77891.', E'C10-18 脂酸甘油三酯类、巴西棕榈树蜡、氢化椰油甘油酯类、氢化 C12-18 甘油三酯类、氢化菜籽油、氢化棕榈仁油、云母、石蜡、氢化大豆油、微晶蜡、聚己二酸双-二甘油酯-2、甘油硬脂酸酯、三乙氧基辛基硅烷、漆树果蜡、硬脂酸、辛甘醇、着色剂 CI 77499、着色剂 CI 77492、着色剂 CI 77491、着色剂 CI 77163、着色剂 CI 77891', E'已翻译'),
  (E'refil-karandasha-dlya-broveiy-light-brown-100757', E'C10-18 Triglycerides, Copernicia Cerifera (Carnauba) Wax, Hydrogenated Coco-Glycerides, Hydrogenated C12-18 Triglycerides, Hydrogenated Rapeseed Oil, Hydrogenated Palm Kernel Oil, Mica, Paraffin, Hydrogenated Soybean Oil, Microcrystalline Wax, Bis-Diglyceryl Polyacyladipate-2, Glyceryl Stearates, Triethoxycaprylylsilane, Rhus Succedanea Fruit Wax, Stearic Acid, Caprylyl Glycol, CI 77499, CI 77492, CI 77491, CI 77163, CI 77891.', E'C10-18 脂酸甘油三酯类、巴西棕榈树蜡、氢化椰油甘油酯类、氢化 C12-18 甘油三酯类、氢化菜籽油、氢化棕榈仁油、云母、石蜡、氢化大豆油、微晶蜡、聚己二酸双-二甘油酯-2、甘油硬脂酸酯、三乙氧基辛基硅烷、漆树果蜡、硬脂酸、辛甘醇、着色剂 CI 77499、着色剂 CI 77492、着色剂 CI 77491、着色剂 CI 77163、着色剂 CI 77891', E'已翻译'),
  (E'gel-dlya-ukladki-broveiy-pusy-brow-fix-professional-15ml-10-100535', E'Aqua, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate, Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Disodium EDTA, Citric Acid, Parfum, Limonene, Eugenol, Coumarin', E'水、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷醇丙烯酸酯交联聚合物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、乙二胺四乙酸二钠、柠檬酸、香精、柠檬烯、丁香酚、香豆素', E'已翻译'),
  (E'prozrachnyiy-gel-fiksator-dlya-broveiy-100801', E'Aqua, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl\nMethacrylate, Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Disodium EDTA, Citric Acid, Parfum, Limonene, Eugenol, Coumarin', E'水、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷醇丙烯酸酯交联聚合物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、乙二胺四乙酸二钠、柠檬酸、香精、柠檬烯、丁香酚、香豆素', E'已翻译'),
  (E'rebrending-prozrachnyiy-gel-fiksator-dlya-broveiy-pusy-5-ml-100797', E'Aqua, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate, Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Disodium EDTA, Citric Acid, Parfum, Limonene, Eugenol, Coumarin', E'水、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷醇丙烯酸酯交联聚合物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、乙二胺四乙酸二钠、柠檬酸、香精、柠檬烯、丁香酚、香豆素', E'已翻译'),
  (E'prozrachnyiy-super-gel-fiksator-dlya-broveiy-super-fix-brow-gel-pusy-25-ml-13-100641', E'Aqua, VP/VA Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid.', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸', E'已翻译'),
  (E'vosstanavlivayshchiiy-gel-fiksator-dlya-broveiy-100798', E'Aqua, VP/VA Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethyl Propanol, Biotinoyl Tripeptide-1, 1,2-Hexanediol, Arginine, Lactic Acid, Glycine Soja Germ Extract, Triticum Vulgare Germ Extract, Scutellaria Baicalensis Root Extract, Gluconolactone, Calcium Gluconate, Serenoa Serrulata Fruit Extract, Panthenol, Hydrolyzed Keratin, Biotin, Niacinamide, Camellia Sinensis Leaf Water, Aloe Barbadensis Leaf Juice, Sodium Hyaluronate, PEG-40 Hydrogenated Castor Oil, Propanediol, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid, Dehydroacetic Acid, Benzyl Alcohol, Potassium Sorbate, Sodium Benzoate.', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、生物素酰三肽-1、1,2-己二醇、精氨酸、乳酸、大豆胚芽提取物、小麦胚芽提取物、黄芩根提取物、葡糖酸内酯、葡糖酸钙、锯叶棕果提取物、泛醇、水解角蛋白、生物素、烟酰胺、茶叶水、库拉索芦荟叶汁、透明质酸钠、PEG-40 氢化蓖麻油、丙二醇、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸、脱氢乙酸、苄醇、山梨酸钾、苯甲酸钠', E'已翻译'),
  (E'fiksiruyshchiiy-gel-dlya-broveiy-pusy-lamination-5-ml-5-1-100619', E'Aqua, PVP, Propylene Glycol,Glycerin, Acrylates/Palmeth-25 Acrylate Copolymer, PEG-40 Hydrogenated Castor Oil, PPG-26-Buteth-26, DMDM Hydantoin, Sodium Hydroxide, Disodium EDTA, Parfum, Benzyl Salicylate, Citral.', E'水、聚乙烯吡咯烷酮、丙二醇、甘油、丙烯酸（酯）类/棕榈醇聚醚-25 丙烯酸酯共聚物、PEG-40 氢化蓖麻油、PPG-26-丁醇聚醚-26、DMDM 乙内酰脲、氢氧化钠、乙二胺四乙酸二钠、香精、水杨酸苄酯、柠檬醛', E'已翻译'),
  (E'karandash-dlya-broveiy-s-refilom-light-brown-light-brown-100804', E'C10-18 Triglycerides, Copernicia Cerifera (Carnauba) Wax, Hydrogenated Coco-Glycerides, Hydrogenated C12-18 Triglycerides, Hydrogenated Rapeseed Oil, Hydrogenated Palm Kernel Oil, Mica, Paraffin, Hydrogenated Soybean Oil, Microcrystalline Wax, Bis-Diglyceryl Polyacyladipate-2, Glyceryl Stearates, Triethoxycaprylylsilane, Rhus Succedanea Fruit Wax, Stearic Acid, Caprylyl Glycol, CI 77499, CI 77492, CI 77491, CI 77163.', E'C10-18 脂酸甘油三酯类、巴西棕榈树蜡、氢化椰油甘油酯类、氢化 C12-18 甘油三酯类、氢化菜籽油、氢化棕榈仁油、云母、石蜡、氢化大豆油、微晶蜡、聚己二酸双-二甘油酯-2、甘油硬脂酸酯、三乙氧基辛基硅烷、漆树果蜡、硬脂酸、辛甘醇、着色剂 CI 77499、着色剂 CI 77492、着色剂 CI 77491、着色剂 CI 77163', E'已翻译'),
  (E'karandash-dlya-broveiy-s-refilom-medium-brown-medium-brown-100805', E'C10-18 Triglycerides, Copernicia Cerifera (Carnauba) Wax, Hydrogenated Coco-Glycerides, Hydrogenated C12-18 Triglycerides, Hydrogenated Rapeseed Oil, Hydrogenated Palm Kernel Oil, Mica, Paraffin, Hydrogenated Soybean Oil, Microcrystalline Wax, Bis-Diglyceryl Polyacyladipate-2, Glyceryl Stearates, Rhus Succedanea Fruit Wax, Stearic Acid, Triethoxycaprylylsilane, Caprylyl Glycol, CI 77499, CI 77163.', E'C10-18 脂酸甘油三酯类、巴西棕榈树蜡、氢化椰油甘油酯类、氢化 C12-18 甘油三酯类、氢化菜籽油、氢化棕榈仁油、云母、石蜡、氢化大豆油、微晶蜡、聚己二酸双-二甘油酯-2、甘油硬脂酸酯、漆树果蜡、硬脂酸、三乙氧基辛基硅烷、辛甘醇、着色剂 CI 77499、着色剂 CI 77163', E'已翻译'),
  (E'super-gel-dlya-broveiy-100800', E'Aqua, VP/VA Copolymer, Glycerin, Acrylates Copolymer, Acrylates/C10-30 Alkyl Methacrylate Copolymer, Aminomethyl Propanol, Panthenol, PEG-40 Hydrogenated Castor Oil, Ethylhexylglycerin, Phenoxyethanol, Parfum, Disodium EDTA, Citric Acid.', E'水、VP/VA 共聚物、甘油、丙烯酸（酯）类共聚物、丙烯酸（酯）类/C10-30 烷基甲基丙烯酸酯共聚物、氨甲基丙醇、泛醇、PEG-40 氢化蓖麻油、乙基己基甘油、苯氧乙醇、香精、乙二胺四乙酸二钠、柠檬酸', E'已翻译'),
  (E'mnogofunkcionalnaya-kist-pusy-touch-point-32-gr-100252', E'Ручка: полистирол, алюминий; Ворс: синтетические нити (ПБТ)', E'刷柄：聚苯乙烯、铝、刷毛：聚对苯二甲酸丁二醇酯（PBT）合成纤维', E'已翻译'),
  (E'kosmetichka-magic-bag-pusy-100248', NULL, E'本品为配件，不适用化妆品成分表；材质请以商品实物标签标注为准。', E'材质说明'),
  (E'mini-kosmetichka-magic-bag-pusy-100251', NULL, E'本品为配件，不适用化妆品成分表；材质请以商品实物标签标注为准。', E'材质说明'),
  (E'odnorazovye-netkanye-polotenca-dlya-lica-pusy-clean-girl-80sht-up-100224', E'100% вискоза (нетканое полотно)', E'100% 粘胶纤维（无纺布）', E'已翻译'),
  (E'kosmetichka-oblachko-pusy-100249', E'Текстильный материал – 100% полиэстер.\nНаполнитель – 100% полипропиленовое волокно.', E'纺织材料：100% 聚酯纤维\n填充物：100% 聚丙烯纤维', E'已翻译'),
  (E'silikonovaya-kosmetichka-pusy-silicase-1-1-100549', NULL, E'本品为配件，不适用化妆品成分表；材质请以商品实物标签标注为准。', E'材质说明'),
  (E'rebrending-uvlajnyayshchiiy-krem-dlya-ruk-pusy-tobacco-pepper-vanilla-13-100658', E'Aqua, Rosa Damascena Flower Water, Coco-Caprylate, Glycerin, Octyldodecano, Butyrospermum Parkii (Shea) Butter, Cetearyl Alcohol, Glyceryl Stearate, PEG-100 Stearate, Cyclopentasiloxane, Dimethicone, Phenoxyethanol, Ethylhexylglycerin, Panthenol, Sodium Polyacrylate, Carbomer, Tocopheryl Acetate, Sodium Hyaluronate, Avena Sativa Leaf/Stalk Extract, Saccharomyces Ferment Lysate Filtrate, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Hydroxide, Parfum, Eugenol, Linalool.', E'水、突厥蔷薇花水、椰油醇-辛酸酯、甘油、辛基十二醇、乳木果油、鲸蜡硬脂醇、甘油硬脂酸酯、PEG-100 硬脂酸酯、环五聚二甲基硅氧烷、聚二甲基硅氧烷、苯氧乙醇、乙基己基甘油、泛醇、聚丙烯酸钠、卡波姆、生育酚乙酸酯、透明质酸钠、燕麦叶/茎提取物、酵母菌发酵产物溶胞产物滤液、柠檬酸、苯甲酸钠、山梨酸钾、氢氧化钠、香精、丁香酚、芳樟醇', E'已翻译'),
  (E'v-tube-gialuronovyiy-krem-gel-dlya-tela-pusy-hyaluronic-body-cream-gel-150-ml-100237', E'Aqua, Rosa Damascena Flower Water, Dicaprylyl Carbonate, Butylene Glycol, Coco-Caprylate, Hydroxypropyl Starch Phosphate, Brassica Campestris (Rapeseed) Sterols, Cetearyl Alcohol, Disodium Cetearyl Sulfosuccinate, Butyrospermum Parkii (Shea) Butter, Theobroma Cacao (Cocoa) Seed Butter, Brassica Oleracea Italica (Broccoli) Seed Oil, Panthenol, Glycerin, Sodium Hyaluronate, Pullulan, Trehalose, Urea, Serine, Algin, Pentylene Glycol, Caprylyl Glycol, Phenoxyethanol, Ethylhexylglycerin, Acrylates/Beheneth-25 Methacrylate Copolymer, Glyceryl Polyacrylate, Mica (CI 77019), Titanium Dioxide (CI 77891), Iron Oxides (CI 77491), Disodium EDTA, Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate, Cyclopentasiloxane, Disodium Phosphate, Potassium Phosphate, Sodium Hydroxide, Citric Acid, Parfum, Eugenol, Coumarin, Linalool, Limonene', E'水、突厥蔷薇花水、碳酸二辛酯、丁二醇、椰油醇-辛酸酯、羟丙基淀粉磷酸酯、油菜甾醇类、鲸蜡硬脂醇、鲸蜡硬脂醇磺基琥珀酸酯二钠、乳木果油、可可籽脂、西兰花籽油、泛醇、甘油、透明质酸钠、普鲁兰多糖、海藻糖、尿素、丝氨酸、藻酸、戊二醇、辛甘醇、苯氧乙醇、乙基己基甘油、丙烯酸（酯）类/山嵛醇聚醚-25 甲基丙烯酸酯共聚物、聚丙烯酸甘油酯、云母（着色剂 CI 77019）、二氧化钛（着色剂 CI 77891）、氧化铁（着色剂 CI 77491）、乙二胺四乙酸二钠、四（双-叔丁基羟基氢化肉桂酸）季戊四醇酯、环五聚二甲基硅氧烷、磷酸氢二钠、磷酸钾、氢氧化钠、柠檬酸、香精、丁香酚、香豆素、芳樟醇、柠檬烯', E'已翻译'),
  (E'gel-dlya-dusha-pusy-home-shower-body-gel-tobacco-pepper-vanilla-12-100495', E'Aqua, Sodium Сoco-Sulfate, Coco-Glucoside, Acrylates/Beheneth-25 Methacrylate Copolymer, Parfum, Sodium Cocoamphoacetate, Brassica Oleracea Italica Juice, Glycerin, Opuntia Ficus-Indica Stem Extract, Panthenol, PEG-40 Hydrogenated Castor Oil, Phenoxyethanol, Ethylhexylglycerin, Sodium Benzoate, Potassium Sorbate, Sodium Chloride, Citric Acid, Disodium EDTA, Sodium Hydroxide, Eugenol, Limonene', E'水、椰油醇硫酸酯钠、椰油基葡糖苷、丙烯酸（酯）类/山嵛醇聚醚-25 甲基丙烯酸酯共聚物、香精、椰油酰两性基乙酸钠、西兰花汁、甘油、仙人掌茎提取物、泛醇、PEG-40 氢化蓖麻油、苯氧乙醇、乙基己基甘油、苯甲酸钠、山梨酸钾、氯化钠、柠檬酸、乙二胺四乙酸二钠、氢氧化钠、丁香酚、柠檬烯', E'已翻译'),
  (E'skrab-dlya-tela-pusy-body-shimmering-scrub-250gr-100195', E'Glycerin, Sucrose, Hydrogenated Castor Oil, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Butyrospermum Parkii (Shea) Butter, Aqua, Cocamidopropyl Betaine, Brassica Oleracea Italica (Broccoli) Seed Oil, Parfum, Phenoxyethanol, Ethylhexylglycerin, Sodium Chloride, Synthetic Fluorphlogopite, Titanium Dioxide (CI 77891), Iron Oxides (CI 77491), Pentaerythrityl Tetra-di-t-butyl Hydroxyhydrocinnamate, Amyl cinnamal, Benzyl salicylate, Coumarin, Linalool, Limonene, Alpha-isomethyl lonone.', E'甘油、蔗糖、氢化蓖麻油、鲸蜡硬脂醇、辛酸/癸酸甘油三酯、乳木果油、水、椰油酰胺丙基甜菜碱、西兰花籽油、香精、苯氧乙醇、乙基己基甘油、氯化钠、合成氟金云母、二氧化钛（着色剂 CI 77891）、氧化铁（着色剂 CI 77491）、四（双-叔丁基羟基氢化肉桂酸）季戊四醇酯、戊基肉桂醛、水杨酸苄酯、香豆素、芳樟醇、柠檬烯、α-异甲基紫罗兰酮', E'已翻译'),
  (E'mercayshchiiy-spreiy-dlya-tela-pusy-shine-100ml-100250', NULL, E'原品牌页面暂未公开完整成分表，请以中国销售实物包装的成分标注为准。', E'待品牌确认'),
  (E'muss-avtozagar-dlya-tela-pusy-body-tan-mousse-body-tan-mousse-pusy-200-ml-4-100590', E'Aqua, Dihydroxyacetone, Propylene Glycol, Dimethyl Isosorbide, Glycerin, Polysor-bate 20, Cocamidopropyl Betaine, Erythrulose, Panthenol, Centella Asiatica Extract, Mangifera Indica Fruit Extract, Carica Papaya Fruit Extract, Sodium Hyaluronate, Tilia Cordata Flower Water, Cupressus Sempervirens Leaf Water, Xanthan Gum, Ethylhexylglycerin, Phenoxyethanol, 1,2-hexanediol, Sodium Benzoate, Potassium Sorbate, Parfum, Benzyl Salicylate, Linalool, Limonene.', E'水、二羟基丙酮、丙二醇、二甲基异山梨醇、甘油、聚山梨醇酯-20、椰油酰胺丙基甜菜碱、赤藓酮糖、泛醇、积雪草提取物、芒果果提取物、番木瓜果提取物、透明质酸钠、小叶椴花水、地中海柏木叶水、黄原胶、乙基己基甘油、苯氧乙醇、1,2-己二醇、苯甲酸钠、山梨酸钾、香精、水杨酸苄酯、芳樟醇、柠檬烯', E'已翻译'),
  (E'skrab-slaiym-dlya-tela-pusy-slime-scrub-250-g-100196', E'Sugar, Aqua, Cocamidopropyl Betaine, Glycerin, Sweet Almond Oil, Prunus Armeniaca Kernel Oil, Panthenol, Tocopherol, Squalane, Xanthan Gum, Aloe Barbadensis (Aloe Vera) Leaf Gel, Parfum, Citric Acid, Sodium Benzoate, Potassium Sorbate, Benzyl Alcohol, Cl 17200', E'糖、水、椰油酰胺丙基甜菜碱、甘油、甜扁桃油、杏仁油、泛醇、生育酚（维生素 E）、角鲨烷、黄原胶、库拉索芦荟叶凝胶、香精、柠檬酸、苯甲酸钠、山梨酸钾、苄醇、着色剂 CI 17200', E'已翻译'),
  (E'uvlajnyayshchiiy-krem-dlya-ruk-pusy-ginger-verveine-100763', E'Aqua, Rosa Damascena Flower Water, Coco-Caprylate, Glycerin, Octyldodecanol, Butyrospermum Parkii (Shea) Butter, Cetearyl Alcohol, Glyceryl Stearate, PEG-100 Stearate, Cyclopentasiloxane, Dimethicone, Phenoxyethanol, Ethylhexylglycerin, Panthenol, Sodium Polyacrylate, Carbomer, Tocopheryl Acetate, Sodium Hyaluronate, Avena Sativa Leaf/Stalk Extract, Saccharomyces Ferment Lysate Filtrate, Citric Acid, Sodium Benzoate, Potassium Sorbate, Sodium Hydroxide, Parfum, Citral, Hexyl Cinnamal, Limonene, Linalool.', E'水、突厥蔷薇花水、椰油醇-辛酸酯、甘油、辛基十二醇、乳木果油、鲸蜡硬脂醇、甘油硬脂酸酯、PEG-100 硬脂酸酯、环五聚二甲基硅氧烷、聚二甲基硅氧烷、苯氧乙醇、乙基己基甘油、泛醇、聚丙烯酸钠、卡波姆、生育酚乙酸酯、透明质酸钠、燕麦叶/茎提取物、酵母菌发酵产物溶胞产物滤液、柠檬酸、苯甲酸钠、山梨酸钾、氢氧化钠、香精、柠檬醛、己基肉桂醛、柠檬烯、芳樟醇', E'已翻译'),
  (E'pitatelnaya-krem-maska-dlya-ruk-pusy-100188', E'Aqua, Cetearyl Alcohol, Caprylic/Capric Triglyceride, Cyclopentasiloxane, Butyrospermum Parkii (Shea) Butter, Cocos Nucifera Oil, Glyceryl Stearate, PEG-100 Stearate, Octyldodecanol, Macadamia Integrifolia Seed Oil, Ethylhexylglycerin, Phenoxyethanol, Dicaprylyl Carbonate, Dimethicone, Panthenol, Citric Acid, Cocos Nucifera Water, Tocopheryl Acetate, Sodium Polyacrylate, Bisabolol, Disodium EDTA, Potassium Sorbate, Parfum', E'水、鲸蜡硬脂醇、辛酸/癸酸甘油三酯、环五聚二甲基硅氧烷、乳木果油、椰子油、甘油硬脂酸酯、PEG-100 硬脂酸酯、辛基十二醇、澳洲坚果籽油、乙基己基甘油、苯氧乙醇、碳酸二辛酯、聚二甲基硅氧烷、泛醇、柠檬酸、椰子水、生育酚乙酸酯、聚丙烯酸钠、红没药醇、乙二胺四乙酸二钠、山梨酸钾、香精', E'已翻译'),
  (E'skrab-slaiym-dlya-tela-pusy-matcha-detox-100197', E'Sucrose (Sugar), Glycerin, Aqua, Kaolin, Glycine Soja (Soybean) Oil, Phenoxyethanol, Parfum, Xanthan Gum, Tocopheryl Acetate, Camellia Sinensis (Matcha) Leaf Powder, Cannabis Sativa Seed Oil, Tocopherol, Beta-Sitosterol, Squalene, Helianthus Annuus Seed Oil, CI 75810', E'蔗糖、甘油、水、高岭土、大豆油、苯氧乙醇、香精、黄原胶、生育酚乙酸酯、茶叶粉（抹茶）、大麻籽油、生育酚（维生素 E）、β-谷甾醇、角鲨烯、向日葵籽油、着色剂 CI 75810', E'已翻译'),
  (E'skrab-slaiym-dlya-tela-pusy-tropic-enzymes-100198', E'Sucrose (Sugar), Glycerin, Aqua, Prunus Persica (Peach) Kernel Oil, Cocos Nucifera (Coconut) Oil, Phenoxyethanol, Parfum, Xanthan Gum, Tocopheryl Acetate, Passiflora Edulis Seed Oil, Tocopherol, Beta-Sitosterol, Squalene, Panthenol, Mangifera Indica (Mango) Fruit Extract, Carica Papaya (Papaya) Fruit Extract, Inulin, Papain, Sodium Benzoate, Potassium Sorbate, CI 45100, CI 18965, CI 19140.', E'蔗糖、甘油、水、桃仁油、椰子油、苯氧乙醇、香精、黄原胶、生育酚乙酸酯、西番莲籽油、生育酚（维生素 E）、β-谷甾醇、角鲨烯、泛醇、芒果果提取物、番木瓜果提取物、菊粉、木瓜蛋白酶、苯甲酸钠、山梨酸钾、着色剂 CI 45100、着色剂 CI 18965、着色剂 CI 19140', E'已翻译'),
  (E'sekretnyiy-boks-vsye-vklycheno-1-100795', NULL, E'礼盒内容按所选规格随机组合，完整成分请以收到的各单品包装标注为准。', E'礼盒说明'),
  (E'sekretnyiy-boks-otpusk-dlya-sebya-100796', NULL, E'礼盒内容按所选规格随机组合，完整成分请以收到的各单品包装标注为准。', E'礼盒说明'),
  (E'sekretnyiy-boks-otpusk-dlya-sebya-2-100794', NULL, E'礼盒内容按所选规格随机组合，完整成分请以收到的各单品包装标注为准。', E'礼盒说明'),
  (E'nabor-hodovoiy-letniiy-vaiyb-100687', NULL, E'本套装包含多件产品，完整成分请分别参见套装内各单品包装及对应商品页面。', E'套装说明'),
  (E'hodovoiy-nabor-im-100688', NULL, E'本套装包含多件产品，完整成分请分别参见套装内各单品包装及对应商品页面。', E'套装说明'),
  (E'nabor-lichiko-freshik-100684', NULL, E'本套装包含多件产品，完整成分请分别参见套装内各单品包装及对应商品页面。', E'套装说明'),
  (E'nabor-hodovoiy-bazovyiy-100685', NULL, E'本套装包含多件产品，完整成分请分别参见套装内各单品包装及对应商品页面。', E'套装说明'),
  (E'nabor-hodovoiy-dlya-tela-100686', NULL, E'本套装包含多件产品，完整成分请分别参见套装内各单品包装及对应商品页面。', E'套装说明'),
  (E'nabor-dlya-vosstanovleniya-volos-pusy-prime-your-prime-era-kit-100678', E'Шампунь: Aqua, Sodium C14–16 Olefin Sulfonate, Sodium Cocoyl Isethionate, Cocamidopropyl Betaine, Acrylates/Palmeth-25 Acrylate Copolymer, Glycerin, Coco-Glucoside, Decyl-Glucoside, Glyceryl Oleate, Phenoxyethanol, Ethylhexylglycerin, Panthenol, Guar Hydroxypropyltrimonium Chloride, Coconut Acid, Sodium Isethionate, Laminaria Digitata Extract, Hydrolyzed Hemp Seed Extract, Hydrolyzed Rice Protein, Calendula Officinalis Flower Extract, Arnica Chamissonis Flower Extract, Hydrolyzed Wheat Protein, Parfum, Citric Acid, Sodium Benzoate, Potassium Sorbate, Rosmarinus Officinalis Water, Benzyl Alcohol, Dehydroacetic Acid, Styrene/Acrylates Copolymer, Disodium EDTA, Sodium Hydroxide, Propylene Glycol, Sodium Chloride. \n\nКондиционер: Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Panthenol, Phenyl Trimethicone, Cyclopentasiloxane, Persea Gratissima (Avocado) Oil, Argania Spinosa Kernel Oil, Butyrospermum Parkii (Shea) Butter, Dimethicone, Phenoxyethanol, Ethylhexylglycerin, Glycerin, Sodium PCA, Glucose, Urea, Glutamic Acid, Lysine, Glycine, Allantoin, Gluconolactone, Calcium Gluconate, Hydrolyzed Hemp Seed Extract, Hydrolyzed Rice Protein, Hydrolyzed Wheat Protein, Parfum, Propylene Glycol, Vaccinium Myrtillus Fruit Extract, Prunus Persica Fruit Extract, Tocopheryl Acetate, Cetrimonium Chloride, Citric Acid, Sodium Benzoate, Potassium Sorbate, Isopropyl Alcohol, Lactic Acid, Disodium EDTA. \n\nМаска: Aqua, Cetearyl Alcohol, Behentrimonium Methosulfate, Glycerin, Macadamia Integrifolia Seed Oil, Crambe Abyssinica Seed Oil, Phenyl Trimethicone, Sodium PCA, Glucose, Urea, Glutamic Acid, Lysine, Glycine, Allantoin, Gluconolactone, Calcium Gluconate, Avena Sativa Leaf/Stalk Extract, Saccharomyces Ferment Lysate Filtrate, Panthenol, Hydrolyzed Keratin, Hydrolyzed Wheat Protein, Parfum, Propylene Glycol, Carica Papaya Fruit Extract, Tocopheryl Acetate, Cetrimonium Chloride, Bis(C13-15 Alkoxy) PG-Amodimethicone, C14-15 Alcohols, Isotridecyl Alcohol, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Prunus Amygdalus Dulcis Fruit Extract, Punica Granatum Fruit Extract, Sodium Benzoate, Potassium Sorbate, Benzyl Alcohol, Lactic Acid, Disodium EDTA.', E'洗发水：水、C14-16 烯烃磺酸钠、椰油酰羟乙磺酸酯钠、椰油酰胺丙基甜菜碱、丙烯酸（酯）类/棕榈醇聚醚-25 丙烯酸酯共聚物、甘油、椰油基葡糖苷、癸基葡糖苷、油酸甘油酯、苯氧乙醇、乙基己基甘油、泛醇、瓜儿胶羟丙基三甲基氯化铵、椰油酸、羟乙磺酸钠、掌状海带提取物、水解大麻籽提取物、水解大米蛋白、金盏花花提取物、夏蒙山金车花提取物、水解小麦蛋白、香精、柠檬酸、苯甲酸钠、山梨酸钾、迷迭香水、苄醇、脱氢乙酸、苯乙烯/丙烯酸（酯）类共聚物、乙二胺四乙酸二钠、氢氧化钠、丙二醇、氯化钠\n护发素：水、鲸蜡硬脂醇、山嵛基三甲基氯化铵、泛醇、苯基聚三甲基硅氧烷、环五聚二甲基硅氧烷、鳄梨油、摩洛哥坚果仁油、乳木果油、聚二甲基硅氧烷、苯氧乙醇、乙基己基甘油、甘油、PCA 钠、葡萄糖、尿素、谷氨酸、赖氨酸、甘氨酸、尿囊素、葡糖酸内酯、葡糖酸钙、水解大麻籽提取物、水解大米蛋白、水解小麦蛋白、香精、丙二醇、越橘果提取物、桃果提取物、生育酚乙酸酯、西曲氯铵、柠檬酸、苯甲酸钠、山梨酸钾、异丙醇、乳酸、乙二胺四乙酸二钠\n发膜：水、鲸蜡硬脂醇、山嵛基三甲基铵甲基硫酸盐、甘油、澳洲坚果籽油、深海两节荠籽油、苯基聚三甲基硅氧烷、PCA 钠、葡萄糖、尿素、谷氨酸、赖氨酸、甘氨酸、尿囊素、葡糖酸内酯、葡糖酸钙、燕麦叶/茎提取物、酵母菌发酵产物溶胞产物滤液、泛醇、水解角蛋白、水解小麦蛋白、香精、丙二醇、番木瓜果提取物、生育酚乙酸酯、西曲氯铵、双(C13-15 烷氧基) PG 氨端聚二甲基硅氧烷、C14-15 醇、异十三醇、苯氧乙醇、乙基己基甘油、柠檬酸、甜扁桃果提取物、石榴果提取物、苯甲酸钠、山梨酸钾、苄醇、乳酸、乙二胺四乙酸二钠', E'已翻译'),
  (E'maska-dlya-volos-pusy-base-hair-500-g-100177', E'Aqua, Cetearyl Alcohol, Behenamidopropyl Dimethylamine, Caprylic/Capric Triglyceride, Cocos Nucifera Oil, Macadamia Integrifolia Seed Oil, Panthenol, Hydrolyzed Keratin, Tocopheryl Acetate, Cetrimonium Chloride, Silicone Quaternium-18, Trideceth-6, Trideceth-12, Phenoxyethanol, Ethylhexylglycerin, Propylene Glycol, Actinidia Chinensis Extract, Potassium Sorbate, Sodium Benzoate, Benzyl Alcohol, Lactic Acid, Parfum, Disodium EDTA.', E'水、鲸蜡硬脂醇、山嵛酰胺丙基二甲胺、辛酸/癸酸甘油三酯、椰子油、澳洲坚果籽油、泛醇、水解角蛋白、生育酚乙酸酯、西曲氯铵、聚硅氧烷季铵盐-18、十三烷醇聚醚-6、十三烷醇聚醚-12、苯氧乙醇、乙基己基甘油、丙二醇、中华猕猴桃提取物、山梨酸钾、苯甲酸钠、苄醇、乳酸、香精、乙二胺四乙酸二钠', E'已翻译'),
  (E'nesmyvaemyiy-krem-spreiy-dlya-volos-pusy-base-hair-200-ml-100223', E'Aqua, Cetearyl Alcohol, Behenamidopropyl Dimethylamine, PPG-3 Caprylyl Ether, Isopropyl Myristate, Myristyl Alcohol, Biosaccharide Gum-1, Tocopheryl Acetate, Sodium PCA, Glucose, Urea, Glutamic Acid, Lysine, Glycine, Allantoin, Glycerin, Gluconolactone, Calcium Gluconate, Panthenol, Silicone Quaternium-16, Undeceth-11, Butyloctanol, Undeceth-5, Hydrolyzed Keratin, Hydrolyzed Wheat Protein, Parfum, Propylene Glycol, Bis(C13-15 Alkoxy) PG-Amodimethicone, C14-15 Alcohols, Isotridecyl Alcohol, Phenoxyethanol, Ethylhexylglycerin, Prunus Amygdalus Dulcis Fruit Extract, Mangifera Indica Fruit Extract, Malva Verticillata Flower/Leaf/Stem Extract, Sodium Benzoate, Potassium Sorbate, Benzyl Alcohol, Lactic Acid, Disodium EDTA.', E'水、鲸蜡硬脂醇、山嵛酰胺丙基二甲胺、PPG-3 辛基醚、肉豆蔻酸异丙酯、肉豆蔻醇、生物糖胶-1、生育酚乙酸酯、PCA 钠、葡萄糖、尿素、谷氨酸、赖氨酸、甘氨酸、尿囊素、甘油、葡糖酸内酯、葡糖酸钙、泛醇、聚硅氧烷季铵盐-16、十一烷醇聚醚-11、丁基辛醇、十一烷醇聚醚-5、水解角蛋白、水解小麦蛋白、香精、丙二醇、双(C13-15 烷氧基) PG 氨端聚二甲基硅氧烷、C14-15 醇、异十三醇、苯氧乙醇、乙基己基甘油、甜扁桃果提取物、芒果果提取物、冬葵花/叶/茎提取物、苯甲酸钠、山梨酸钾、苄醇、乳酸、乙二胺四乙酸二钠', E'已翻译'),
  (E'shampun-dlya-volos-pusy-base-hair-750-ml-3-100595', NULL, E'原品牌页面暂未公开完整成分表，请以中国销售实物包装的成分标注为准。', E'待品牌确认'),
  (E'maska-dlya-volos-pusy-prime-hair-250-ml-100178', E'Aqua, Cetearyl Alcohol, Behentrimonium Methosulfate, Glycerin, Macadamia Integrifolia Seed Oil, Crambe Abyssinica Seed Oil, Phenyl Trimethicone, Sodium PCA, Glucose, Urea, Glutamic Acid, Lysine, Glycine, Allantoin, Gluconolactone, Calcium Gluconate, Avena Sativa Leaf/Stalk Extract, Saccharomyces Ferment Lysate Filtrate, Panthenol, Hydrolyzed Keratin, Hydrolyzed Wheat Protein, Parfum, Propylene Glycol, Carica Papaya Fruit Extract, Tocopheryl Acetate, Cetrimonium Chloride, Bis(C13-15 Alkoxy) PG-Amodimethicone, C14-15 Alcohols, Isotridecyl Alcohol, Phenoxyethanol, Ethylhexylglycerin, Citric Acid, Prunus Amygdalus Dulcis Fruit Extract, Punica Granatum Fruit Extract, Sodium Benzoate, Potassium Sorbate, Benzyl Alcohol, Lactic Acid, Disodium EDTA.', E'水、鲸蜡硬脂醇、山嵛基三甲基铵甲基硫酸盐、甘油、澳洲坚果籽油、深海两节荠籽油、苯基聚三甲基硅氧烷、PCA 钠、葡萄糖、尿素、谷氨酸、赖氨酸、甘氨酸、尿囊素、葡糖酸内酯、葡糖酸钙、燕麦叶/茎提取物、酵母菌发酵产物溶胞产物滤液、泛醇、水解角蛋白、水解小麦蛋白、香精、丙二醇、番木瓜果提取物、生育酚乙酸酯、西曲氯铵、双(C13-15 烷氧基) PG 氨端聚二甲基硅氧烷、C14-15 醇、异十三醇、苯氧乙醇、乙基己基甘油、柠檬酸、甜扁桃果提取物、石榴果提取物、苯甲酸钠、山梨酸钾、苄醇、乳酸、乙二胺四乙酸二钠', E'已翻译'),
  (E'kondicioner-dlya-volos-pusy-prime-hair-400-ml-100173', E'Aqua, Cetearyl Alcohol, Behentrimonium Chloride, Panthenol, Phenyl Trimethicone, Cyclopentasiloxane, Persea Gratissima (Avocado) Oil, Argania Spinosa Kernel Oil, Butyrospermum Parkii (Shea) Butter, Dimethicone, Phenoxyethanol, Ethylhexylglycerin, Glycerin, Sodium PCA, Glucose, Urea, Glutamic Acid, Lysine, Glycine, Allantoin, Gluconolactone, Calcium Gluconate, Hydrolyzed Hemp Seed Extract, Hydrolyzed Rice Protein, Hydrolyzed Wheat Protein, Parfum, Propylene Glycol, Vaccinium Myrtillus Fruit Extract, Prunus Persica Fruit Extract, Tocopheryl Acetate, Cetrimonium Chloride, Citric Acid, Sodium Benzoate, Potassium Sorbate, Isopropyl Alcohol, Lactic Acid, Disodium EDTA.', E'水、鲸蜡硬脂醇、山嵛基三甲基氯化铵、泛醇、苯基聚三甲基硅氧烷、环五聚二甲基硅氧烷、鳄梨油、摩洛哥坚果仁油、乳木果油、聚二甲基硅氧烷、苯氧乙醇、乙基己基甘油、甘油、PCA 钠、葡萄糖、尿素、谷氨酸、赖氨酸、甘氨酸、尿囊素、葡糖酸内酯、葡糖酸钙、水解大麻籽提取物、水解大米蛋白、水解小麦蛋白、香精、丙二醇、越橘果提取物、桃果提取物、生育酚乙酸酯、西曲氯铵、柠檬酸、苯甲酸钠、山梨酸钾、异丙醇、乳酸、乙二胺四乙酸二钠', E'已翻译'),
  (E'shampun-dlya-volos-pusy-prime-hair-400-ml-100203', E'Aqua, Sodium C14–16 Olefin Sulfonate, Sodium Cocoyl Isethionate, Cocamidopropyl Betaine, Acrylates/Palmeth-25 Acrylate Copolymer, Glycerin, Coco-Glucoside, Decyl-Glucoside, Glyceryl Oleate, Phenoxyethanol, Ethylhexylglycerin, Panthenol, Guar Hydroxypropyltrimonium Chloride, Coconut Acid, Sodium Isethionate, Laminaria Digitata Extract, Hydrolyzed Hemp Seed Extract, Hydrolyzed Rice Protein, Calendula Officinalis Flower Extract, Arnica Chamissonis Flower Extract, Hydrolyzed Wheat Protein, Parfum, Citric Acid, Sodium Benzoate, Potassium Sorbate, Rosmarinus Officinalis Water, Benzyl Alcohol, Dehydroacetic Acid, Styrene/Acrylates Copolymer, Disodium EDTA, Sodium Hydroxide, Propylene Glycol, Sodium Chloride.', E'水、C14-16 烯烃磺酸钠、椰油酰羟乙磺酸酯钠、椰油酰胺丙基甜菜碱、丙烯酸（酯）类/棕榈醇聚醚-25 丙烯酸酯共聚物、甘油、椰油基葡糖苷、癸基葡糖苷、油酸甘油酯、苯氧乙醇、乙基己基甘油、泛醇、瓜儿胶羟丙基三甲基氯化铵、椰油酸、羟乙磺酸钠、掌状海带提取物、水解大麻籽提取物、水解大米蛋白、金盏花花提取物、夏蒙山金车花提取物、水解小麦蛋白、香精、柠檬酸、苯甲酸钠、山梨酸钾、迷迭香水、苄醇、脱氢乙酸、苯乙烯/丙烯酸（酯）类共聚物、乙二胺四乙酸二钠、氢氧化钠、丙二醇、氯化钠', E'已翻译');

INSERT INTO product_ingredient_translation_backups (batch_id, product_id, slug, ingredients, old_updated_at)
SELECT 'ingredients-zh-cn-v2', p.id, p.slug, p.ingredients, p.updated_at::TEXT
FROM products p
JOIN product_ingredient_translation_payload_20260829 t ON t.slug = p.slug
ON CONFLICT (batch_id, product_id) DO NOTHING;

UPDATE products p
SET ingredients = t.ingredients_zh,
    updated_at = CURRENT_TIMESTAMP
FROM product_ingredient_translation_payload_20260829 t
WHERE p.slug = t.slug
  AND p.ingredients IS DISTINCT FROM t.ingredients_zh;

DO $$
DECLARE
  mismatch_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO mismatch_count
  FROM product_ingredient_translation_payload_20260829 t
  JOIN products p ON p.slug = t.slug
  WHERE p.ingredients IS DISTINCT FROM t.ingredients_zh;
  IF mismatch_count <> 0 THEN
    RAISE EXCEPTION 'Chinese ingredient verification failed for % products', mismatch_count;
  END IF;
END $$;
