BEGIN;

ALTER TABLE community_topics ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 0;
ALTER TABLE community_topics ADD COLUMN IF NOT EXISTS featured INTEGER NOT NULL DEFAULT 0 CHECK (featured IN (0, 1));

ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS comment_status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS restricted_until TEXT;
ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS restriction_note TEXT NOT NULL DEFAULT '';
ALTER TABLE community_profiles DROP CONSTRAINT IF EXISTS community_profiles_comment_status_check;
ALTER TABLE community_profiles ADD CONSTRAINT community_profiles_comment_status_check
  CHECK (comment_status IN ('active', 'restricted'));

CREATE TABLE IF NOT EXISTS community_topic_follows (
  topic_id TEXT NOT NULL REFERENCES community_topics(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (topic_id, member_id)
);

CREATE INDEX IF NOT EXISTS community_topic_follows_member_idx
  ON community_topic_follows (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_comment_likes (
  comment_id TEXT NOT NULL REFERENCES community_comments(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (comment_id, member_id)
);

CREATE INDEX IF NOT EXISTS community_comment_likes_member_idx
  ON community_comment_likes (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_activity_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL CHECK (event_type IN ('visit', 'post_created', 'like', 'comment', 'comment_like', 'follow', 'topic_follow', 'mention')),
  entity_type TEXT NOT NULL DEFAULT '',
  entity_id TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_activity_member_idx
  ON community_activity_events (member_id, created_at DESC);
CREATE INDEX IF NOT EXISTS community_activity_daily_idx
  ON community_activity_events (created_at DESC, event_type);

CREATE TABLE IF NOT EXISTS community_notification_preferences (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  reactions_enabled INTEGER NOT NULL DEFAULT 1 CHECK (reactions_enabled IN (0, 1)),
  social_enabled INTEGER NOT NULL DEFAULT 1 CHECK (social_enabled IN (0, 1)),
  campaigns_enabled INTEGER NOT NULL DEFAULT 1 CHECK (campaigns_enabled IN (0, 1)),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS community_broadcasts (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  target TEXT NOT NULL CHECK (target IN ('all', 'active', 'creators')),
  recipient_count INTEGER NOT NULL DEFAULT 0,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_broadcasts_created_idx
  ON community_broadcasts (created_at DESC);

COMMIT;
