CREATE TABLE IF NOT EXISTS member_wechat_identities (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  app_id TEXT NOT NULL,
  openid TEXT NOT NULL,
  unionid TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  last_login_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE(app_id, openid)
);

CREATE INDEX IF NOT EXISTS member_wechat_identity_member_idx ON member_wechat_identities (member_id);
CREATE INDEX IF NOT EXISTS member_wechat_identity_union_idx ON member_wechat_identities (unionid) WHERE unionid != '';
