BEGIN;

ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER NOT NULL DEFAULT 10;

ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_requested_at TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS inventory_restocked INTEGER NOT NULL DEFAULT 0;

INSERT INTO payment_providers (provider, display_name, enabled, mode) VALUES
  ('wechat', '微信支付', 0, 'production'),
  ('alipay', '支付宝', 0, 'production')
ON CONFLICT (provider) DO NOTHING;

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_slug TEXT NOT NULL,
  order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  movement_type TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  stock_after INTEGER NOT NULL,
  reference_id TEXT NOT NULL,
  actor TEXT NOT NULL DEFAULT 'system',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (product_slug, movement_type, reference_id)
);

CREATE INDEX IF NOT EXISTS inventory_movements_order_idx ON inventory_movements (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS inventory_movements_product_idx ON inventory_movements (product_slug, created_at DESC);

CREATE TABLE IF NOT EXISTS shipments (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
  carrier_code TEXT NOT NULL,
  carrier_name TEXT NOT NULL,
  tracking_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '已发货',
  tracking_url TEXT NOT NULL DEFAULT '',
  shipped_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  delivered_at TEXT,
  last_synced_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS shipment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
  event_time TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  status TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'admin',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS shipments_tracking_idx ON shipments (tracking_number);
CREATE INDEX IF NOT EXISTS shipment_events_shipment_idx ON shipment_events (shipment_id, event_time DESC);

ALTER TABLE returns ADD COLUMN IF NOT EXISTS request_type TEXT NOT NULL DEFAULT 'refund';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS items_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS requested_amount_fen INTEGER;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS resolution TEXT NOT NULL DEFAULT '';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS refund_id TEXT REFERENCES refunds(id) ON DELETE SET NULL;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS return_carrier TEXT NOT NULL DEFAULT '';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS return_tracking_number TEXT NOT NULL DEFAULT '';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS completed_at TEXT;

INSERT INTO notification_templates (key, name, email_subject, email_body, sms_body, enabled) VALUES
  ('order_confirmed', '支付成功通知', '订单 {{orderId}} 支付成功', '你好 {{customer}}，订单 {{orderId}} 已支付成功，实付 {{amount}}。我们正在为你准备商品。', 'PUSY.CN：订单 {{orderId}} 已支付成功。', 1),
  ('order_shipped', '发货通知', '订单 {{orderId}} 已发货', '你好 {{customer}}，订单 {{orderId}} 已通过 {{carrier}} 发出，物流单号 {{trackingNumber}}。查询物流：{{trackingUrl}}', 'PUSY.CN：订单 {{orderId}} 已发货，{{carrier}} {{trackingNumber}}。', 1),
  ('refund_completed', '退款完成通知', '订单 {{orderId}} 退款已完成', '你好 {{customer}}，订单 {{orderId}} 的 {{refundStatus}} 已完成，退款金额 {{refundAmount}}。到账时间以支付渠道为准。', 'PUSY.CN：订单 {{orderId}} 退款 {{refundAmount}} 已完成。', 1),
  ('order_cancelled', '订单取消通知', '订单 {{orderId}} 已取消', '你好 {{customer}}，订单 {{orderId}} 已取消。原因：{{reason}}。如已支付，退款将按原支付渠道退回。', 'PUSY.CN：订单 {{orderId}} 已取消。', 1),
  ('return_updated', '售后进度通知', '售后单 {{returnId}} 状态更新', '你好 {{customer}}，订单 {{orderId}} 的售后单 {{returnId}} 已更新为“{{status}}”。{{note}}', 'PUSY.CN：售后单 {{returnId}} 已更新为 {{status}}。', 1),
  ('low_stock_alert', '低库存提醒', '库存预警：{{productName}}', '商品 {{productName}}（{{productSlug}}）当前库存 {{stock}} 件，已达到预警阈值 {{threshold}} 件，请及时补货。', '', 1)
ON CONFLICT (key) DO NOTHING;

COMMIT;
