BEGIN;

CREATE TABLE IF NOT EXISTS product_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  parent_id INTEGER REFERENCES product_categories(id) ON DELETE SET NULL,
  description TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS product_categories_parent_sort_idx
  ON product_categories (parent_id, sort_order, id);

INSERT INTO product_categories (name, slug, sort_order) VALUES
  ('彩妆', 'makiyazh', 10),
  ('眉妆', 'brows', 20),
  ('护肤', 'uhod', 30),
  ('面部护理', 'face', 40),
  ('身体护理', 'uhod-1', 50),
  ('头发护理', 'hair', 60),
  ('套装', 'nabory', 70),
  ('神秘礼盒', 'sekretnye-boksy', 80),
  ('家居', 'dlya-doma', 90),
  ('配件', 'accessories', 100),
  ('礼品卡', 'gift-card', 110)
ON CONFLICT (name) DO NOTHING;

INSERT INTO product_categories (name, slug, sort_order)
SELECT DISTINCT p.category, 'legacy-' || SUBSTRING(MD5(p.category) FROM 1 FOR 12), 900
FROM products p
WHERE NOT EXISTS (SELECT 1 FROM product_categories c WHERE c.name = p.category)
ON CONFLICT DO NOTHING;

ALTER TABLE products
  ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES product_categories(id) ON DELETE RESTRICT;

UPDATE products p
SET category_id = c.id
FROM product_categories c
WHERE p.category_id IS NULL AND c.name = p.category;

CREATE INDEX IF NOT EXISTS products_category_id_idx ON products (category_id, status, id);

COMMIT;
