ALTER TABLE members ADD COLUMN IF NOT EXISTS points_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS lifetime_points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'bronze';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_awarded INTEGER NOT NULL DEFAULT 0;
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS assignment_mode TEXT NOT NULL DEFAULT 'public';

CREATE TABLE IF NOT EXISTS member_points_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  points INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  reason TEXT NOT NULL,
  reference_type TEXT NOT NULL DEFAULT '',
  reference_id TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, reference_type, reference_id)
);

CREATE INDEX IF NOT EXISTS member_points_ledger_member_idx ON member_points_ledger (member_id, created_at DESC);

UPDATE orders o
SET points_awarded = FLOOR(GREATEST(o.total - COALESCE((
  SELECT ROUND(SUM(r.amount_fen) / 12.0)::INTEGER FROM refunds r WHERE r.order_id = o.id AND r.status = 'succeeded'
), 0), 0) * 0.12)::INTEGER
WHERE o.member_id IS NOT NULL AND o.status NOT IN ('待付款','支付失败','已取消');

WITH totals AS (
  SELECT member_id, COALESCE(SUM(points_awarded), 0)::INTEGER AS points
  FROM orders WHERE member_id IS NOT NULL GROUP BY member_id
)
UPDATE members m SET
  points_balance = totals.points,
  lifetime_points = totals.points,
  tier = CASE WHEN totals.points >= 5000 THEN 'diamond' WHEN totals.points >= 2000 THEN 'gold' WHEN totals.points >= 500 THEN 'silver' ELSE 'bronze' END,
  updated_at = CURRENT_TIMESTAMP
FROM totals WHERE m.id = totals.member_id;

INSERT INTO member_points_ledger (member_id, points, balance_after, reason, reference_type, reference_id)
SELECT id, points_balance, points_balance, '历史消费积分初始化', 'migration', 'growth-engine-v1'
FROM members WHERE points_balance > 0
ON CONFLICT (member_id, reference_type, reference_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS coupon_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id INTEGER NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'available',
  assigned_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  used_at TEXT,
  order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  UNIQUE (coupon_id, member_id)
);

CREATE INDEX IF NOT EXISTS coupon_assignments_member_idx ON coupon_assignments (member_id, status, assigned_at DESC);

CREATE TABLE IF NOT EXISTS customer_tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#ef398b',
  description TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_tag_assignments (
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES customer_tags(id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (member_id, tag_id)
);

CREATE TABLE IF NOT EXISTS customer_segments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  filter_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_product_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  product_slug TEXT NOT NULL,
  alert_type TEXT NOT NULL,
  target_price INTEGER,
  last_notified_at TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, product_slug, alert_type)
);

CREATE INDEX IF NOT EXISTS member_product_alerts_product_idx ON member_product_alerts (product_slug, alert_type, status);

CREATE TABLE IF NOT EXISTS product_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_slug TEXT NOT NULL,
  old_price INTEGER NOT NULL,
  new_price INTEGER NOT NULL,
  changed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS growth_automation_runs (
  id TEXT PRIMARY KEY,
  automation_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',
  matched_count INTEGER NOT NULL DEFAULT 0,
  queued_count INTEGER NOT NULL DEFAULT 0,
  error_text TEXT NOT NULL DEFAULT '',
  started_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  finished_at TEXT
);

CREATE INDEX IF NOT EXISTS growth_automation_runs_key_idx ON growth_automation_runs (automation_key, started_at DESC);

INSERT INTO notification_templates (key, name, email_subject, email_body, sms_body, enabled) VALUES
  ('payment_reminder', '未付款订单提醒', '你的 PUSY.CN 订单 {{orderId}} 即将释放', '你好 {{customer}}，订单 {{orderId}} 尚未支付，金额为 {{amount}} 元。库存将在 {{expiresAt}} 后释放，如需购买请尽快完成支付。', 'PUSY.CN：订单 {{orderId}} 尚未支付，请在 {{expiresAt}} 前完成支付。', 1),
  ('repurchase_reminder', '复购提醒', '{{productName}} 可能快用完了', '你好 {{customer}}，距你购买 {{productName}} 已有一段时间。现在回购，可继续享受熟悉的使用体验：{{productUrl}}', 'PUSY.CN：你购买的 {{productName}} 可能快用完了，欢迎回购。', 1),
  ('new_product', '新品通知', 'PUSY.CN 新品：{{productName}}', '你好 {{customer}}，新品 {{productName}} 已上架。查看详情：{{productUrl}}', 'PUSY.CN 新品 {{productName}} 已上架。', 1),
  ('product_restock', '补货通知', '{{productName}} 已补货', '你好 {{customer}}，你关注的 {{productName}} 已经补货，现在可以购买：{{productUrl}}', 'PUSY.CN：你关注的 {{productName}} 已补货。', 1),
  ('price_drop', '降价通知', '{{productName}} 已降价', '你好 {{customer}}，你关注的 {{productName}} 已从 {{oldPrice}} 元降至 {{newPrice}} 元：{{productUrl}}', 'PUSY.CN：{{productName}} 已降至 {{newPrice}} 元。', 1),
  ('targeted_coupon', '专属优惠券', '你的 PUSY.CN 专属优惠券：{{couponCode}}', '你好 {{customer}}，我们为你准备了专属优惠券 {{couponCode}}。优惠内容：{{benefit}}，使用条件：{{condition}}。有效期至 {{endsAt}}。', 'PUSY.CN：专属优惠券 {{couponCode}} 已到账，有效期至 {{endsAt}}。', 1)
ON CONFLICT (key) DO NOTHING;
