BEGIN;

CREATE TABLE IF NOT EXISTS member_credentials (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  login_password_hash TEXT NOT NULL,
  login_password_salt TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_wallets (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  available_balance_fen BIGINT NOT NULL DEFAULT 0 CHECK (available_balance_fen >= 0),
  frozen_balance_fen BIGINT NOT NULL DEFAULT 0 CHECK (frozen_balance_fen >= 0),
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'frozen')),
  payment_password_hash TEXT,
  payment_password_salt TEXT,
  password_failed_attempts INTEGER NOT NULL DEFAULT 0,
  password_locked_until TEXT,
  password_updated_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

INSERT INTO member_wallets (member_id)
SELECT id FROM members
ON CONFLICT (member_id) DO NOTHING;

ALTER TABLE payments ADD COLUMN IF NOT EXISTS wallet_amount_fen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS external_amount_fen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE payments ADD COLUMN IF NOT EXISTS wallet_status TEXT NOT NULL DEFAULT 'none';

UPDATE payments
SET external_amount_fen = amount_fen
WHERE wallet_amount_fen = 0 AND external_amount_fen = 0;

ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_wallet_amount_check;
ALTER TABLE payments ADD CONSTRAINT payments_wallet_amount_check
  CHECK (wallet_amount_fen >= 0 AND external_amount_fen >= 0 AND amount_fen = wallet_amount_fen + external_amount_fen);
ALTER TABLE payments DROP CONSTRAINT IF EXISTS payments_wallet_status_check;
ALTER TABLE payments ADD CONSTRAINT payments_wallet_status_check
  CHECK (wallet_status IN ('none', 'held', 'captured', 'released', 'refunded'));

ALTER TABLE refunds ADD COLUMN IF NOT EXISTS wallet_amount_fen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS external_amount_fen INTEGER NOT NULL DEFAULT 0;
ALTER TABLE refunds ADD COLUMN IF NOT EXISTS wallet_credited INTEGER NOT NULL DEFAULT 0;

UPDATE refunds
SET external_amount_fen = amount_fen
WHERE wallet_amount_fen = 0 AND external_amount_fen = 0;

ALTER TABLE refunds DROP CONSTRAINT IF EXISTS refunds_payment_split_check;
ALTER TABLE refunds ADD CONSTRAINT refunds_payment_split_check
  CHECK (wallet_amount_fen >= 0 AND external_amount_fen >= 0 AND amount_fen = wallet_amount_fen + external_amount_fen);

CREATE TABLE IF NOT EXISTS member_wallet_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  payment_id TEXT REFERENCES payments(id) ON DELETE SET NULL,
  order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  entry_type TEXT NOT NULL CHECK (entry_type IN ('hold', 'capture', 'release', 'refund', 'adjustment')),
  amount_fen BIGINT NOT NULL,
  available_balance_after_fen BIGINT NOT NULL CHECK (available_balance_after_fen >= 0),
  frozen_balance_after_fen BIGINT NOT NULL CHECK (frozen_balance_after_fen >= 0),
  reference_id TEXT NOT NULL,
  idempotency_key TEXT NOT NULL UNIQUE,
  note TEXT NOT NULL DEFAULT '',
  actor TEXT NOT NULL DEFAULT 'system',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS member_wallet_ledger_member_idx
  ON member_wallet_ledger (member_id, created_at DESC, id DESC);
CREATE INDEX IF NOT EXISTS member_wallet_ledger_order_idx
  ON member_wallet_ledger (order_id, created_at DESC);

COMMIT;
