BEGIN;

ALTER TABLE community_posts DROP CONSTRAINT IF EXISTS community_posts_status_check;
ALTER TABLE community_posts ADD CONSTRAINT community_posts_status_check
  CHECK (status IN ('draft', 'pending', 'approved', 'rejected', 'hidden'));
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS content_fingerprint TEXT NOT NULL DEFAULT '';
ALTER TABLE community_posts ADD COLUMN IF NOT EXISTS campaign_id TEXT;

ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS account_type TEXT NOT NULL DEFAULT 'member';
ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS official_label TEXT NOT NULL DEFAULT '';
ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS creator_status TEXT NOT NULL DEFAULT 'active';
ALTER TABLE community_profiles ADD COLUMN IF NOT EXISTS reward_blocked_at TEXT;
ALTER TABLE community_profiles DROP CONSTRAINT IF EXISTS community_profiles_account_type_check;
ALTER TABLE community_profiles ADD CONSTRAINT community_profiles_account_type_check CHECK (account_type IN ('member', 'official'));
ALTER TABLE community_profiles DROP CONSTRAINT IF EXISTS community_profiles_creator_status_check;
ALTER TABLE community_profiles ADD CONSTRAINT community_profiles_creator_status_check CHECK (creator_status IN ('active', 'restricted'));

CREATE TABLE IF NOT EXISTS community_campaigns (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  title TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  rules TEXT NOT NULL DEFAULT '',
  topic_id TEXT REFERENCES community_topics(id) ON DELETE SET NULL,
  product_slug TEXT REFERENCES products(slug) ON DELETE SET NULL,
  reward_points INTEGER NOT NULL DEFAULT 0 CHECK (reward_points >= 0 AND reward_points <= 500),
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'ended')),
  starts_at TEXT,
  ends_at TEXT,
  created_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE community_posts DROP CONSTRAINT IF EXISTS community_posts_campaign_id_fkey;
ALTER TABLE community_posts ADD CONSTRAINT community_posts_campaign_id_fkey
  FOREIGN KEY (campaign_id) REFERENCES community_campaigns(id) ON DELETE SET NULL;

CREATE TABLE IF NOT EXISTS community_post_versions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  version INTEGER NOT NULL CHECK (version > 0),
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL,
  topic_slugs_json TEXT NOT NULL DEFAULT '[]',
  product_slugs_json TEXT NOT NULL DEFAULT '[]',
  media_ids_json TEXT NOT NULL DEFAULT '[]',
  change_type TEXT NOT NULL CHECK (change_type IN ('created', 'draft_saved', 'submitted', 'edited', 'hidden', 'restored')),
  actor_type TEXT NOT NULL CHECK (actor_type IN ('member', 'admin')),
  actor_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (post_id, version)
);

CREATE INDEX IF NOT EXISTS community_post_versions_post_idx
  ON community_post_versions (post_id, version DESC);

CREATE TABLE IF NOT EXISTS community_campaign_entries (
  campaign_id TEXT NOT NULL REFERENCES community_campaigns(id) ON DELETE CASCADE,
  post_id TEXT NOT NULL UNIQUE REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'qualified', 'rejected')),
  reward_points INTEGER NOT NULL DEFAULT 0,
  review_note TEXT NOT NULL DEFAULT '',
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (campaign_id, post_id)
);

CREATE TABLE IF NOT EXISTS community_reward_grants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  reward_key TEXT NOT NULL,
  points INTEGER NOT NULL CHECK (points > 0),
  status TEXT NOT NULL DEFAULT 'granted' CHECK (status IN ('granted', 'reversed')),
  reference_id TEXT NOT NULL,
  granted_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  reversed_at TEXT,
  UNIQUE (member_id, reward_key, post_id)
);

CREATE TABLE IF NOT EXISTS community_creator_violations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  post_id TEXT REFERENCES community_posts(id) ON DELETE SET NULL,
  kind TEXT NOT NULL CHECK (kind IN ('duplicate', 'engagement_abuse', 'content_violation', 'reward_reversal')),
  note TEXT NOT NULL,
  admin_id TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_campaigns_status_idx ON community_campaigns (status, starts_at, ends_at);
CREATE INDEX IF NOT EXISTS community_campaign_entries_status_idx ON community_campaign_entries (status, created_at DESC);
CREATE INDEX IF NOT EXISTS community_posts_fingerprint_idx ON community_posts (member_id, content_fingerprint, created_at DESC) WHERE content_fingerprint <> '';

COMMIT;
