BEGIN;

CREATE TABLE IF NOT EXISTS community_post_likes (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, member_id)
);

CREATE INDEX IF NOT EXISTS community_post_likes_member_idx
  ON community_post_likes (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_bookmarks (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, member_id)
);

CREATE INDEX IF NOT EXISTS community_post_bookmarks_member_idx
  ON community_post_bookmarks (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_comments (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  parent_comment_id TEXT REFERENCES community_comments(id) ON DELETE SET NULL,
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 2 AND 500),
  status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden', 'deleted')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_comments_post_idx
  ON community_comments (post_id, status, created_at ASC);
CREATE INDEX IF NOT EXISTS community_comments_parent_idx
  ON community_comments (parent_comment_id, created_at ASC)
  WHERE parent_comment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS community_reports (
  id TEXT PRIMARY KEY,
  reporter_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('post', 'comment')),
  entity_id TEXT NOT NULL,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  comment_id TEXT REFERENCES community_comments(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('spam', 'abuse', 'misinformation', 'commercial', 'other')),
  detail TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
  resolution_note TEXT NOT NULL DEFAULT '',
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (reporter_member_id, entity_type, entity_id),
  CHECK ((entity_type = 'post' AND comment_id IS NULL) OR (entity_type = 'comment' AND comment_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS community_reports_queue_idx
  ON community_reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS community_reports_post_idx
  ON community_reports (post_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_report_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id TEXT NOT NULL REFERENCES community_reports(id) ON DELETE CASCADE,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('resolve', 'dismiss')),
  note TEXT NOT NULL DEFAULT '',
  admin_id TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_report_events_report_idx
  ON community_report_events (report_id, created_at DESC);

COMMIT;
