BEGIN;

CREATE TABLE IF NOT EXISTS member_social_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('wechat', 'alipay')),
  provider_user_id TEXT NOT NULL,
  provider_union_id TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, provider),
  UNIQUE (provider, provider_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS member_social_accounts_union_idx
  ON member_social_accounts (provider, provider_union_id)
  WHERE provider_union_id != '';

CREATE TABLE IF NOT EXISTS member_oauth_states (
  state_hash TEXT PRIMARY KEY,
  member_id INTEGER REFERENCES members(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('wechat', 'alipay')),
  mode TEXT NOT NULL CHECK (mode IN ('bind', 'login')),
  return_to TEXT NOT NULL DEFAULT '/account',
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS member_oauth_states_expiry_idx ON member_oauth_states (expires_at);

COMMIT;
