BEGIN;

CREATE TABLE IF NOT EXISTS community_post_products (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  product_slug TEXT NOT NULL REFERENCES products(slug) ON DELETE RESTRICT,
  position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0 AND position < 3),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, product_slug),
  UNIQUE (post_id, position)
);

CREATE INDEX IF NOT EXISTS community_post_products_product_idx
  ON community_post_products (product_slug, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_promotions (
  post_id TEXT PRIMARY KEY REFERENCES community_posts(id) ON DELETE CASCADE,
  placement TEXT NOT NULL CHECK (placement IN ('featured', 'pinned')),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0 AND sort_order <= 999),
  note TEXT NOT NULL DEFAULT '',
  promoted_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_post_promotions_feed_idx
  ON community_post_promotions (placement, sort_order DESC, updated_at DESC);

CREATE TABLE IF NOT EXISTS community_content_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL CHECK (event_type IN ('post_impression', 'product_click', 'add_to_cart')),
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  product_slug TEXT REFERENCES products(slug) ON DELETE SET NULL,
  member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  CHECK ((event_type = 'post_impression' AND product_slug IS NULL) OR (event_type IN ('product_click', 'add_to_cart') AND product_slug IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS community_content_events_post_idx
  ON community_content_events (post_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS community_content_events_product_idx
  ON community_content_events (product_slug, event_type, created_at DESC)
  WHERE product_slug IS NOT NULL;

COMMIT;
