BEGIN;

CREATE TABLE IF NOT EXISTS community_profiles (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  public_id TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  bio TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS community_posts (
  id TEXT PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  client_request_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'hidden')),
  moderation_note TEXT NOT NULL DEFAULT '',
  moderated_by TEXT,
  moderated_at TEXT,
  published_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE UNIQUE INDEX IF NOT EXISTS community_posts_member_request_idx
  ON community_posts (member_id, client_request_id);

CREATE INDEX IF NOT EXISTS community_posts_feed_idx
  ON community_posts (status, published_at DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS community_posts_member_idx
  ON community_posts (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_media (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0 AND position < 4),
  mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  byte_size INTEGER NOT NULL CHECK (byte_size > 0 AND byte_size <= 450000),
  bytes BYTEA NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (post_id, position)
);

CREATE INDEX IF NOT EXISTS community_post_media_post_idx
  ON community_post_media (post_id, position);

CREATE TABLE IF NOT EXISTS community_moderation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  admin_id TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_moderation_events_post_idx
  ON community_moderation_events (post_id, created_at DESC);

-- Phase 2 reservation: the tables and stable keys are created now, but product
-- behavior remains disabled until follows, topics and notifications are enabled.
CREATE TABLE IF NOT EXISTS community_follows (
  follower_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  followed_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (follower_member_id, followed_member_id),
  CHECK (follower_member_id <> followed_member_id)
);

CREATE INDEX IF NOT EXISTS community_follows_followed_idx
  ON community_follows (followed_member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_topics (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'archived')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS community_post_topics (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  topic_id TEXT NOT NULL REFERENCES community_topics(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, topic_id)
);

CREATE TABLE IF NOT EXISTS community_notifications (
  id TEXT PRIMARY KEY,
  recipient_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  event_key TEXT NOT NULL,
  event_type TEXT NOT NULL,
  actor_member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  entity_type TEXT NOT NULL DEFAULT 'post',
  entity_id TEXT NOT NULL DEFAULT '',
  post_id TEXT REFERENCES community_posts(id) ON DELETE CASCADE,
  payload_json TEXT NOT NULL DEFAULT '{}',
  read_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (recipient_member_id, event_key)
);

CREATE INDEX IF NOT EXISTS community_notifications_member_idx
  ON community_notifications (recipient_member_id, read_at, created_at DESC);
CREATE INDEX IF NOT EXISTS community_notifications_unread_idx
  ON community_notifications (recipient_member_id, created_at DESC) WHERE read_at IS NULL;

COMMIT;
