"use client";
import { useState } from "react";
import { ExportLink } from "./AdminSharedComponents";
import type { AdminPayment, AdminRefund, AdminWallet, PaymentEvent, PaymentProvider, Reconciliation } from "./admin-types";

export function PaymentAdmin({ providers, payments, refunds, wallets, events, reconciliation, canManage, onAct, onRefund }: { providers: PaymentProvider[]; payments: AdminPayment[]; refunds: AdminRefund[]; wallets: AdminWallet[]; events: PaymentEvent[]; reconciliation: Reconciliation; canManage: boolean; onAct: (payload: Record<string, unknown>) => Promise<boolean>; onRefund: (payment: AdminPayment) => void }) {
  return <div className="admin-payment-stack">
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>支付与退款对账</h2><p>订单、支付、退款和库存确认状态自动交叉核验</p></div><div className="admin-panel-actions"><ExportLink type="payment-reconciliation" /><ExportLink type="refund-reconciliation" /></div></div><div className="stat-grid"><article><span>支付笔数</span><b>{reconciliation.summary.paymentCount}</b></article><article><span>收款金额</span><b>{(reconciliation.summary.paidFen / 100).toFixed(2)} 元</b></article><article><span>成功退款</span><b>{(reconciliation.summary.refundedFen / 100).toFixed(2)} 元</b></article><article><span>净收款</span><b>{(reconciliation.summary.netFen / 100).toFixed(2)} 元</b></article><article><span>异常项目</span><b>{reconciliation.summary.anomalyCount}</b></article></div>{reconciliation.items.some((item) => item.anomalies.length) ? <div className="admin-table-wrap"><table><thead><tr><th>订单 / 交易</th><th>渠道</th><th>支付</th><th>退款</th><th>净额</th><th>异常</th></tr></thead><tbody>{reconciliation.items.filter((item) => item.anomalies.length).map((item) => <tr key={item.payment_id}><td><b>{item.order_id}</b><small>{item.merchant_trade_no}</small></td><td>{item.provider === "wechat" ? "微信支付" : "支付宝"}</td><td>{(item.amount_fen / 100).toFixed(2)} 元<small>{item.payment_status}</small></td><td>{(item.succeeded_refund_fen / 100).toFixed(2)} 元</td><td>{(item.net_fen / 100).toFixed(2)} 元</td><td><span className="payment-row-error">{item.anomalies.join("；")}</span></td></tr>)}</tbody></table></div> : <p className="admin-empty">当前支付、退款、订单和库存确认数据一致。</p>}</section>
    <section className="payment-provider-grid">{providers.map((provider) => <form className="payment-provider-card" key={provider.provider} onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "update-payment-provider", provider: provider.provider, enabled: values.enabled === "on", mode: values.mode, appId: values.appId, merchantId: values.merchantId, publicKeyId: values.publicKeyId, certificateSerial: values.certificateSerial }); }}>
      <div className="payment-provider-title"><div><span>{provider.provider === "wechat" ? "WECHAT PAY" : "ALIPAY"}</span><h2>{provider.display_name}</h2></div><label className="admin-switch"><input type="checkbox" name="enabled" defaultChecked={Boolean(provider.enabled)} /><i /></label></div>
      <div className={`payment-config-state ${provider.configured ? "ready" : ""}`}><b>{provider.configured ? "配置完整，可发起真实交易" : "配置未完成，前台不会扣款"}</b><span>私钥 {provider.secrets.privateKey ? "已安装" : "未安装"} · 公钥 {provider.secrets.publicKey ? "已安装" : "未安装"}{provider.provider === "wechat" ? ` · API v3 密钥 ${provider.secrets.apiV3Key ? "已安装" : "未安装"}` : ""}</span>{provider.missing.length > 0 && <small>还缺：{provider.missing.join("、")}</small>}</div>
      <div className="payment-provider-form"><label>运行环境<select name="mode" defaultValue={provider.mode}><option value="production">正式环境</option>{provider.provider === "alipay" && <option value="sandbox">沙箱环境</option>}</select></label><label>应用 ID<input name="appId" defaultValue={provider.app_id} autoComplete="off" /></label><label>商户号<input name="merchantId" defaultValue={provider.merchant_id} autoComplete="off" /></label>{provider.provider === "wechat" && <><label>平台公钥 ID<input name="publicKeyId" defaultValue={provider.public_key_id} autoComplete="off" /></label><label>商户证书序列号<input name="certificateSerial" defaultValue={provider.certificate_serial} autoComplete="off" /></label></>}</div>
      <p>私钥、公钥和 API v3 密钥仅通过服务器环境变量配置，后台不会保存或回显。支付回调：https://pusy.cn/api/payments/webhooks/{provider.provider}{provider.provider === "wechat" ? "；退款回调：https://pusy.cn/api/payments/webhooks/wechat/refund" : ""}</p><button className="admin-save">保存渠道配置</button>
    </form>)}</section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>会员账户余额</h2><p>余额调整会生成不可变账本和后台审计记录</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>会员</th><th>可用余额</th><th>冻结余额</th><th>支付密码</th><th>调整</th></tr></thead><tbody>{wallets.length ? wallets.map((wallet) => <tr key={wallet.member_id}><td><b>{wallet.name}</b><small>#{wallet.member_id} · {wallet.email}</small></td><td>{(wallet.available_balance_fen / 100).toFixed(2)} 元</td><td>{(wallet.frozen_balance_fen / 100).toFixed(2)} 元</td><td>{wallet.payment_password_set ? "已设置" : "未设置"}</td><td>{canManage ? <button className="admin-text-button" onClick={() => { const amountYuan = window.prompt("调整金额（元）；增加填正数，扣减填负数", ""); const reason = window.prompt("调整原因（必填）", "人工余额调整"); if (amountYuan && reason) void onAct({ action: "adjust-member-wallet", memberId: wallet.member_id, amountYuan, reason }); }}>调整余额</button> : "只读"}</td></tr>) : <tr><td colSpan={5} className="admin-empty">暂无会员余额账户</td></tr>}</tbody></table></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>支付交易</h2><p>{payments.length} 笔记录</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>订单 / 客户</th><th>渠道</th><th>金额</th><th>支付状态</th><th>尝试</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{payments.length ? payments.map((payment) => <tr key={payment.id}><td><b>{payment.order_id}</b><small>{payment.customer} · {payment.email}<br />{payment.merchant_trade_no}</small></td><td>{payment.provider === "wechat" ? "微信支付" : "支付宝"}</td><td>{(payment.amount_fen / 100).toFixed(2)} 元<small>余额 {(payment.wallet_amount_fen / 100).toFixed(2)} · 渠道 {(payment.external_amount_fen / 100).toFixed(2)}</small></td><td><PaymentStatus value={payment.status} />{payment.last_error && <small className="payment-row-error">{payment.last_error}</small>}</td><td>{payment.attempts}</td><td>{new Date(payment.updated_at).toLocaleString("zh-CN")}</td><td><button className="admin-text-button" onClick={() => void onAct({ action: "sync-payment", id: payment.id })}>同步</button>{payment.status === "failed" && <button className="admin-text-button" onClick={() => void onAct({ action: "retry-payment", orderId: payment.order_id, provider: payment.provider })}>重试</button>}{["paid","partially_refunded"].includes(payment.status) && <button className="admin-text-button danger" onClick={() => onRefund(payment)}>退款</button>}</td></tr>) : <tr><td colSpan={7} className="admin-empty">还没有支付交易</td></tr>}</tbody></table></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>退款记录</h2><p>{refunds.length} 笔记录</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>退款单 / 订单</th><th>渠道</th><th>金额</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody>{refunds.length ? refunds.map((refund) => <tr key={refund.id}><td><b>{refund.id}</b><small>{refund.order_id}<br />{refund.merchant_refund_no}</small></td><td>{refund.provider === "wechat" ? "微信支付" : "支付宝"}</td><td>{(refund.amount_fen / 100).toFixed(2)} 元<small>退余额 {(refund.wallet_amount_fen / 100).toFixed(2)} · 退渠道 {(refund.external_amount_fen / 100).toFixed(2)}</small></td><td>{refund.reason}{refund.last_error && <small className="payment-row-error">{refund.last_error}</small>}</td><td><PaymentStatus value={refund.status} /></td><td><button className="admin-text-button" onClick={() => void onAct({ action: "sync-refund", id: refund.id })}>同步</button>{refund.status === "failed" && <button className="admin-text-button" onClick={() => void onAct({ action: "retry-refund", id: refund.id })}>重试</button>}</td></tr>) : <tr><td colSpan={6} className="admin-empty">还没有退款记录</td></tr>}</tbody></table></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>回调审计</h2><p>最近 {events.length} 条已验签事件</p></div></div><div className="payment-event-list">{events.length ? events.map((event) => <article key={event.id}><div><b>{event.provider === "wechat" ? "微信支付" : "支付宝"} · {event.event_type}</b><small>{event.id}</small></div><PaymentStatus value={event.result} /><time>{new Date(event.created_at).toLocaleString("zh-CN")}</time>{event.message && <p>{event.message}</p>}</article>) : <p className="admin-empty">尚未收到支付回调</p>}</div></section>
  </div>;
}

export function PaymentStatus({ value }: { value: string }) {
  const labels: Record<string, string> = { created: "已创建", pending: "待支付", paid: "已支付", failed: "失败", closed: "已关闭", refunding: "退款中", partially_refunded: "部分退款", refunded: "已退款", processing: "处理中", succeeded: "成功", processed: "已处理", rejected: "已拒绝", ignored: "已忽略" };
  return <span className={`payment-status status-${value}`}>{labels[value] ?? value}</span>;
}

export function RefundModal({ payment, onClose, onSubmit }: { payment: AdminPayment; onClose: () => void; onSubmit: (amountYuan: number, reason: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  return <div className="admin-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form onSubmit={async (event) => { event.preventDefault(); setBusy(true); const values = new FormData(event.currentTarget); await onSubmit(Number(values.get("amountYuan")), String(values.get("reason") ?? "")); setBusy(false); }}><div className="admin-panel-title"><div><p>订单 {payment.order_id}</p><h2>发起退款</h2></div><button type="button" onClick={onClose}>×</button></div><p className="admin-help">原支付金额 {(payment.amount_fen / 100).toFixed(2)} 元。系统会校验累计可退余额，并使用固定退款单号安全重试。</p><div className="admin-form-grid"><label>退款金额（元）<input name="amountYuan" type="number" min="0.01" max={(payment.amount_fen / 100).toFixed(2)} step="0.01" required /></label><label>退款原因<input name="reason" maxLength={80} required placeholder="例如：客户取消订单" /></label></div><button className="admin-save" disabled={busy}>{busy ? "正在提交退款…" : "确认发起退款"}</button></form></div>;
}
