"use client";
import type { ChinaRegionSettings, NotificationJob, NotificationSetting, NotificationTemplate, PaymentProvider } from "./admin-types";

export function NotificationAdmin({ settings, templates, jobs, onAct }: { settings: NotificationSetting[]; templates: NotificationTemplate[]; jobs: NotificationJob[]; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  return <div className="admin-notification-stack">
    <section className="notification-settings-grid">{settings.map((setting) => <form className="notification-setting-card" key={setting.channel} onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "update-notification-setting", channel: setting.channel, enabled: values.enabled === "on", senderName: values.senderName, senderAddress: values.senderAddress }); }}><div className="payment-provider-title"><div><span>{setting.provider.toUpperCase()}</span><h2>{setting.display_name}</h2></div><label className="admin-switch"><input type="checkbox" name="enabled" defaultChecked={Boolean(setting.enabled)} /><i /></label></div><div className={`payment-config-state ${setting.configured ? "ready" : ""}`}><b>{setting.configured ? "配置完整，可发送通知" : "配置未完成，不会发送"}</b><span>服务器密钥 {setting.secretInstalled ? "已安装" : "未安装"}</span></div><label>发件名称<input name="senderName" defaultValue={setting.sender_name} /></label><label>{setting.channel === "email" ? "发件邮箱" : "短信签名 / Sender ID"}<input name="senderAddress" defaultValue={setting.sender_address} placeholder={setting.channel === "email" ? "notice@PUSY.CN" : "PUSY.CN"} /></label><p>{setting.channel === "email" ? "邮件通过 Resend 发送，API 密钥只保存在服务器环境变量。" : "短信通过独立 HTTP 网关适配器发送，可对接国内合规短信服务商。"}</p><button className="admin-save">保存渠道配置</button></form>)}</section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>消息模板</h2><p>支持变量：订单号、客户、金额、配送、礼品卡代码等</p></div></div><div className="notification-template-list">{templates.map((template) => <details key={template.key}><summary><div><b>{template.name}</b><small>{template.key}</small></div><span>{template.enabled ? "已启用" : "已停用"} ＋</span></summary><form onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "update-notification-template", key: template.key, enabled: values.enabled === "on", emailSubject: values.emailSubject, emailBody: values.emailBody, smsBody: values.smsBody }); }}><label className="notification-template-toggle"><input type="checkbox" name="enabled" defaultChecked={Boolean(template.enabled)} /> 启用此模板</label><label>邮件标题<input name="emailSubject" defaultValue={template.email_subject} /></label><label>邮件正文<textarea name="emailBody" defaultValue={template.email_body} rows={7} /></label><label>短信正文<textarea name="smsBody" defaultValue={template.sms_body} rows={3} maxLength={500} /></label><button className="admin-save">保存模板</button></form></details>)}</div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>发送记录</h2><p>{jobs.length} 条通知任务</p></div><button onClick={() => void onAct({ action: "process-notifications" })}>处理到期队列</button></div><div className="admin-table-wrap"><table><thead><tr><th>事件 / 接收人</th><th>渠道</th><th>模板</th><th>计划时间</th><th>状态</th><th>尝试</th><th>操作</th></tr></thead><tbody>{jobs.length ? jobs.map((job) => <tr key={job.id}><td><b>{job.entity_id}</b><small>{job.recipient}<br />{job.event_key}</small></td><td>{job.channel === "email" ? "邮件" : "短信"}</td><td>{templates.find((item) => item.key === job.template_key)?.name ?? job.template_key}</td><td>{new Date(job.scheduled_at).toLocaleString("zh-CN")}</td><td><NotificationStatus value={job.status} />{job.last_error && <small className="payment-row-error">{job.last_error}</small>}</td><td>{job.attempts}</td><td>{job.status !== "sent" && <button className="admin-text-button" onClick={() => void onAct({ action: "retry-notification", id: job.id })}>立即重试</button>}</td></tr>) : <tr><td colSpan={7} className="admin-empty">还没有消息通知记录</td></tr>}</tbody></table></div></section>
  </div>;
}

function NotificationStatus({ value }: { value: string }) { const labels: Record<string,string> = { queued: "待发送", failed: "发送失败", sent: "已发送", delivered: "已送达", bounced: "已退信", complained: "被投诉" }; return <span className={`payment-status status-${value}`}>{labels[value] ?? value}</span>; }

export function ChinaRegionAdmin({ settings, providers, onOpenPayments }: { settings: ChinaRegionSettings; providers: PaymentProvider[]; onOpenPayments: () => void }) {
  const identityItems = [["中国区运营主体", settings.operatorName], ["统一社会信用代码", settings.unifiedSocialCreditCode], ["注册地址", settings.registeredAddress], ["客服电话", settings.customerServicePhone], ["客服邮箱", settings.supportEmail], ["隐私联系邮箱", settings.privacyEmail], ["ICP备案", settings.icpNumber], ["公安联网备案", settings.publicSecurityNumber]];
  const paymentsReady = providers.some((provider) => provider.enabled && provider.configured);
  return <div className="china-settings-stack">
    <section className="admin-panel china-readiness"><div className="admin-panel-title"><div><h2>中国区上线状态</h2><p>市场：中国大陆 · 语言：简体中文 · 时区：{settings.timeZone} · 货币：{settings.currency}</p></div><span className={`payment-status ${settings.complianceReady && paymentsReady ? "status-paid" : "status-pending"}`}>{settings.complianceReady && paymentsReady ? "基本配置完成" : "尚未满足上线条件"}</span></div><div className="china-check-grid"><article className={settings.complianceReady ? "ready" : "pending"}><b>{settings.complianceReady ? "✓" : "!"} 经营主体与备案</b><p>{settings.complianceReady ? "主体、联系方式与备案信息已配置。" : "仍有待补充信息，请通过服务器环境变量配置。"}</p></article><article className={paymentsReady ? "ready" : "pending"}><b>{paymentsReady ? "✓" : "!"} 中国区支付</b><p>{paymentsReady ? "至少一个支付渠道已启用并配置完整。" : "微信支付和支付宝均未达到可交易状态。"}</p></article><article className="ready"><b>✓ 中国区政策</b><p>隐私、Cookie、销售条款、配送和退换货页面已切换为中国区版本。</p></article></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>经营与备案信息</h2><p>以下内容会用于中国区法律公示；敏感配置不写入前端代码。</p></div><a href="/details" target="_blank" rel="noopener noreferrer">查看公示页</a></div><div className="china-settings-list">{identityItems.map(([label, value]) => <div key={label}><span>{label}</span><b className={value.startsWith("待") ? "pending" : ""}>{value}</b></div>)}</div><div className="admin-config-note"><b>配置方式</b><p>在运行环境中设置 CHINA_OPERATOR_NAME、CHINA_UNIFIED_SOCIAL_CREDIT_CODE、CHINA_REGISTERED_ADDRESS、CHINA_CUSTOMER_SERVICE_PHONE、CHINA_SUPPORT_EMAIL、CHINA_PRIVACY_EMAIL、CHINA_ICP_NUMBER 和 CHINA_PUBLIC_SECURITY_NUMBER。正式主体信息确认前不会用虚构资料填充。</p></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>支付渠道状态</h2><p>支付密钥由服务器环境管理，非管理员页面明文保存。</p></div><button onClick={onOpenPayments}>前往支付配置</button></div><div className="china-check-grid">{providers.map((provider) => <article className={provider.enabled && provider.configured ? "ready" : "pending"} key={provider.provider}><b>{provider.display_name}</b><p>{provider.enabled ? provider.configured ? "已启用，可发起真实交易。" : "已启用，但商户资料或服务器密钥不完整。" : "当前未启用。"}</p></article>)}</div></section>
  </div>;
}
