"use client";
import { useEffect, useMemo, useState } from "react";
import { formatCnyFromRub } from "../data/products";

type AdminProduct = { id: number; slug: string; name: string; category: string; description: string; image: string; image_alt?: string; badge?: string; price: number; old_price?: number; stock: number; inventory_verified: number; sku?: string; volume?: string; ingredients?: string; usage?: string; status: string };
type AdminOrder = { id: string; member_id?: number; customer: string; email: string; phone: string; address: string; delivery: string; payment: string; total: number; status: string; item_count: number; created_at: string };
type OrderItem = { id: number; order_id: string; product_slug: string; product_name: string; quantity: number; unit_price: number };
type AdminMember = { id: number; name: string; email: string; phone: string; status: string; total_orders: number; total_spent: number; joined_at: string };
type Subscriber = { id: number; email: string; source: string; status: string; subscribed_at: string };
type AdminReturn = { id: string; order_id: string; email: string; reason: string; details: string; status: string; created_at: string };
type RetailPartnership = { id: string; contact_name: string; phone: string; company: string; city: string; cooperation_type: string; wechat: string; email: string; proposal: string; status: string; created_at: string; updated_at: string };
type Coupon = { id: number; code: string; kind: string; value: number; minimum: number; usage_limit: number; used_count: number; status: string; starts_at?: string; ends_at?: string };
type GiftCard = { code: string; order_id: string; initial_balance: number; balance: number; recipient_name: string; recipient_email: string; delivery_date?: string; status: string; created_at: string };
type TrendPoint = { day: string; revenue: number; orders: number };
type PaymentProvider = { provider: "wechat" | "alipay"; display_name: string; enabled: number; mode: string; app_id: string; merchant_id: string; public_key_id: string; certificate_serial: string; configured: boolean; secrets: { privateKey: boolean; publicKey: boolean; apiV3Key?: boolean } };
type AdminPayment = { id: string; order_id: string; provider: "wechat" | "alipay"; merchant_trade_no: string; provider_transaction_id?: string; amount_fen: number; status: string; attempts: number; last_error?: string; customer: string; email: string; created_at: string; updated_at: string };
type AdminRefund = { id: string; payment_id: string; order_id: string; provider: "wechat" | "alipay"; merchant_refund_no: string; provider_refund_id?: string; amount_fen: number; reason: string; status: string; attempts: number; last_error?: string; created_at: string; updated_at: string };
type PaymentEvent = { id: string; payment_id?: string; provider: string; event_type: string; verified: number; result: string; message?: string; created_at: string };
type ChinaRegionSettings = { market: string; currency: string; locale: string; timeZone: string; domain: string; supportEmail: string; operatorName: string; unifiedSocialCreditCode: string; registeredAddress: string; customerServicePhone: string; icpNumber: string; publicSecurityNumber: string; privacyEmail: string; updatedAt: string; complianceReady: boolean };
type NotificationSetting = { channel: "email" | "sms"; display_name: string; enabled: number; provider: string; sender_name: string; sender_address: string; configured: boolean; secretInstalled: boolean };
type NotificationTemplate = { key: string; name: string; email_subject: string; email_body: string; sms_body: string; enabled: number; updated_at: string };
type NotificationJob = { id: string; event_key: string; entity_type: string; entity_id: string; template_key: string; channel: string; recipient: string; status: string; attempts: number; scheduled_at: string; next_retry_at?: string; provider_message_id?: string; last_error?: string; sent_at?: string; created_at: string };
type AdminData = { products: AdminProduct[]; orders: AdminOrder[]; orderItems: OrderItem[]; members: AdminMember[]; subscribers: Subscriber[]; returns: AdminReturn[]; retailPartnerships: RetailPartnership[]; coupons: Coupon[]; giftCards: GiftCard[]; providers: PaymentProvider[]; payments: AdminPayment[]; refunds: AdminRefund[]; paymentEvents: PaymentEvent[]; notificationSettings: NotificationSetting[]; notificationTemplates: NotificationTemplate[]; notificationJobs: NotificationJob[]; region: ChinaRegionSettings; revenueTrend: TrendPoint[]; stats: { order_count: number; revenue: number; pending_count: number; avg_order_value: number; low_stock_count: number; unverified_inventory_count: number; active_subscribers: number; pending_returns: number; pending_partnerships: number } };
const emptyProduct: Omit<AdminProduct, "id"> = { slug: "", name: "", category: "彩妆", description: "", image: "/assets/01.webp", image_alt: "", badge: "", price: 0, old_price: 0, stock: 0, inventory_verified: 0, sku: "", volume: "", ingredients: "", usage: "", status: "active" };
const storedToYuan = (value?: number) => value ? Number((value * 0.12).toFixed(2)) : 0;

export function AdminClient({ viewer, canSignOut }: { viewer: string; canSignOut: boolean }) {
  const [tab, setTab] = useState("overview");
  const [data, setData] = useState<AdminData | null>(null);
  const [editing, setEditing] = useState<AdminProduct | null>(null);
  const [creating, setCreating] = useState(false);
  const [importing, setImporting] = useState(false);
  const [selectedOrder, setSelectedOrder] = useState<AdminOrder | null>(null);
  const [selectedMember, setSelectedMember] = useState<AdminMember | null>(null);
  const [refundPayment, setRefundPayment] = useState<AdminPayment | null>(null);
  const [query, setQuery] = useState("");
  const [message, setMessage] = useState("");
  const [loading, setLoading] = useState(true);

  async function load() {
    setLoading(true);
    const response = await fetch("/api/admin", { cache: "no-store" });
    const body = await response.json();
    if (!response.ok) setMessage(body.error || "加载失败"); else setData(body);
    setLoading(false);
  }
  useEffect(() => { queueMicrotask(() => { void load(); }); }, []);
  async function act(payload: Record<string, unknown>) {
    setMessage("正在保存…");
    const response = await fetch("/api/admin", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
    const body = await response.json();
    if (!response.ok) { setMessage(body.error || "保存失败"); return false; }
    setMessage("已保存"); await load(); return true;
  }
  async function saveProduct(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const payload = Object.fromEntries(new FormData(event.currentTarget).entries());
    const ok = await act({ action: editing ? "update-product" : "create-product", id: editing?.id, ...payload });
    if (ok) { setEditing(null); setCreating(false); }
  }
  async function saveCoupon(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const payload = Object.fromEntries(new FormData(event.currentTarget).entries());
    if (await act({ action: "create-coupon", ...payload })) event.currentTarget.reset();
  }
  function changeTab(next: string) { setTab(next); setQuery(""); }

  const normalized = query.trim().toLowerCase();
  const filtered = useMemo(() => {
    if (!data || !normalized) return { products: data?.products ?? [], orders: data?.orders ?? [], members: data?.members ?? [], subscribers: data?.subscribers ?? [], returns: data?.returns ?? [], retailPartnerships: data?.retailPartnerships ?? [], coupons: data?.coupons ?? [], giftCards: data?.giftCards ?? [], payments: data?.payments ?? [], refunds: data?.refunds ?? [], notificationJobs: data?.notificationJobs ?? [] };
    return {
      products: data.products.filter((item) => `${item.name} ${item.slug} ${item.category} ${item.status}`.toLowerCase().includes(normalized)),
      orders: data.orders.filter((item) => `${item.id} ${item.customer} ${item.email} ${item.phone} ${item.status}`.toLowerCase().includes(normalized)),
      members: data.members.filter((item) => `${item.name} ${item.email} ${item.phone} ${item.status}`.toLowerCase().includes(normalized)),
      subscribers: data.subscribers.filter((item) => `${item.email} ${item.source} ${item.status}`.toLowerCase().includes(normalized)),
      returns: data.returns.filter((item) => `${item.id} ${item.order_id} ${item.email} ${item.reason} ${item.status}`.toLowerCase().includes(normalized)),
      retailPartnerships: data.retailPartnerships.filter((item) => `${item.id} ${item.contact_name} ${item.phone} ${item.company} ${item.city} ${item.cooperation_type} ${item.wechat} ${item.email} ${item.proposal} ${item.status}`.toLowerCase().includes(normalized)),
      coupons: data.coupons.filter((item) => `${item.code} ${item.kind} ${item.status}`.toLowerCase().includes(normalized)),
      giftCards: data.giftCards.filter((item) => `${item.code} ${item.order_id} ${item.recipient_name} ${item.recipient_email} ${item.status}`.toLowerCase().includes(normalized)),
      payments: data.payments.filter((item) => `${item.id} ${item.order_id} ${item.merchant_trade_no} ${item.customer} ${item.email} ${item.provider} ${item.status}`.toLowerCase().includes(normalized)),
      refunds: data.refunds.filter((item) => `${item.id} ${item.order_id} ${item.merchant_refund_no} ${item.provider} ${item.reason} ${item.status}`.toLowerCase().includes(normalized)),
      notificationJobs: data.notificationJobs.filter((item) => `${item.id} ${item.event_key} ${item.entity_id} ${item.template_key} ${item.channel} ${item.recipient} ${item.status}`.toLowerCase().includes(normalized)),
    };
  }, [data, normalized]);

  return <main className="admin-shell">
    <aside className="admin-sidebar"><a className="admin-brand" href="/">PUSY.CN</a><p>中国区商城管理后台</p><nav>{[["overview","总览"],["settings","中国区设置"],["orders","订单管理"],["payments","支付与退款"],["notifications","消息通知"],["members","会员管理"],["products","产品管理"],["returns","售后管理"],["partnerships","零售合作"],["marketing","营销工具"],["subscribers","订阅用户"]].map(([key,label]) => <button className={tab === key ? "active" : ""} onClick={() => changeTab(key)} key={key}>{label}</button>)}</nav><div className="admin-viewer"><span>当前用户</span><b>{viewer}</b>{canSignOut && <a href="/signout-with-chatgpt?return_to=/">退出登录</a>}</div><a className="admin-store-link" href="/">← 返回商城</a></aside>
    <section className="admin-main"><header><div><p>PUSY.CN / CHINA ADMIN</p><h1>{({overview:"经营总览",settings:"中国区设置",orders:"订单管理",payments:"支付与退款",notifications:"消息通知",members:"会员管理",products:"产品管理",returns:"售后管理",partnerships:"零售合作",marketing:"营销工具",subscribers:"订阅用户"} as Record<string,string>)[tab]}</h1></div><div className="admin-status"><i /> 商城数据库已连接</div></header>
      {!['overview','settings'].includes(tab) && <div className="admin-search"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索当前列表" /><span>{query ? `${tab === "orders" ? filtered.orders.length : tab === "payments" ? filtered.payments.length + filtered.refunds.length : tab === "notifications" ? filtered.notificationJobs.length : tab === "members" ? filtered.members.length : tab === "products" ? filtered.products.length : tab === "returns" ? filtered.returns.length : tab === "partnerships" ? filtered.retailPartnerships.length : tab === "marketing" ? filtered.coupons.length + filtered.giftCards.length : filtered.subscribers.length} 条结果` : ""}</span></div>}
      {message && <div className="admin-message">{message}</div>}
      {loading && !data ? <div className="admin-loading">正在读取商城数据…</div> : data && <>
        {tab === "overview" && <div className="admin-overview"><section className="stat-grid"><article><span>累计订单</span><b>{data.stats?.order_count ?? 0}</b></article><article><span>累计销售额</span><b>{formatCnyFromRub(data.stats?.revenue ?? 0)}</b></article><article><span>平均客单价</span><b>{formatCnyFromRub(Math.round(data.stats?.avg_order_value ?? 0))}</b></article><article><span>待处理订单</span><b>{data.stats?.pending_count ?? 0}</b></article><article><span>待核验库存</span><b>{data.stats?.unverified_inventory_count ?? 0}</b></article><article><span>低库存商品</span><b>{data.stats?.low_stock_count ?? 0}</b></article><article><span>待审核售后</span><b>{data.stats?.pending_returns ?? 0}</b></article><article><span>待联系合作</span><b>{data.stats?.pending_partnerships ?? 0}</b></article></section><RevenueChart points={data.revenueTrend} /><section className="admin-panel"><div className="admin-panel-title"><h2>最新订单</h2><button onClick={() => changeTab("orders")}>查看全部</button></div><OrderTable orders={data.orders.slice(0, 6)} onOpen={setSelectedOrder} onStatus={(id,status) => act({ action:"update-order-status", id, status })} /></section></div>}
        {tab === "settings" && <ChinaRegionAdmin settings={data.region} providers={data.providers} onOpenPayments={() => changeTab("payments")} />}
        {tab === "orders" && <section className="admin-panel"><div className="admin-panel-title"><h2>全部订单</h2><div className="admin-panel-actions"><span>{filtered.orders.length} 条记录</span><ExportLink type="orders" /></div></div><OrderTable orders={filtered.orders} onOpen={setSelectedOrder} onStatus={(id,status) => act({ action:"update-order-status", id, status })} /></section>}
        {tab === "payments" && <PaymentAdmin providers={data.providers} payments={filtered.payments} refunds={filtered.refunds} events={data.paymentEvents} onAct={act} onRefund={setRefundPayment} />}
        {tab === "notifications" && <NotificationAdmin settings={data.notificationSettings} templates={data.notificationTemplates} jobs={filtered.notificationJobs} onAct={act} />}
        {tab === "members" && <section className="admin-panel"><div className="admin-panel-title"><h2>会员档案</h2><div className="admin-panel-actions"><span>{filtered.members.length} 位会员</span><ExportLink type="members" /></div></div><div className="admin-table-wrap"><table><thead><tr><th>会员</th><th>联系方式</th><th>订单</th><th>累计消费</th><th>加入时间</th><th>状态</th><th>详情</th></tr></thead><tbody>{filtered.members.map((member) => <tr key={member.id}><td><b>{member.name}</b><small>#{member.id}</small></td><td>{member.email}<small>{member.phone}</small></td><td>{member.total_orders}</td><td>{formatCnyFromRub(member.total_spent)}</td><td>{new Date(member.joined_at).toLocaleDateString("zh-CN")}</td><td><select value={member.status} onChange={(event) => act({ action:"update-member-status", id:member.id, status:event.target.value })}><option value="active">普通会员</option><option value="vip">VIP</option><option value="blocked">已停用</option></select></td><td><button className="admin-text-button" onClick={() => setSelectedMember(member)}>查看</button></td></tr>)}</tbody></table></div></section>}
        {tab === "products" && <section className="admin-panel"><div className="admin-panel-title"><div><h2>商品库</h2><p>库存由本商城独立管理；完成数量核验后，商品才允许加入购物袋。</p></div><div className="admin-panel-actions"><ExportLink type="products" /><button onClick={() => setImporting(true)}>批量导入</button><button className="admin-primary" onClick={() => { setEditing(null); setCreating(true); }}>＋ 新建商品</button></div></div><div className="admin-table-wrap"><table><thead><tr><th>商品</th><th>分类</th><th>价格</th><th>库存</th><th>核验状态</th><th>状态</th><th>操作</th></tr></thead><tbody>{filtered.products.map((product) => <tr key={product.id}><td><div className="admin-product-cell"><img src={product.image} alt="" /><span><b>{product.name}</b><small>/{product.slug}</small></span></div></td><td>{product.category}</td><td>{formatCnyFromRub(product.price)}</td><td className={product.inventory_verified && product.stock < 10 ? "low-stock" : ""}>{product.inventory_verified ? product.stock : "—"}</td><td>{product.inventory_verified ? "已核验" : "待核验"}</td><td>{product.status === "active" ? "销售中" : "已下架"}</td><td><button className="admin-text-button" onClick={() => { setEditing(product); setCreating(false); }}>编辑</button>{product.status === "active" && <button className="admin-text-button danger" onClick={() => act({ action:"archive-product", id:product.id })}>下架</button>}</td></tr>)}</tbody></table></div></section>}
        {tab === "returns" && <section className="admin-panel"><div className="admin-panel-title"><h2>售后申请</h2><div className="admin-panel-actions"><span>{filtered.returns.length} 条申请</span><ExportLink type="returns" /></div></div><div className="admin-table-wrap"><table><thead><tr><th>售后单号</th><th>订单号</th><th>客户邮箱</th><th>原因 / 说明</th><th>申请时间</th><th>状态</th></tr></thead><tbody>{filtered.returns.length ? filtered.returns.map((item) => <tr key={item.id}><td><b>{item.id}</b></td><td>{item.order_id}</td><td>{item.email}</td><td>{item.reason}<small>{item.details || "无补充说明"}</small></td><td>{new Date(item.created_at).toLocaleString("zh-CN")}</td><td><select value={item.status} onChange={(event) => act({ action:"update-return-status", id:item.id, status:event.target.value })}>{["待审核","已批准","已拒绝","已退款","已关闭"].map((status) => <option key={status}>{status}</option>)}</select></td></tr>) : <tr><td className="admin-empty" colSpan={6}>暂无售后申请</td></tr>}</tbody></table></div></section>}
        {tab === "partnerships" && <section className="admin-panel"><div className="admin-panel-title"><div><h2>中国区零售合作申请</h2><p>集中处理官网提交的渠道、经销与企业采购咨询。</p></div><div className="admin-panel-actions"><span>{filtered.retailPartnerships.length} 条申请</span><ExportLink type="partnerships" /></div></div><div className="admin-table-wrap"><table><thead><tr><th>申请人 / 公司</th><th>联系方式</th><th>地区 / 类型</th><th>合作方案</th><th>提交时间</th><th>状态</th></tr></thead><tbody>{filtered.retailPartnerships.length ? filtered.retailPartnerships.map((item) => <tr key={item.id}><td><b>{item.contact_name}</b><small>{item.company}<br />{item.id}</small></td><td>{item.phone}<small>{item.wechat ? `微信：${item.wechat}` : "未填写微信"}<br />{item.email || "未填写邮箱"}</small></td><td>{item.city}<small>{item.cooperation_type}</small></td><td className="admin-partnership-proposal">{item.proposal}</td><td>{new Date(item.created_at).toLocaleString("zh-CN")}</td><td><select value={item.status} onChange={(event) => act({ action:"update-retail-partnership-status", id:item.id, status:event.target.value })}>{["待联系","洽谈中","已合作","已拒绝","已关闭"].map((status) => <option key={status}>{status}</option>)}</select></td></tr>) : <tr><td className="admin-empty" colSpan={6}>暂无零售合作申请</td></tr>}</tbody></table></div></section>}
        {tab === "marketing" && <div className="admin-marketing"><section className="admin-panel"><div className="admin-panel-title"><h2>优惠码</h2><span>{filtered.coupons.length} 个</span></div><form className="coupon-admin-form" onSubmit={saveCoupon}><input name="code" placeholder="优惠码，例如 SUMMER20" required /><select name="kind"><option value="percent">百分比</option><option value="fixed">固定金额（元）</option></select><input name="value" type="number" min="1" step="0.01" placeholder="折扣比例或金额" required /><input name="minimum" type="number" min="0" step="0.01" placeholder="最低消费（元）" /><input name="usageLimit" type="number" min="0" placeholder="限用次数，0不限" /><button>创建优惠码</button></form><div className="admin-table-wrap"><table><thead><tr><th>优惠码</th><th>方式</th><th>门槛</th><th>使用</th><th>状态</th></tr></thead><tbody>{filtered.coupons.map((coupon) => <tr key={coupon.id}><td><b>{coupon.code}</b></td><td>{coupon.kind === "percent" ? `${coupon.value}%` : formatCnyFromRub(coupon.value)}</td><td>{coupon.minimum ? formatCnyFromRub(coupon.minimum) : "无门槛"}</td><td>{coupon.used_count} / {coupon.usage_limit || "不限"}</td><td><select value={coupon.status} onChange={(event) => act({ action:"update-coupon-status", id:coupon.id, status:event.target.value })}><option value="active">启用</option><option value="disabled">停用</option></select></td></tr>)}</tbody></table></div></section><section className="admin-panel"><div className="admin-panel-title"><h2>礼品卡</h2><span>{filtered.giftCards.length} 张</span></div><div className="admin-table-wrap"><table><thead><tr><th>卡号</th><th>收件人</th><th>余额</th><th>来源订单</th><th>发送日期</th><th>状态</th></tr></thead><tbody>{filtered.giftCards.length ? filtered.giftCards.map((card) => <tr key={card.code}><td><b>{card.code}</b></td><td>{card.recipient_name}<small>{card.recipient_email}</small></td><td>{formatCnyFromRub(card.balance)}<small>初始 {formatCnyFromRub(card.initial_balance)}</small></td><td>{card.order_id}</td><td>{card.delivery_date || "立即"}</td><td><select value={card.status} onChange={(event) => act({ action:"update-gift-card-status", code:card.code, status:event.target.value })}><option value="active">有效</option><option value="used">已用完</option><option value="void">已作废</option></select></td></tr>) : <tr><td className="admin-empty" colSpan={6}>完成礼品卡订单后会在这里生成卡号</td></tr>}</tbody></table></div></section></div>}
        {tab === "subscribers" && <section className="admin-panel"><div className="admin-panel-title"><h2>邮件订阅名单</h2><div className="admin-panel-actions"><span>{filtered.subscribers.length} 位订阅用户</span><ExportLink type="subscribers" /></div></div><div className="admin-table-wrap"><table><thead><tr><th>邮箱</th><th>来源</th><th>订阅时间</th><th>状态</th></tr></thead><tbody>{filtered.subscribers.map((subscriber) => <tr key={subscriber.id}><td><b>{subscriber.email}</b></td><td>{subscriber.source === "homepage" ? "首页" : subscriber.source === "footer" ? "页脚" : subscriber.source}</td><td>{new Date(subscriber.subscribed_at).toLocaleString("zh-CN")}</td><td><select value={subscriber.status} onChange={(event) => act({ action:"update-subscriber-status", id:subscriber.id, status:event.target.value })}><option value="active">订阅中</option><option value="unsubscribed">已退订</option></select></td></tr>)}</tbody></table></div></section>}
      </>}
    </section>
    {(creating || editing) && <ProductModal editing={editing} onClose={() => { setCreating(false); setEditing(null); }} onSubmit={saveProduct} />}
    {importing && <ImportModal onClose={() => setImporting(false)} onImport={async (products) => { const ok = await act({ action: "bulk-import-products", products }); if (ok) setImporting(false); }} />}
    {selectedOrder && data && <OrderModal order={selectedOrder} items={data.orderItems.filter((item) => item.order_id === selectedOrder.id)} onClose={() => setSelectedOrder(null)} />}
    {selectedMember && data && <MemberModal member={selectedMember} orders={data.orders.filter((order) => order.member_id === selectedMember.id)} onClose={() => setSelectedMember(null)} />}
    {refundPayment && <RefundModal payment={refundPayment} onClose={() => setRefundPayment(null)} onSubmit={async (amountYuan, reason) => { const ok = await act({ action: "create-refund", paymentId: refundPayment.id, amountYuan, reason }); if (ok) setRefundPayment(null); }} />}
  </main>;
}

function ExportLink({ type }: { type: string }) { return <a className="admin-export" href={`/api/admin/export?type=${type}`}>导出 CSV</a>; }

function RevenueChart({ points }: { points: TrendPoint[] }) {
  const days = Array.from({ length: 30 }, (_, index) => { const date = new Date(); date.setDate(date.getDate() - 29 + index); return date.toISOString().slice(0, 10); });
  const values = days.map((day) => points.find((point) => point.day === day)?.revenue ?? 0);
  const max = Math.max(...values, 1);
  return <section className="admin-panel revenue-chart"><div className="admin-panel-title"><div><h2>近 30 天销售趋势</h2><p>按非取消订单统计</p></div><b>{formatCnyFromRub(values.reduce((sum, value) => sum + value, 0))}</b></div><div className="revenue-bars">{values.map((value, index) => <i key={days[index]} style={{ height: `${Math.max(3, value / max * 100)}%` }} title={`${days[index]} · ${formatCnyFromRub(value)}`} />)}</div><div className="revenue-axis"><span>{days[0].slice(5)}</span><span>{days[14].slice(5)}</span><span>{days[29].slice(5)}</span></div></section>;
}

function ImportModal({ onClose, onImport }: { onClose: () => void; onImport: (products: Record<string, unknown>[]) => Promise<void> }) {
  const [value, setValue] = useState('[\n  {\n    "slug": "product-slug",\n    "name": "中文商品名称",\n    "category": "彩妆",\n    "price": 118.8,\n    "stock": 0,\n    "inventoryVerified": false,\n    "image": "/assets/01.webp"\n  }\n]');
  const [error, setError] = useState("");
  function parse() {
    setError("");
    try { const parsed = JSON.parse(value); if (!Array.isArray(parsed)) throw new Error("JSON 顶层必须是数组"); void onImport(parsed); return; } catch (jsonError) {
      try { const lines = value.trim().split(/\r?\n/).filter(Boolean); const headers = lines[0].split(",").map((item) => item.trim()); if (!headers.includes("slug") || !headers.includes("name")) throw new Error("CSV 必须包含 slug 和 name 列"); const rows = lines.slice(1).map((line) => Object.fromEntries(line.split(",").map((cell,index) => [headers[index], cell.trim()]))); void onImport(rows); } catch { setError(jsonError instanceof Error ? jsonError.message : "无法解析导入内容"); }
    }
  }
  return <div className="admin-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-detail-card"><div className="admin-panel-title"><div><p>最多一次导入 200 件</p><h2>批量导入商品</h2></div><button onClick={onClose}>×</button></div><p className="admin-help">支持 JSON 数组或 CSV。已有相同 slug 的商品会更新，不会重复创建；price 与 oldPrice 均直接填写人民币元。</p><textarea className="admin-import-area" value={value} onChange={(event) => setValue(event.target.value)} rows={18} />{error && <p className="checkout-error">{error}</p>}<button className="admin-save" onClick={parse}>开始导入</button></section></div>;
}

function NotificationAdmin({ settings, templates, jobs, onAct }: { settings: NotificationSetting[]; templates: NotificationTemplate[]; jobs: NotificationJob[]; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  return <div className="admin-notification-stack">
    <section className="notification-settings-grid">{settings.map((setting) => <form className="notification-setting-card" key={setting.channel} onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "update-notification-setting", channel: setting.channel, enabled: values.enabled === "on", senderName: values.senderName, senderAddress: values.senderAddress }); }}><div className="payment-provider-title"><div><span>{setting.provider.toUpperCase()}</span><h2>{setting.display_name}</h2></div><label className="admin-switch"><input type="checkbox" name="enabled" defaultChecked={Boolean(setting.enabled)} /><i /></label></div><div className={`payment-config-state ${setting.configured ? "ready" : ""}`}><b>{setting.configured ? "配置完整，可发送通知" : "配置未完成，不会发送"}</b><span>服务器密钥 {setting.secretInstalled ? "已安装" : "未安装"}</span></div><label>发件名称<input name="senderName" defaultValue={setting.sender_name} /></label><label>{setting.channel === "email" ? "发件邮箱" : "短信签名 / Sender ID"}<input name="senderAddress" defaultValue={setting.sender_address} placeholder={setting.channel === "email" ? "notice@PUSY.CN" : "PUSY.CN"} /></label><p>{setting.channel === "email" ? "邮件通过 Resend 发送，API 密钥只保存在服务器环境变量。" : "短信通过独立 HTTP 网关适配器发送，可对接国内合规短信服务商。"}</p><button className="admin-save">保存渠道配置</button></form>)}</section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>消息模板</h2><p>支持变量：订单号、客户、金额、配送、礼品卡代码等</p></div></div><div className="notification-template-list">{templates.map((template) => <details key={template.key}><summary><div><b>{template.name}</b><small>{template.key}</small></div><span>{template.enabled ? "已启用" : "已停用"} ＋</span></summary><form onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "update-notification-template", key: template.key, enabled: values.enabled === "on", emailSubject: values.emailSubject, emailBody: values.emailBody, smsBody: values.smsBody }); }}><label className="notification-template-toggle"><input type="checkbox" name="enabled" defaultChecked={Boolean(template.enabled)} /> 启用此模板</label><label>邮件标题<input name="emailSubject" defaultValue={template.email_subject} /></label><label>邮件正文<textarea name="emailBody" defaultValue={template.email_body} rows={7} /></label><label>短信正文<textarea name="smsBody" defaultValue={template.sms_body} rows={3} maxLength={500} /></label><button className="admin-save">保存模板</button></form></details>)}</div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>发送记录</h2><p>{jobs.length} 条通知任务</p></div><button onClick={() => void onAct({ action: "process-notifications" })}>处理到期队列</button></div><div className="admin-table-wrap"><table><thead><tr><th>事件 / 接收人</th><th>渠道</th><th>模板</th><th>计划时间</th><th>状态</th><th>尝试</th><th>操作</th></tr></thead><tbody>{jobs.length ? jobs.map((job) => <tr key={job.id}><td><b>{job.entity_id}</b><small>{job.recipient}<br />{job.event_key}</small></td><td>{job.channel === "email" ? "邮件" : "短信"}</td><td>{templates.find((item) => item.key === job.template_key)?.name ?? job.template_key}</td><td>{new Date(job.scheduled_at).toLocaleString("zh-CN")}</td><td><NotificationStatus value={job.status} />{job.last_error && <small className="payment-row-error">{job.last_error}</small>}</td><td>{job.attempts}</td><td>{job.status !== "sent" && <button className="admin-text-button" onClick={() => void onAct({ action: "retry-notification", id: job.id })}>立即重试</button>}</td></tr>) : <tr><td colSpan={7} className="admin-empty">还没有消息通知记录</td></tr>}</tbody></table></div></section>
  </div>;
}

function NotificationStatus({ value }: { value: string }) { const labels: Record<string,string> = { queued: "待发送", failed: "发送失败", sent: "已发送", delivered: "已送达", bounced: "已退信", complained: "被投诉" }; return <span className={`payment-status status-${value}`}>{labels[value] ?? value}</span>; }

function ChinaRegionAdmin({ settings, providers, onOpenPayments }: { settings: ChinaRegionSettings; providers: PaymentProvider[]; onOpenPayments: () => void }) {
  const identityItems = [["中国区运营主体", settings.operatorName], ["统一社会信用代码", settings.unifiedSocialCreditCode], ["注册地址", settings.registeredAddress], ["客服电话", settings.customerServicePhone], ["客服邮箱", settings.supportEmail], ["隐私联系邮箱", settings.privacyEmail], ["ICP备案", settings.icpNumber], ["公安联网备案", settings.publicSecurityNumber]];
  const paymentsReady = providers.some((provider) => provider.enabled && provider.configured);
  return <div className="china-settings-stack">
    <section className="admin-panel china-readiness"><div className="admin-panel-title"><div><h2>中国区上线状态</h2><p>市场：中国大陆 · 语言：简体中文 · 时区：{settings.timeZone} · 货币：{settings.currency}</p></div><span className={`payment-status ${settings.complianceReady && paymentsReady ? "status-paid" : "status-pending"}`}>{settings.complianceReady && paymentsReady ? "基本配置完成" : "尚未满足上线条件"}</span></div><div className="china-check-grid"><article className={settings.complianceReady ? "ready" : "pending"}><b>{settings.complianceReady ? "✓" : "!"} 经营主体与备案</b><p>{settings.complianceReady ? "主体、联系方式与备案信息已配置。" : "仍有待补充信息，请通过服务器环境变量配置。"}</p></article><article className={paymentsReady ? "ready" : "pending"}><b>{paymentsReady ? "✓" : "!"} 中国区支付</b><p>{paymentsReady ? "至少一个支付渠道已启用并配置完整。" : "微信支付和支付宝均未达到可交易状态。"}</p></article><article className="ready"><b>✓ 中国区政策</b><p>隐私、Cookie、销售条款、配送和退换货页面已切换为中国区版本。</p></article></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>经营与备案信息</h2><p>以下内容会用于中国区法律公示；敏感配置不写入前端代码。</p></div><a href="/details" target="_blank">查看公示页</a></div><div className="china-settings-list">{identityItems.map(([label, value]) => <div key={label}><span>{label}</span><b className={value.startsWith("待") ? "pending" : ""}>{value}</b></div>)}</div><div className="admin-config-note"><b>配置方式</b><p>在运行环境中设置 CHINA_OPERATOR_NAME、CHINA_UNIFIED_SOCIAL_CREDIT_CODE、CHINA_REGISTERED_ADDRESS、CHINA_CUSTOMER_SERVICE_PHONE、CHINA_SUPPORT_EMAIL、CHINA_PRIVACY_EMAIL、CHINA_ICP_NUMBER 和 CHINA_PUBLIC_SECURITY_NUMBER。正式主体信息确认前不会用虚构资料填充。</p></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>支付渠道状态</h2><p>支付密钥由服务器环境管理，非管理员页面明文保存。</p></div><button onClick={onOpenPayments}>前往支付配置</button></div><div className="china-check-grid">{providers.map((provider) => <article className={provider.enabled && provider.configured ? "ready" : "pending"} key={provider.provider}><b>{provider.display_name}</b><p>{provider.enabled ? provider.configured ? "已启用，可发起真实交易。" : "已启用，但商户资料或服务器密钥不完整。" : "当前未启用。"}</p></article>)}</div></section>
  </div>;
}

function PaymentAdmin({ providers, payments, refunds, events, onAct, onRefund }: { providers: PaymentProvider[]; payments: AdminPayment[]; refunds: AdminRefund[]; events: PaymentEvent[]; onAct: (payload: Record<string, unknown>) => Promise<boolean>; onRefund: (payment: AdminPayment) => void }) {
  return <div className="admin-payment-stack">
    <section className="payment-provider-grid">{providers.map((provider) => <form className="payment-provider-card" key={provider.provider} onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "update-payment-provider", provider: provider.provider, enabled: values.enabled === "on", mode: values.mode, appId: values.appId, merchantId: values.merchantId, publicKeyId: values.publicKeyId, certificateSerial: values.certificateSerial }); }}>
      <div className="payment-provider-title"><div><span>{provider.provider === "wechat" ? "WECHAT PAY" : "ALIPAY"}</span><h2>{provider.display_name}</h2></div><label className="admin-switch"><input type="checkbox" name="enabled" defaultChecked={Boolean(provider.enabled)} /><i /></label></div>
      <div className={`payment-config-state ${provider.configured ? "ready" : ""}`}><b>{provider.configured ? "配置完整，可发起交易" : "配置未完成，前台不会扣款"}</b><span>私钥 {provider.secrets.privateKey ? "已安装" : "未安装"} · 公钥 {provider.secrets.publicKey ? "已安装" : "未安装"}{provider.provider === "wechat" ? ` · API v3 密钥 ${provider.secrets.apiV3Key ? "已安装" : "未安装"}` : ""}</span></div>
      <div className="payment-provider-form"><label>运行环境<select name="mode" defaultValue={provider.mode}><option value="production">正式环境</option>{provider.provider === "alipay" && <option value="sandbox">沙箱环境</option>}</select></label><label>应用 ID<input name="appId" defaultValue={provider.app_id} autoComplete="off" /></label><label>商户号<input name="merchantId" defaultValue={provider.merchant_id} autoComplete="off" /></label>{provider.provider === "wechat" && <><label>平台公钥 ID<input name="publicKeyId" defaultValue={provider.public_key_id} autoComplete="off" /></label><label>商户证书序列号<input name="certificateSerial" defaultValue={provider.certificate_serial} autoComplete="off" /></label></>}</div>
      <p>私钥、公钥和 API v3 密钥仅通过服务器环境变量配置，后台不会保存或回显。</p><button className="admin-save">保存渠道配置</button>
    </form>)}</section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>支付交易</h2><p>{payments.length} 笔记录</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>订单 / 客户</th><th>渠道</th><th>金额</th><th>支付状态</th><th>尝试</th><th>更新时间</th><th>操作</th></tr></thead><tbody>{payments.length ? payments.map((payment) => <tr key={payment.id}><td><b>{payment.order_id}</b><small>{payment.customer} · {payment.email}<br />{payment.merchant_trade_no}</small></td><td>{payment.provider === "wechat" ? "微信支付" : "支付宝"}</td><td>{(payment.amount_fen / 100).toFixed(2)} 元</td><td><PaymentStatus value={payment.status} />{payment.last_error && <small className="payment-row-error">{payment.last_error}</small>}</td><td>{payment.attempts}</td><td>{new Date(payment.updated_at).toLocaleString("zh-CN")}</td><td><button className="admin-text-button" onClick={() => void onAct({ action: "sync-payment", id: payment.id })}>同步</button>{payment.status === "failed" && <button className="admin-text-button" onClick={() => void onAct({ action: "retry-payment", orderId: payment.order_id, provider: payment.provider })}>重试</button>}{["paid","partially_refunded"].includes(payment.status) && <button className="admin-text-button danger" onClick={() => onRefund(payment)}>退款</button>}</td></tr>) : <tr><td colSpan={7} className="admin-empty">还没有支付交易</td></tr>}</tbody></table></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>退款记录</h2><p>{refunds.length} 笔记录</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>退款单 / 订单</th><th>渠道</th><th>金额</th><th>原因</th><th>状态</th><th>操作</th></tr></thead><tbody>{refunds.length ? refunds.map((refund) => <tr key={refund.id}><td><b>{refund.id}</b><small>{refund.order_id}<br />{refund.merchant_refund_no}</small></td><td>{refund.provider === "wechat" ? "微信支付" : "支付宝"}</td><td>{(refund.amount_fen / 100).toFixed(2)} 元</td><td>{refund.reason}{refund.last_error && <small className="payment-row-error">{refund.last_error}</small>}</td><td><PaymentStatus value={refund.status} /></td><td><button className="admin-text-button" onClick={() => void onAct({ action: "sync-refund", id: refund.id })}>同步</button>{refund.status === "failed" && <button className="admin-text-button" onClick={() => void onAct({ action: "retry-refund", id: refund.id })}>重试</button>}</td></tr>) : <tr><td colSpan={6} className="admin-empty">还没有退款记录</td></tr>}</tbody></table></div></section>
    <section className="admin-panel"><div className="admin-panel-title"><div><h2>回调审计</h2><p>最近 {events.length} 条已验签事件</p></div></div><div className="payment-event-list">{events.length ? events.map((event) => <article key={event.id}><div><b>{event.provider === "wechat" ? "微信支付" : "支付宝"} · {event.event_type}</b><small>{event.id}</small></div><PaymentStatus value={event.result} /><time>{new Date(event.created_at).toLocaleString("zh-CN")}</time>{event.message && <p>{event.message}</p>}</article>) : <p className="admin-empty">尚未收到支付回调</p>}</div></section>
  </div>;
}

function PaymentStatus({ value }: { value: string }) {
  const labels: Record<string, string> = { created: "已创建", pending: "待支付", paid: "已支付", failed: "失败", closed: "已关闭", refunding: "退款中", partially_refunded: "部分退款", refunded: "已退款", processing: "处理中", succeeded: "成功", processed: "已处理", rejected: "已拒绝", ignored: "已忽略" };
  return <span className={`payment-status status-${value}`}>{labels[value] ?? value}</span>;
}

function RefundModal({ payment, onClose, onSubmit }: { payment: AdminPayment; onClose: () => void; onSubmit: (amountYuan: number, reason: string) => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  return <div className="admin-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form onSubmit={async (event) => { event.preventDefault(); setBusy(true); const values = new FormData(event.currentTarget); await onSubmit(Number(values.get("amountYuan")), String(values.get("reason") ?? "")); setBusy(false); }}><div className="admin-panel-title"><div><p>订单 {payment.order_id}</p><h2>发起退款</h2></div><button type="button" onClick={onClose}>×</button></div><p className="admin-help">原支付金额 {(payment.amount_fen / 100).toFixed(2)} 元。系统会校验累计可退余额，并使用固定退款单号安全重试。</p><div className="admin-form-grid"><label>退款金额（元）<input name="amountYuan" type="number" min="0.01" max={(payment.amount_fen / 100).toFixed(2)} step="0.01" required /></label><label>退款原因<input name="reason" maxLength={80} required placeholder="例如：客户取消订单" /></label></div><button className="admin-save" disabled={busy}>{busy ? "正在提交退款…" : "确认发起退款"}</button></form></div>;
}

function OrderTable({ orders, onStatus, onOpen }: { orders: AdminOrder[]; onStatus: (id:string,status:string) => void; onOpen: (order:AdminOrder) => void }) { return <div className="admin-table-wrap"><table><thead><tr><th>订单号</th><th>客户</th><th>商品</th><th>金额</th><th>配送 / 支付</th><th>时间</th><th>状态</th></tr></thead><tbody>{orders.length ? orders.map((order) => <tr key={order.id}><td><button className="admin-order-link" onClick={() => onOpen(order)}>{order.id}</button></td><td>{order.customer}<small>{order.email}<br />{order.phone}</small></td><td>{order.item_count} 件</td><td>{formatCnyFromRub(order.total)}</td><td>{order.delivery}<small>{order.payment}</small></td><td>{new Date(order.created_at).toLocaleString("zh-CN")}</td><td><select value={order.status} onChange={(event) => onStatus(order.id,event.target.value)}>{["待付款","支付失败","待处理","已确认","配货中","已发货","已完成","退款中","部分退款","已退款","已取消"].map((status) => <option value={status} key={status}>{status}</option>)}</select></td></tr>) : <tr><td colSpan={7} className="admin-empty">还没有符合条件的订单</td></tr>}</tbody></table></div>; }

function ProductModal({ editing, onClose, onSubmit }: { editing: AdminProduct | null; onClose: () => void; onSubmit: (event:React.FormEvent<HTMLFormElement>) => void }) { return <div className="admin-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form onSubmit={onSubmit}><div className="admin-panel-title"><h2>{editing ? "编辑商品" : "新建商品"}</h2><button type="button" onClick={onClose}>×</button></div><div className="admin-form-grid"><label>商品名称<input name="name" defaultValue={editing?.name ?? emptyProduct.name} required /></label><label>链接标识<input name="slug" defaultValue={editing?.slug ?? emptyProduct.slug} required /></label><label>分类<input name="category" defaultValue={editing?.category ?? emptyProduct.category} required /></label><label>角标<input name="badge" defaultValue={editing?.badge ?? emptyProduct.badge} /></label><label>售价（元）<input name="price" type="number" min="0" step="0.01" defaultValue={storedToYuan(editing?.price)} required /></label><label>原价（元）<input name="oldPrice" type="number" min="0" step="0.01" defaultValue={storedToYuan(editing?.old_price)} /></label><label>库存数量<input name="stock" type="number" min="0" defaultValue={editing?.stock ?? emptyProduct.stock} required /></label><label className="inventory-check"><input name="inventoryVerified" type="checkbox" defaultChecked={Boolean(editing?.inventory_verified)} />库存数量已核验</label><label>状态<select name="status" defaultValue={editing?.status ?? emptyProduct.status}><option value="active">销售中</option><option value="archived">已下架</option></select></label><label>商品编号 / SKU<input name="sku" defaultValue={editing?.sku ?? emptyProduct.sku} /></label><label>规格容量<input name="volume" defaultValue={editing?.volume ?? emptyProduct.volume} placeholder="例如：110 毫升" /></label><label className="full">主图地址<input name="image" defaultValue={editing?.image ?? emptyProduct.image} required /></label><label className="full">备用图片地址<input name="imageAlt" defaultValue={editing?.image_alt ?? emptyProduct.image_alt} /></label><label className="full">商品说明<textarea name="description" defaultValue={editing?.description ?? emptyProduct.description} rows={4} /></label><label className="full">成分<textarea name="ingredients" defaultValue={editing?.ingredients ?? emptyProduct.ingredients} rows={4} /></label><label className="full">使用方法<textarea name="usage" defaultValue={editing?.usage ?? emptyProduct.usage} rows={4} /></label></div>{editing && !editing.inventory_verified && <p className="inventory-source-note">请填写本商城的实际库存数量，确认无误后勾选“库存数量已核验”。</p>}<button className="admin-save">保存商品</button></form></div>; }

function OrderModal({ order, items, onClose }: { order: AdminOrder; items: OrderItem[]; onClose: () => void }) { return <div className="admin-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-detail-card"><div className="admin-panel-title"><div><p>订单详情</p><h2>{order.id}</h2></div><button onClick={onClose}>×</button></div><div className="admin-detail-grid"><article><span>客户</span><b>{order.customer}</b><p>{order.email}<br />{order.phone}</p></article><article><span>配送</span><b>{order.delivery}</b><p>{order.address}</p></article><article><span>支付</span><b>{order.payment}</b><p>{order.status}</p></article></div><h3>商品明细</h3><div className="admin-order-items">{items.map((item) => <div key={item.id}><span>{item.product_name}<small>{item.product_slug}</small></span><b>× {item.quantity}</b><strong>{formatCnyFromRub(item.unit_price * item.quantity)}</strong></div>)}</div><div className="admin-detail-total"><span>订单合计</span><b>{formatCnyFromRub(order.total)}</b></div></section></div>; }

function MemberModal({ member, orders, onClose }: { member: AdminMember; orders: AdminOrder[]; onClose: () => void }) { return <div className="admin-modal" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><section className="admin-detail-card"><div className="admin-panel-title"><div><p>会员档案 #{member.id}</p><h2>{member.name}</h2></div><button onClick={onClose}>×</button></div><div className="admin-detail-grid"><article><span>联系方式</span><b>{member.email}</b><p>{member.phone}</p></article><article><span>累计订单</span><b>{member.total_orders} 笔</b><p>{formatCnyFromRub(member.total_spent)}</p></article><article><span>会员状态</span><b>{member.status === "vip" ? "VIP" : member.status === "blocked" ? "已停用" : "普通会员"}</b><p>加入于 {new Date(member.joined_at).toLocaleDateString("zh-CN")}</p></article></div><h3>订单历史</h3><div className="admin-member-orders">{orders.length ? orders.map((order) => <div key={order.id}><b>{order.id}</b><span>{new Date(order.created_at).toLocaleDateString("zh-CN")}</span><span>{order.status}</span><strong>{formatCnyFromRub(order.total)}</strong></div>) : <p>暂无订单</p>}</div></section></div>; }
