"use client";

import Image from "next/image";
import { useState } from "react";
import type { CommunityInsights, CommunityModerationPost, CommunityOperationsData, CommunityReport } from "./admin-types";
import { CommunityOperationsAdmin } from "./CommunityOperationsAdmin";

export type { CommunityInsights, CommunityModerationPost, CommunityReport } from "./admin-types";

const statusNames = { pending: "待审核", approved: "公开显示", rejected: "拒绝公开", hidden: "已隐藏" } as const;
const reportReasonNames = { spam: "垃圾或重复内容", abuse: "攻击、骚扰或不友善", misinformation: "虚假或误导信息", commercial: "未标注商业推广", other: "其他问题" } as const;
const reportStatusNames = { pending: "待处理", resolved: "已处理违规", dismissed: "已驳回" } as const;

function ModerationCard({ post, canManage, selected, onSelect, onAct }: { post: CommunityModerationPost; canManage: boolean; selected: boolean; onSelect: (id: string, selected: boolean) => void; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const [status, setStatus] = useState(post.status);
  const [reason, setReason] = useState(post.moderation_note || "");
  const [placement, setPlacement] = useState<"none" | "featured" | "pinned">(post.promotion_placement || "none");
  const [sortOrder, setSortOrder] = useState(post.promotion_rank);
  const [promotionNote, setPromotionNote] = useState(post.promotion_note || "");
  const [accountType, setAccountType] = useState(post.author_account_type);
  const [officialLabel, setOfficialLabel] = useState(post.author_official_label || "PÚSY 官方");
  const [creatorStatus, setCreatorStatus] = useState(post.creator_status);
  return <article className="community-moderation-card">
    <header>{canManage && <input type="checkbox" checked={selected} onChange={(event) => onSelect(post.id, event.target.checked)} aria-label={`选择 ${post.title || post.id}`} />}<div className="community-admin-author"><i>{post.author_name.slice(0, 1).toUpperCase()}</i><span><b>{post.author_name}{post.author_account_type === "official" ? ` · ${post.author_official_label || "官方"}` : ""}</b><small>{post.author_public_id} · 会员 #{post.member_id} · {post.creator_status === "restricted" ? "已限制" : "正常"}</small></span></div><div><em className={`community-status status-${post.status}`}>{statusNames[post.status]}</em><time>{new Date(post.created_at).toLocaleString("zh-CN")}</time></div></header>
    <div className={`community-admin-media count-${post.media_ids.length}`}>{post.media_ids.map((id, index) => <span key={id}><Image src={`/api/community/media/${id}`} alt={`待审社区图片 ${index + 1}`} fill sizes="(max-width: 900px) 50vw, 240px" unoptimized /></span>)}</div>
    <section><small>{post.id}</small>{post.campaign_title && <p className="community-admin-campaign">活动投稿：{post.campaign_title} · {post.campaign_entry_status === "qualified" ? "已入选" : post.campaign_entry_status === "rejected" ? "未入选" : "待评选"}</p>}{post.title && <h3>{post.title}</h3>}<p>{post.body}</p>{post.products.length > 0 && <div className="community-admin-products">{post.products.map((product) => <a href={`/products/${product.slug}`} target="_blank" rel="noopener noreferrer" key={product.slug}>{product.name}</a>)}</div>}<dl className="community-post-metrics"><div><dt>曝光</dt><dd>{post.impression_count}</dd></div><div><dt>商品点击</dt><dd>{post.product_click_count}</dd></div><div><dt>加购</dt><dd>{post.add_to_cart_count}</dd></div></dl></section>
    <footer>{canManage ? <><label>审核结果<select value={status} onChange={(event) => setStatus(event.target.value as CommunityModerationPost["status"])}><option value="pending">待审核</option><option value="approved">公开显示</option><option value="rejected">拒绝公开</option><option value="hidden">隐藏内容</option></select></label><label>审核说明<textarea value={reason} onChange={(event) => setReason(event.target.value)} maxLength={500} rows={3} placeholder={status === "rejected" ? "拒绝公开时必须填写，会员可见" : "选填，会员可在自己的主页查看"} /></label><button onClick={() => void onAct({ action: "update-community-post-status", id: post.id, status, reason })}>保存审核结果</button>{post.campaign_title && post.status === "approved" && <section className="community-promotion-editor"><h4>活动评选</h4><button onClick={() => void onAct({ action: "qualify-community-campaign-entry", id: post.id, qualified: true, note: "内容符合活动要求" })}>入选并发放活动积分</button><button onClick={() => void onAct({ action: "qualify-community-campaign-entry", id: post.id, qualified: false, note: "内容未达到本期活动要求" })}>标记未入选</button></section>}<section className="community-promotion-editor"><h4>创作者治理</h4><label>账号类型<select value={accountType} onChange={(event) => setAccountType(event.target.value as "member" | "official")}><option value="member">普通会员</option><option value="official">官方账号</option></select></label>{accountType === "official" && <label>官方标识<input value={officialLabel} maxLength={30} onChange={(event) => setOfficialLabel(event.target.value)} /></label>}<label>投稿资格<select value={creatorStatus} onChange={(event) => setCreatorStatus(event.target.value as "active" | "restricted")}><option value="active">正常</option><option value="restricted">限制投稿与奖励</option></select></label><button onClick={() => void onAct({ action: "update-community-creator", memberId: post.member_id, accountType, officialLabel, creatorStatus })}>保存创作者设置</button></section>{post.status === "approved" && <section className="community-promotion-editor"><h4>内容推荐</h4><label>展示位置<select value={placement} onChange={(event) => setPlacement(event.target.value as "none" | "featured" | "pinned")}><option value="none">普通内容</option><option value="featured">精选推荐</option><option value="pinned">社区置顶</option></select></label><label>推荐权重<input type="number" min={0} max={999} value={sortOrder} onChange={(event) => setSortOrder(Math.min(999, Math.max(0, Number(event.target.value))))} /></label><label>运营说明<textarea value={promotionNote} onChange={(event) => setPromotionNote(event.target.value)} maxLength={300} rows={2} placeholder="选填，仅后台可见" /></label><button onClick={() => void onAct({ action: "update-community-promotion", id: post.id, placement, sortOrder, note: promotionNote })}>保存推荐设置</button></section>}</> : <p>当前账号仅可查看社区审核队列。</p>}<a href={`/community/posts/${post.id}`} target="_blank" rel="noopener noreferrer">预览内容 ↗</a></footer>
  </article>;
}

function ReportCard({ report, canManage, onAct }: { report: CommunityReport; canManage: boolean; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const [decision, setDecision] = useState<"resolve" | "dismiss">(report.status === "dismissed" ? "dismiss" : "resolve");
  const [note, setNote] = useState(report.resolution_note || "");
  return <article className="community-report-card">
    <header><div><span>{report.entity_type === "post" ? "分享举报" : "评论举报"}</span><strong>{reportReasonNames[report.reason]}</strong></div><em className={`report-${report.status}`}>{reportStatusNames[report.status]}</em></header>
    <section><small>{report.id} · 举报人：{report.reporter_name}</small><h3>{report.target_author_name} 的{report.entity_type === "post" ? "分享" : "评论"}</h3><blockquote>{report.target_excerpt || "内容已不可见"}</blockquote>{report.detail && <p>举报说明：{report.detail}</p>}<a href={`/community/posts/${report.post_id}`} target="_blank" rel="noopener noreferrer">查看关联分享 ↗</a></section>
    <footer>{canManage ? <><label>处理结果<select value={decision} onChange={(event) => setDecision(event.target.value as "resolve" | "dismiss")}><option value="resolve">确认违规并隐藏内容</option><option value="dismiss">驳回举报</option></select></label><label>处理说明<textarea value={note} onChange={(event) => setNote(event.target.value)} maxLength={500} rows={3} placeholder={decision === "resolve" ? "确认违规时必须填写" : "选填"} /></label><button onClick={() => void onAct({ action: "update-community-report-status", id: report.id, decision, note })}>保存处理结果</button></> : <p>当前账号仅可查看举报队列。</p>}</footer>
  </article>;
}

export function CommunityAdmin({ posts, reports, insights, operations, canManage, onAct }: { posts: CommunityModerationPost[]; reports: CommunityReport[]; insights: CommunityInsights; operations: CommunityOperationsData; canManage: boolean; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const pending = posts.filter((post) => post.status === "pending").length;
  const pendingReports = reports.filter((report) => report.status === "pending").length;
  const [postFilter, setPostFilter] = useState("all");
  const [selectedPosts, setSelectedPosts] = useState<string[]>([]);
  const visiblePosts = postFilter === "all" ? posts : posts.filter((post) => post.status === postFilter);
  const selectPost = (id: string, selected: boolean) => setSelectedPosts((current) => selected ? [...new Set([...current, id])] : current.filter((item) => item !== id));
  return <div className="community-admin-workspace">
    <section className="community-insights"><article><span>近 30 天曝光</span><b>{insights.summary.impressions.toLocaleString("zh-CN")}</b><small>{insights.summary.measuredPosts} 篇内容产生数据</small></article><article><span>商品点击</span><b>{insights.summary.productClicks.toLocaleString("zh-CN")}</b><small>{insights.summary.impressions ? `${(insights.summary.productClicks / insights.summary.impressions * 100).toFixed(1)}% 点击率` : "等待曝光数据"}</small></article><article><span>社区加购</span><b>{insights.summary.addToCarts.toLocaleString("zh-CN")}</b><small>{insights.summary.productClicks ? `${(insights.summary.addToCarts / insights.summary.productClicks * 100).toFixed(1)}% 点击后加购` : "等待商品点击"}</small></article></section>
    {insights.products.length > 0 && <section className="admin-panel community-top-products"><div className="admin-panel-title"><div><h2>社区带动商品</h2><p>近 30 天按加购与点击排序。</p></div></div><div>{insights.products.map((product) => <a href={`/products/${product.productSlug}`} target="_blank" rel="noopener noreferrer" key={product.productSlug}><span><b>{product.productName}</b><small>{product.productClicks} 次点击</small></span><strong>{product.addToCarts} 次加购</strong></a>)}</div></section>}
    {canManage && <CampaignCreator onAct={onAct} />}
    <CommunityOperationsAdmin data={operations} canManage={canManage} onAct={onAct} />
    <section className="admin-panel community-admin-panel"><div className="admin-panel-title"><div><h2>用户举报</h2><p>核查会员举报；确认违规会隐藏对应分享或评论，并写入举报事件与后台操作日志。</p></div><span>{pendingReports} 条待处理</span></div><div className="community-report-list">{reports.length ? reports.map((report) => <ReportCard report={report} canManage={canManage} onAct={onAct} key={report.id} />) : <p className="admin-empty">还没有用户举报</p>}</div></section>
    <section className="admin-panel community-admin-panel"><div className="admin-panel-title"><div><h2>社区内容审核</h2><p>审核会员图文与公开昵称；所有状态变更同时进入社区事件和后台操作日志。</p></div><span>{pending} 条待审核</span></div><div className="community-bulk-toolbar"><select value={postFilter} onChange={(event) => setPostFilter(event.target.value)}><option value="all">全部状态</option><option value="pending">待审核</option><option value="approved">已公开</option><option value="rejected">未通过</option><option value="hidden">已隐藏</option></select>{canManage && <><button onClick={() => setSelectedPosts(visiblePosts.map((post) => post.id))}>全选当前</button><button disabled={!selectedPosts.length} onClick={() => void onAct({ action: "bulk-update-community-post-status", ids: selectedPosts, status: "approved", reason: "批量审核通过" }).then((ok) => { if (ok) setSelectedPosts([]); })}>批量通过</button><button disabled={!selectedPosts.length} onClick={() => void onAct({ action: "bulk-update-community-post-status", ids: selectedPosts, status: "hidden", reason: "批量隐藏处理" }).then((ok) => { if (ok) setSelectedPosts([]); })}>批量隐藏</button></>}</div><div className="community-moderation-list">{visiblePosts.length ? visiblePosts.map((post) => <ModerationCard post={post} selected={selectedPosts.includes(post.id)} onSelect={selectPost} canManage={canManage} onAct={onAct} key={post.id} />) : <p className="admin-empty">当前筛选条件下没有投稿</p>}</div></section>
  </div>;
}

function CampaignCreator({ onAct }: { onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const [title, setTitle] = useState("");
  const [slug, setSlug] = useState("");
  const [description, setDescription] = useState("");
  const [topicSlug, setTopicSlug] = useState("");
  const [rewardPoints, setRewardPoints] = useState(50);
  return <section className="admin-panel community-campaign-admin"><div className="admin-panel-title"><div><h2>主题活动</h2><p>创建活动后会显示在创作中心和发布页；活动积分需在内容审核通过后单独评选发放。</p></div></div><div><label>活动名称<input value={title} maxLength={80} onChange={(event) => { setTitle(event.target.value); if (!slug) setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")); }} /></label><label>稳定标识<input value={slug} maxLength={80} onChange={(event) => setSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))} placeholder="summer-color" /></label><label>绑定话题标识<input value={topicSlug} maxLength={40} onChange={(event) => setTopicSlug(event.target.value.toLowerCase().replace(/[^a-z0-9-]/g, ""))} placeholder="lip-diary" /></label><label>入选积分<input type="number" min={0} max={500} value={rewardPoints} onChange={(event) => setRewardPoints(Number(event.target.value))} /></label><label className="wide">活动说明<textarea rows={3} value={description} maxLength={500} onChange={(event) => setDescription(event.target.value)} /></label><button disabled={!title || slug.length < 2} onClick={() => void onAct({ action: "create-community-campaign", title, slug, description, topicSlug, rewardPoints, status: "active", rules: "内容需原创、真实且通过社区审核；同一内容不可重复参与。" })}>创建并启用活动</button></div></section>;
}
