"use client";

import { useMemo, useState } from "react";
import type { CommunityAdminTopic, CommunityOperationsData } from "./admin-types";

type Act = (payload: Record<string, unknown>) => Promise<boolean>;

function TopicForm({ topic, onAct, disabled }: { topic?: CommunityAdminTopic; onAct: Act; disabled: boolean }) {
  return <form className="community-ops-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "save-community-topic", id: topic?.id, featured: new FormData(form).get("featured") === "on", ...values }).then((ok) => { if (ok && !topic) form.reset(); }); }}>
    <input name="name" defaultValue={topic?.name} placeholder="话题名称" required maxLength={30} disabled={disabled} />
    <input name="slug" defaultValue={topic?.slug} placeholder="stable-topic-slug" required maxLength={40} readOnly={Boolean(topic)} disabled={disabled} />
    <input name="description" defaultValue={topic?.description} placeholder="话题说明" maxLength={240} disabled={disabled} />
    <select name="status" defaultValue={topic?.status ?? "draft"} disabled={disabled}><option value="draft">草稿</option><option value="active">启用</option><option value="archived">归档</option></select>
    <input name="sortOrder" type="number" min={0} max={999} defaultValue={topic?.sort_order ?? 0} aria-label="排序权重" disabled={disabled} />
    <label><input name="featured" type="checkbox" defaultChecked={Boolean(topic?.featured)} disabled={disabled} />推荐</label><button disabled={disabled}>{topic ? "保存" : "新增话题"}</button>
  </form>;
}

function BroadcastForm({ onAct }: { onAct: Act }) {
  return <form className="community-broadcast-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "send-community-broadcast", ...values }).then((ok) => { if (ok) form.reset(); }); }}><label>通知标题<input name="title" required maxLength={80} /></label><label>接收范围<select name="target"><option value="all">全部社区会员</option><option value="active">近 30 天活跃会员</option><option value="creators">公开创作者</option></select></label><label className="wide">通知内容<textarea name="body" required maxLength={500} rows={3} /></label><button>发送站内通知</button></form>;
}

export function CommunityOperationsAdmin({ data, canManage, onAct }: { data: CommunityOperationsData; canManage: boolean; onAct: Act }) {
  const [view, setView] = useState<"comments" | "members" | "topics" | "campaigns" | "broadcasts">("comments");
  const [query, setQuery] = useState("");
  const normalized = query.trim().toLowerCase();
  const comments = useMemo(() => data.comments.filter((item) => !normalized || `${item.author_name} ${item.body} ${item.post_title} ${item.status}`.toLowerCase().includes(normalized)), [data.comments, normalized]);
  const members = useMemo(() => data.members.filter((item) => !normalized || `${item.display_name} ${item.public_id} ${item.creator_status} ${item.comment_status}`.toLowerCase().includes(normalized)), [data.members, normalized]);
  return <section className="admin-panel community-operations-admin"><div className="admin-panel-title"><div><h2>社区运营中台</h2><p>管理评论、会员关系、话题、活动和定向通知。</p></div></div>
    <div className="community-retention-grid"><article><span>今日活跃</span><b>{data.metrics.dau}</b></article><article><span>7 日活跃</span><b>{data.metrics.wau}</b></article><article><span>30 日活跃</span><b>{data.metrics.mau}</b></article><article><span>7 日回访率</span><b>{data.metrics.retention7d}%</b><small>{data.metrics.returning7d} 人多日回访</small></article><article><span>30 日互动</span><b>{data.metrics.interactions30d}</b></article></div>
    <div className="community-ops-toolbar"><nav>{(["comments", "members", "topics", "campaigns", "broadcasts"] as const).map((item) => <button className={view === item ? "active" : ""} onClick={() => setView(item)} key={item}>{({ comments: "评论队列", members: "会员治理", topics: "话题管理", campaigns: "活动管理", broadcasts: "运营通知" })[item]}</button>)}</nav><input type="search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="搜索当前队列" /></div>
    {view === "comments" && <div className="admin-table-wrap"><table><thead><tr><th>评论人</th><th>关联内容</th><th>评论</th><th>互动/举报</th><th>状态</th><th>操作</th></tr></thead><tbody>{comments.map((item) => <tr key={item.id}><td><b>{item.author_name}</b><small>{item.author_public_id}</small></td><td><a href={`/community/posts/${item.post_id}`} target="_blank">{item.post_title || item.post_id}</a></td><td>{item.body}</td><td>{item.like_count} 赞 · {item.pending_reports} 举报</td><td>{item.status === "visible" ? "公开" : item.status === "hidden" ? "已隐藏" : "已删除"}</td><td>{canManage && item.status !== "deleted" && <button onClick={() => void onAct({ action: "update-community-comment-status", id: item.id, status: item.status === "visible" ? "hidden" : "visible" })}>{item.status === "visible" ? "隐藏" : "恢复"}</button>}</td></tr>)}</tbody></table></div>}
    {view === "members" && <div className="community-member-ops-list">{members.map((member) => <article key={member.member_id}><header><div><b>{member.display_name}</b><small>{member.public_id} · {member.follower_count} 关注者</small></div><span>{member.violation_count} 次违规</span></header><p>{member.post_count} 篇分享 · {member.comment_count} 条评论 · 投稿 {member.creator_status === "active" ? "正常" : "受限"} · 评论 {member.comment_status === "active" ? "正常" : "受限"}</p>{member.restriction_note && <aside>{member.restriction_note}</aside>}{canManage && <div><button onClick={() => void onAct({ action: "update-community-member-governance", memberId: member.member_id, creatorStatus: "restricted", commentStatus: "restricted", restrictedUntil: new Date(Date.now() + 7 * 864e5).toISOString(), note: "社区运营限制 7 天" })}>限制 7 天</button><button onClick={() => void onAct({ action: "update-community-member-governance", memberId: member.member_id, creatorStatus: "active", commentStatus: "active", restrictedUntil: "", note: "" })}>解除限制</button><a href={`/community/members/${member.public_id}`} target="_blank">查看主页</a></div>}</article>)}</div>}
    {view === "topics" && <div className="community-topic-ops"><TopicForm onAct={onAct} disabled={!canManage} />{data.topics.map((topic) => <TopicForm topic={topic} onAct={onAct} disabled={!canManage} key={topic.id} />)}</div>}
    {view === "campaigns" && <div className="community-campaign-ops-list">{data.campaigns.map((campaign) => <form key={campaign.id} onSubmit={(event) => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); void onAct({ action: "save-community-campaign", id: campaign.id, ...values }); }}><header><div><b>{campaign.title}</b><small>{campaign.slug} · {campaign.entry_count} 篇投稿</small></div><span>{campaign.status === "active" ? "进行中" : campaign.status === "ended" ? "已结束" : "草稿"}</span></header><input name="title" defaultValue={campaign.title} required maxLength={80} /><input name="description" defaultValue={campaign.description} maxLength={500} /><input name="rewardPoints" type="number" min={0} max={500} defaultValue={campaign.reward_points} /><select name="status" defaultValue={campaign.status}><option value="draft">草稿</option><option value="active">进行中</option><option value="ended">已结束</option></select><label>开始<input name="startsAt" type="datetime-local" defaultValue={campaign.starts_at?.slice(0, 16) ?? ""} /></label><label>结束<input name="endsAt" type="datetime-local" defaultValue={campaign.ends_at?.slice(0, 16) ?? ""} /></label><button disabled={!canManage}>保存活动</button></form>)}</div>}
    {view === "broadcasts" && <div>{canManage && <BroadcastForm onAct={onAct} />}<div className="community-broadcast-history">{data.broadcasts.map((item) => <article key={item.id}><b>{item.title}</b><p>{item.body}</p><small>{item.target} · {item.recipient_count} 位接收者 · {new Date(item.created_at).toLocaleString("zh-CN")}</small></article>)}</div></div>}
  </section>;
}
