"use client";

import { formatCnyFromRub } from "../data/products";
import type { GrowthData } from "./admin-types";

export type { AutomationRun, CouponAssignment, GrowthData, GrowthMember, GrowthSegment, GrowthTag } from "./admin-types";

const tierNames: Record<string, string> = { bronze: "新锐", silver: "银卡", gold: "金卡", diamond: "钻石" };

export function GrowthAdmin({ data, onAct }: { data: GrowthData; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  return <div className="growth-admin-stack">
    <section className="stat-grid growth-stat-grid"><article><span>会员总数</span><b>{data.stats.total_members ?? 0}</b></article><article><span>银卡会员</span><b>{data.stats.silver_members ?? 0}</b></article><article><span>金卡 / 钻石</span><b>{(data.stats.gold_members ?? 0) + (data.stats.diamond_members ?? 0)}</b></article><article><span>待使用积分</span><b>{data.stats.points_outstanding ?? 0}</b></article></section>

    <section className="admin-panel"><div className="admin-panel-title"><div><h2>定向发放优惠券</h2><p>按会员等级、客户标签或已保存分组精准发放；未订阅营销通知的会员仍可在账户中查看，但不会收到推广消息。</p></div></div><form className="growth-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "issue-targeted-coupon", ...values }).then((ok) => { if (ok) form.reset(); }); }}>
      <label>优惠码<input name="code" required placeholder="例如 GOLD20" /></label><label>优惠方式<select name="kind"><option value="percent">百分比折扣</option><option value="fixed">固定金额（元）</option></select></label><label>优惠额度<input name="value" type="number" min="1" step="0.01" required /></label><label>最低消费（元）<input name="minimum" type="number" min="0" step="0.01" defaultValue="0" /></label><label>会员等级<select name="tier"><option value="all">全部等级</option><option value="bronze">新锐会员</option><option value="silver">银卡会员</option><option value="gold">金卡会员</option><option value="diamond">钻石会员</option></select></label><label>客户标签<select name="tagId"><option value="0">不限标签</option>{data.tags.map((tag) => <option value={tag.id} key={tag.id}>{tag.name}（{tag.member_count}）</option>)}</select></label><label>已保存分组<select name="segmentId"><option value="0">不使用分组</option>{data.segments.map((segment) => <option value={segment.id} key={segment.id}>{segment.name}</option>)}</select></label><label>有效期至<input name="endsAt" type="datetime-local" /></label><button className="admin-primary">确认定向发放</button>
    </form></section>

    <div className="growth-two-column"><section className="admin-panel"><div className="admin-panel-title"><div><h2>客户标签</h2><p>用于人工识别与定向营销</p></div></div><form className="growth-inline-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "create-customer-tag", ...values }).then((ok) => { if (ok) form.reset(); }); }}><input name="name" placeholder="标签名称" required maxLength={40} /><input name="color" type="color" defaultValue="#ef398b" /><input name="description" placeholder="标签说明" maxLength={160} /><button>新增标签</button></form><div className="growth-tag-list">{data.tags.map((tag) => <span key={tag.id} style={{ borderColor: tag.color }}><i style={{ background: tag.color }} />{tag.name}<b>{tag.member_count}</b></span>)}</div></section>
      <section className="admin-panel"><div className="admin-panel-title"><div><h2>客户分组</h2><p>保存可重复使用的筛选条件</p></div></div><form className="growth-form compact" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "create-customer-segment", ...values }).then((ok) => { if (ok) form.reset(); }); }}><label>分组名称<input name="name" required /></label><label>等级<select name="tier"><option value="all">全部等级</option>{Object.entries(tierNames).map(([key, name]) => <option value={key} key={key}>{name}</option>)}</select></label><label>标签<select name="tagId"><option value="0">不限</option>{data.tags.map((tag) => <option value={tag.id} key={tag.id}>{tag.name}</option>)}</select></label><label>最低累计消费（元）<input name="minSpentYuan" type="number" min="0" defaultValue="0" /></label><label className="wide">说明<input name="description" /></label><button>保存分组</button></form><div className="segment-list">{data.segments.map((segment) => <div key={segment.id}><b>{segment.name}</b><span>{segment.description || "已保存筛选条件"}</span></div>)}</div></section></div>

    <section className="admin-panel"><div className="admin-panel-title"><div><h2>会员等级、积分与标签</h2><p>消费积分由支付和退款自动同步；人工调整会完整写入积分账本。</p></div></div><div className="admin-table-wrap"><table><thead><tr><th>会员</th><th>等级 / 积分</th><th>消费</th><th>标签</th><th>添加标签</th><th>人工调分</th></tr></thead><tbody>{data.members.map((member) => { const tagIds = member.tag_ids ? member.tag_ids.split(",").map(Number) : []; return <tr key={member.id}><td><b>{member.name}</b><small>{member.email}<br />#{member.id}</small></td><td>{tierNames[member.tier] ?? member.tier}<small>可用 {member.points_balance} · 累计 {member.lifetime_points}</small></td><td>{formatCnyFromRub(member.total_spent)}<small>{member.total_orders} 笔订单</small></td><td><div className="member-tags">{tagIds.map((id) => { const tag = data.tags.find((item) => item.id === id); return tag ? <button title="点击移除" key={id} style={{ borderColor: tag.color }} onClick={() => void onAct({ action: "assign-member-tag", memberId: member.id, tagId: id, assigned: false })}>{tag.name} ×</button> : null; })}</div></td><td><form className="table-inline-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const tagId = Number(new FormData(form).get("tagId")); if (tagId) void onAct({ action: "assign-member-tag", memberId: member.id, tagId }); }}><select name="tagId"><option value="0">选择标签</option>{data.tags.filter((tag) => !tagIds.includes(tag.id)).map((tag) => <option value={tag.id} key={tag.id}>{tag.name}</option>)}</select><button>添加</button></form></td><td><form className="table-inline-form" onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "adjust-member-points", memberId: member.id, ...values }).then((ok) => { if (ok) form.reset(); }); }}><input name="points" type="number" placeholder="±积分" required /><input name="reason" placeholder="原因" required /><button>确认</button></form></td></tr>; })}</tbody></table></div></section>

    <section className="admin-panel"><div className="admin-panel-title"><div><h2>自动化提醒</h2><p>未付款、复购和新品提醒会根据订单状态及会员授权生成通知任务。</p></div><button onClick={() => void onAct({ action: "run-growth-automations" })}>立即运行</button></div><div className="admin-table-wrap"><table><thead><tr><th>任务</th><th>开始时间</th><th>匹配</th><th>入队</th><th>状态</th></tr></thead><tbody>{data.automationRuns.length ? data.automationRuns.map((run) => <tr key={run.id}><td><b>{run.automation_key === "payment-reminder" ? "未付款提醒" : run.automation_key === "repurchase-reminder" ? "复购提醒" : "新品通知"}</b><small>{run.id}</small></td><td>{new Date(run.started_at).toLocaleString("zh-CN")}</td><td>{run.matched_count}</td><td>{run.queued_count}</td><td>{run.status === "completed" ? "已完成" : run.status === "failed" ? `失败：${run.error_text}` : "运行中"}</td></tr>) : <tr><td colSpan={5} className="admin-empty">尚未运行增长自动化任务</td></tr>}</tbody></table></div></section>
  </div>;
}
