export type SupportThread = {
  id: string;
  mailbox: string;
  subject: string;
  customer_email: string;
  customer_name: string;
  customer_phone?: string;
  customer_wechat?: string;
  member_id?: number;
  member_name?: string;
  order_id?: string;
  order_status?: string;
  return_id?: string;
  return_status?: string;
  status: "unread" | "open" | "pending" | "resolved";
  priority: "low" | "normal" | "high" | "urgent";
  assigned_to?: string;
  assigned_admin_id?: string;
  due_at?: string;
  first_response_due_at?: string;
  resolution_due_at?: string;
  first_responded_at?: string;
  resolved_at?: string;
  reopened_count: number;
  member_total_orders?: number;
  member_total_spent?: number;
  member_points_balance?: number;
  member_lifetime_points?: number;
  member_tier?: string;
  member_status?: string;
  member_tags?: string;
  starred: number;
  archived_at?: string;
  deleted_at?: string;
  last_message_at: string;
  created_at: string;
};

export type SupportMessage = {
  id: string;
  thread_id: string;
  direction: "inbound" | "outbound" | "system";
  source: string;
  provider_email_id?: string;
  from_email: string;
  to_email: string;
  subject: string;
  text_body: string;
  attachments_json: string;
  created_at: string;
};

export type ReturnEvent = { id: string; return_id: string; event_type: string; from_status?: string; to_status?: string; note: string; actor: string; created_at: string };
export type Attachment = { id: string; filename: string; content_type?: string; size?: number };
export type SupportReceiving = { domain: string; configured: boolean };
export type CannedReply = { id: number; title: string; content: string };
export type SupportAgent = { id: string; email: string; display_name: string; role: string };
export type SupportCustomerOrder = { id: string; member_id?: number; customer: string; email: string; total: number; status: string; delivery: string; payment: string; carrier_name?: string; tracking_number?: string; shipment_status?: string; created_at: string };
export type SupportCustomerReturn = { id: string; order_id: string; member_id?: number; email: string; reason: string; request_type: string; status: string; refund_id?: string; created_at: string };
export type SupportViewer = { id: string; email: string; displayName: string };
export type Folder = "inbox" | "unread" | "handling" | "unassigned" | "due-soon" | "overdue" | "starred" | "archived" | "trash";
export type ManageOperation = "mark-read" | "mark-unread" | "star" | "unstar" | "archive" | "unarchive" | "trash" | "restore" | "delete-permanent";
