"use client";

import { formatCnyFromRub } from "../data/products";
import type { Invoice, Order, OrderItem, Shipment, ShipmentEvent } from "./account-types";

export function OrderList({ orders, items, shipments = [], shipmentEvents = [], onAct }: { orders: Order[]; items: OrderItem[]; shipments?: Shipment[]; shipmentEvents?: ShipmentEvent[]; onAct?: (payload: Record<string, unknown>) => Promise<boolean> }) { return <div className="member-order-list">{orders.map((order) => { const shipment = shipments.find((item) => item.order_id === order.id); const events = shipmentEvents.filter((item) => item.shipment_id === shipment?.id); const cancellable = ["待付款", "支付失败", "待处理", "已确认", "配货中"].includes(order.status); return <details key={order.id}><summary><span><b>{order.id}</b><small>{new Date(order.created_at).toLocaleString("zh-CN")}</small></span><span>{order.item_count} 件商品</span><strong>{formatCnyFromRub(order.total)}</strong><em>{order.status}</em></summary><div className="member-order-detail"><p>{order.delivery} · {order.payment}</p><p>{order.address}</p>{items.filter((item) => item.order_id === order.id).map((item) => <div key={item.id}><span>{item.product_name}<small>数量 {item.quantity}</small></span><b>{formatCnyFromRub(item.unit_price * item.quantity)}</b></div>)}{order.discount > 0 && <p className="member-discount">订单优惠 −{formatCnyFromRub(order.discount)}</p>}{shipment && <section className="member-shipment"><b>{shipment.carrier_name} · {shipment.tracking_number}</b><span>{shipment.status}</span>{shipment.tracking_url && <a href={shipment.tracking_url} target="_blank" rel="noopener noreferrer">查询物流 →</a>}{events.slice(0, 5).map((event) => <p key={event.id}><time>{new Date(event.event_time).toLocaleString("zh-CN")}</time> {event.status} · {event.description}{event.location ? `（${event.location}）` : ""}</p>)}</section>}{cancellable && onAct && <button className="member-order-cancel" onClick={() => { const reason = window.prompt("请输入取消订单原因", "不再需要"); if (reason) void onAct({ action: "cancel-order", orderId: order.id, reason }); }}>取消订单</button>}{["已发货", "已完成", "部分退款"].includes(order.status) && <a className="member-order-return" href={`/contact?category=${encodeURIComponent("售后问题")}&orderId=${encodeURIComponent(order.id)}`}>申请售后</a>}</div></details>; })}</div>; }

const invoiceStatusLabels: Record<string, string> = { pending: "待审核", processing: "开票中", issued: "已开具", rejected: "已驳回", cancelled: "已取消" };

export function InvoicePanel({ invoices, orders, email, name, onAct }: { invoices: Invoice[]; orders: Order[]; email: string; name: string; onAct: (payload: Record<string, unknown>) => Promise<boolean> }) {
  const requestedOrders = new Set(invoices.filter((item) => !["rejected", "cancelled"].includes(item.status)).map((item) => item.order_id));
  const eligible = orders.filter((order) => !["待付款", "支付失败", "已取消", "已退款"].includes(order.status) && !requestedOrders.has(order.id));
  return <section className="member-section invoice-member-section"><div className="member-section-title"><div><p>电子发票将发送至申请邮箱</p><h2>发票管理</h2></div><span>{invoices.length} 条申请</span></div>
    {invoices.length > 0 && <div className="member-invoice-list">{invoices.map((invoice) => <article key={invoice.id}><div><span>{invoice.invoice_type === "company" ? "企业发票" : "个人发票"}</span><b>{invoice.title}</b><small>{invoice.id} · 订单 {invoice.order_id}</small></div><strong>{formatCnyFromRub(invoice.amount)}</strong><em className={`invoice-status status-${invoice.status}`}>{invoiceStatusLabels[invoice.status] ?? invoice.status}</em>{invoice.rejection_reason && <p>原因：{invoice.rejection_reason}</p>}{invoice.status === "issued" && invoice.file_url && <a href={invoice.file_url} target="_blank" rel="noopener noreferrer">下载电子发票 →</a>}</article>)}</div>}
    <div className="invoice-request-list"><h3>可申请开票的订单</h3>{eligible.length ? eligible.map((order) => <details key={order.id}><summary><span><b>{order.id}</b><small>{new Date(order.created_at).toLocaleDateString("zh-CN")} · {order.status}</small></span><strong>{formatCnyFromRub(order.total)}</strong><em>申请开票</em></summary><form onSubmit={(event) => { event.preventDefault(); const form = event.currentTarget; const values = Object.fromEntries(new FormData(form).entries()); void onAct({ action: "request-invoice", orderId: order.id, ...values }).then((ok) => { if (ok) form.reset(); }); }}><label>发票类型<select name="invoiceType" defaultValue="personal"><option value="personal">个人发票</option><option value="company">企业发票</option></select></label><label>发票抬头<input name="title" defaultValue={name} maxLength={120} required /></label><label>企业税号<input name="taxNumber" maxLength={30} placeholder="个人发票可不填" /></label><label>接收邮箱<input name="recipientEmail" type="email" defaultValue={email} maxLength={160} required /></label><button>提交发票申请</button></form></details>) : <p className="member-empty-inline">当前没有新的可开票订单</p>}</div>
  </section>;
}
