BEGIN;

CREATE TABLE IF NOT EXISTS products (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  image TEXT NOT NULL,
  image_alt TEXT,
  badge TEXT,
  price INTEGER NOT NULL,
  old_price INTEGER,
  stock INTEGER NOT NULL DEFAULT 0,
  low_stock_threshold INTEGER NOT NULL DEFAULT 10,
  inventory_verified INTEGER NOT NULL DEFAULT 0,
  images_json TEXT NOT NULL DEFAULT '[]',
  variants_json TEXT NOT NULL DEFAULT '[]',
  sku TEXT,
  volume TEXT,
  ingredients TEXT,
  usage TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS product_categories (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  parent_id INTEGER REFERENCES product_categories(id) ON DELETE SET NULL,
  description TEXT NOT NULL DEFAULT '',
  sort_order INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS product_categories_parent_sort_idx ON product_categories (parent_id, sort_order, id);

INSERT INTO product_categories (name, slug, sort_order) VALUES
  ('彩妆', 'makiyazh', 10), ('眉妆', 'brows', 20), ('护肤', 'uhod', 30),
  ('面部护理', 'face', 40), ('身体护理', 'uhod-1', 50), ('头发护理', 'hair', 60),
  ('套装', 'nabory', 70), ('神秘礼盒', 'sekretnye-boksy', 80), ('家居', 'dlya-doma', 90),
  ('配件', 'accessories', 100), ('礼品卡', 'gift-card', 110)
ON CONFLICT (name) DO NOTHING;

INSERT INTO product_categories (name, slug, sort_order)
SELECT DISTINCT p.category, 'legacy-' || SUBSTRING(MD5(p.category) FROM 1 FOR 12), 900
FROM products p
WHERE NOT EXISTS (SELECT 1 FROM product_categories c WHERE c.name = p.category)
ON CONFLICT DO NOTHING;

ALTER TABLE products ADD COLUMN IF NOT EXISTS category_id INTEGER REFERENCES product_categories(id) ON DELETE RESTRICT;
UPDATE products p SET category_id = c.id FROM product_categories c WHERE p.category_id IS NULL AND c.name = p.category;
CREATE INDEX IF NOT EXISTS products_category_id_idx ON products (category_id, status, id);

CREATE TABLE IF NOT EXISTS members (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  phone TEXT NOT NULL DEFAULT '',
  email_verified INTEGER NOT NULL DEFAULT 0,
  phone_verified INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  total_orders INTEGER NOT NULL DEFAULT 0,
  total_spent INTEGER NOT NULL DEFAULT 0,
  points_balance INTEGER NOT NULL DEFAULT 0,
  lifetime_points INTEGER NOT NULL DEFAULT 0,
  tier TEXT NOT NULL DEFAULT 'bronze',
  joined_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_profiles (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  nickname TEXT NOT NULL DEFAULT '',
  gender TEXT NOT NULL DEFAULT '',
  birthday TEXT NOT NULL DEFAULT '',
  wechat TEXT NOT NULL DEFAULT '',
  province TEXT NOT NULL DEFAULT '',
  city TEXT NOT NULL DEFAULT '',
  occupation TEXT NOT NULL DEFAULT '',
  skin_type TEXT NOT NULL DEFAULT '',
  skin_concerns TEXT NOT NULL DEFAULT '[]',
  preferred_categories TEXT NOT NULL DEFAULT '[]',
  bio TEXT NOT NULL DEFAULT '',
  email_marketing INTEGER NOT NULL DEFAULT 0,
  sms_marketing INTEGER NOT NULL DEFAULT 0,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_addresses (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id),
  label TEXT NOT NULL DEFAULT '家',
  recipient TEXT NOT NULL,
  phone TEXT NOT NULL,
  province TEXT NOT NULL,
  city TEXT NOT NULL,
  district TEXT NOT NULL DEFAULT '',
  detail TEXT NOT NULL,
  postcode TEXT NOT NULL DEFAULT '',
  is_default INTEGER NOT NULL DEFAULT 0,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS orders (
  id TEXT PRIMARY KEY,
  member_id INTEGER REFERENCES members(id),
  customer TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  address TEXT NOT NULL,
  delivery TEXT NOT NULL,
  payment TEXT NOT NULL,
  total INTEGER NOT NULL,
  discount INTEGER NOT NULL DEFAULT 0,
  coupon_code TEXT,
  payment_token_hash TEXT NOT NULL DEFAULT '',
  reservation_expires_at TEXT,
  resources_released INTEGER NOT NULL DEFAULT 0,
  resources_committed INTEGER NOT NULL DEFAULT 0,
  points_awarded INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT '待付款',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE orders ADD COLUMN IF NOT EXISTS reservation_expires_at TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS resources_released INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS resources_committed INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS points_awarded INTEGER NOT NULL DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_reason TEXT NOT NULL DEFAULT '';
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancel_requested_at TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS cancelled_at TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS inventory_restocked INTEGER NOT NULL DEFAULT 0;
ALTER TABLE products ADD COLUMN IF NOT EXISTS low_stock_threshold INTEGER NOT NULL DEFAULT 10;

CREATE TABLE IF NOT EXISTS member_verification_codes (
  id TEXT PRIMARY KEY,
  target TEXT NOT NULL,
  purpose TEXT NOT NULL,
  code_hash TEXT NOT NULL,
  attempts INTEGER NOT NULL DEFAULT 0,
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS member_verification_target_idx ON member_verification_codes (target, created_at);

CREATE TABLE IF NOT EXISTS member_sessions (
  token_hash TEXT PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  expires_at TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS member_sessions_member_idx ON member_sessions (member_id);

CREATE TABLE IF NOT EXISTS member_social_accounts (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('wechat', 'alipay')),
  provider_user_id TEXT NOT NULL,
  provider_union_id TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, provider),
  UNIQUE (provider, provider_user_id)
);

CREATE UNIQUE INDEX IF NOT EXISTS member_social_accounts_union_idx
  ON member_social_accounts (provider, provider_union_id)
  WHERE provider_union_id != '';

CREATE TABLE IF NOT EXISTS member_oauth_states (
  state_hash TEXT PRIMARY KEY,
  member_id INTEGER REFERENCES members(id) ON DELETE CASCADE,
  provider TEXT NOT NULL CHECK (provider IN ('wechat', 'alipay')),
  mode TEXT NOT NULL CHECK (mode IN ('bind', 'login')),
  return_to TEXT NOT NULL DEFAULT '/account',
  expires_at TEXT NOT NULL,
  consumed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS member_oauth_states_expiry_idx ON member_oauth_states (expires_at);

CREATE TABLE IF NOT EXISTS rate_limits (
  key TEXT PRIMARY KEY,
  request_count INTEGER NOT NULL DEFAULT 0,
  window_started_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS order_items (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id),
  product_slug TEXT NOT NULL,
  product_name TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  unit_price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS subscribers (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  source TEXT NOT NULL DEFAULT 'website',
  status TEXT NOT NULL DEFAULT 'active',
  subscribed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS retail_partnerships (
  id TEXT PRIMARY KEY,
  contact_name TEXT NOT NULL,
  phone TEXT NOT NULL,
  company TEXT NOT NULL,
  city TEXT NOT NULL,
  cooperation_type TEXT NOT NULL,
  wechat TEXT NOT NULL DEFAULT '',
  email TEXT NOT NULL DEFAULT '',
  proposal TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '待联系',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS coupons (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  kind TEXT NOT NULL DEFAULT 'percent',
  value INTEGER NOT NULL,
  minimum INTEGER NOT NULL DEFAULT 0,
  usage_limit INTEGER NOT NULL DEFAULT 0,
  used_count INTEGER NOT NULL DEFAULT 0,
  status TEXT NOT NULL DEFAULT 'active',
  assignment_mode TEXT NOT NULL DEFAULT 'public',
  starts_at TEXT,
  ends_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE members ADD COLUMN IF NOT EXISTS points_balance INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS lifetime_points INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS tier TEXT NOT NULL DEFAULT 'bronze';
ALTER TABLE coupons ADD COLUMN IF NOT EXISTS assignment_mode TEXT NOT NULL DEFAULT 'public';

CREATE TABLE IF NOT EXISTS member_points_ledger (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  points INTEGER NOT NULL,
  balance_after INTEGER NOT NULL,
  reason TEXT NOT NULL,
  reference_type TEXT NOT NULL DEFAULT '',
  reference_id TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, reference_type, reference_id)
);

CREATE INDEX IF NOT EXISTS member_points_ledger_member_idx ON member_points_ledger (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS coupon_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  coupon_id INTEGER NOT NULL REFERENCES coupons(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'available',
  assigned_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  used_at TEXT,
  order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  UNIQUE (coupon_id, member_id)
);

CREATE INDEX IF NOT EXISTS coupon_assignments_member_idx ON coupon_assignments (member_id, status, assigned_at DESC);

CREATE TABLE IF NOT EXISTS member_task_completions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  task_key TEXT NOT NULL,
  period_key TEXT NOT NULL DEFAULT 'lifetime',
  points INTEGER NOT NULL DEFAULT 0,
  reference_id TEXT NOT NULL DEFAULT '',
  metadata_json TEXT NOT NULL DEFAULT '{}',
  completed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, task_key, period_key)
);

CREATE INDEX IF NOT EXISTS member_task_completions_member_idx ON member_task_completions (member_id, completed_at DESC);

CREATE TABLE IF NOT EXISTS member_referral_codes (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  code TEXT NOT NULL UNIQUE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_referrals (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  referred_member_id INTEGER NOT NULL UNIQUE REFERENCES members(id) ON DELETE CASCADE,
  referral_code TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'registered' CHECK (status IN ('registered', 'rewarded', 'invalid')),
  qualifying_order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  registered_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  rewarded_at TEXT,
  CHECK (referrer_member_id <> referred_member_id)
);

CREATE INDEX IF NOT EXISTS member_referrals_referrer_idx ON member_referrals (referrer_member_id, status, registered_at DESC);

CREATE TABLE IF NOT EXISTS member_benefit_grants (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  benefit_key TEXT NOT NULL,
  benefit_year INTEGER NOT NULL,
  coupon_id INTEGER REFERENCES coupons(id) ON DELETE SET NULL,
  metadata_json TEXT NOT NULL DEFAULT '{}',
  granted_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, benefit_key, benefit_year)
);

CREATE INDEX IF NOT EXISTS member_benefit_grants_member_idx ON member_benefit_grants (member_id, granted_at DESC);

CREATE TABLE IF NOT EXISTS customer_tags (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  color TEXT NOT NULL DEFAULT '#ef398b',
  description TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_tag_assignments (
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  tag_id INTEGER NOT NULL REFERENCES customer_tags(id) ON DELETE CASCADE,
  assigned_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (member_id, tag_id)
);

CREATE TABLE IF NOT EXISTS customer_segments (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  description TEXT NOT NULL DEFAULT '',
  filter_json TEXT NOT NULL DEFAULT '{}',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS member_product_alerts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  product_slug TEXT NOT NULL,
  alert_type TEXT NOT NULL,
  target_price INTEGER,
  last_notified_at TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (member_id, product_slug, alert_type)
);

CREATE INDEX IF NOT EXISTS member_product_alerts_product_idx ON member_product_alerts (product_slug, alert_type, status);

CREATE TABLE IF NOT EXISTS product_price_history (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_slug TEXT NOT NULL,
  old_price INTEGER NOT NULL,
  new_price INTEGER NOT NULL,
  changed_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS growth_automation_runs (
  id TEXT PRIMARY KEY,
  automation_key TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'running',
  matched_count INTEGER NOT NULL DEFAULT 0,
  queued_count INTEGER NOT NULL DEFAULT 0,
  error_text TEXT NOT NULL DEFAULT '',
  started_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  finished_at TEXT
);

CREATE INDEX IF NOT EXISTS growth_automation_runs_key_idx ON growth_automation_runs (automation_key, started_at DESC);

CREATE TABLE IF NOT EXISTS returns (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id),
  email TEXT NOT NULL,
  reason TEXT NOT NULL,
  details TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT '待审核',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS gift_cards (
  code TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id),
  initial_balance INTEGER NOT NULL,
  balance INTEGER NOT NULL,
  recipient_name TEXT NOT NULL DEFAULT '',
  recipient_email TEXT NOT NULL DEFAULT '',
  message TEXT NOT NULL DEFAULT '',
  delivery_date TEXT,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS payment_providers (
  provider TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 0,
  mode TEXT NOT NULL DEFAULT 'production',
  app_id TEXT NOT NULL DEFAULT '',
  merchant_id TEXT NOT NULL DEFAULT '',
  public_key_id TEXT NOT NULL DEFAULT '',
  certificate_serial TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

INSERT INTO payment_providers (provider, display_name, enabled, mode) VALUES
  ('wechat', '微信支付', 0, 'production'),
  ('alipay', '支付宝', 0, 'production')
ON CONFLICT (provider) DO NOTHING;

CREATE TABLE IF NOT EXISTS payments (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL REFERENCES orders(id),
  provider TEXT NOT NULL,
  merchant_trade_no TEXT NOT NULL UNIQUE,
  provider_transaction_id TEXT,
  amount_fen INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'created',
  checkout_url TEXT,
  code_url TEXT,
  attempts INTEGER NOT NULL DEFAULT 0,
  next_retry_at TEXT,
  last_error TEXT,
  paid_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS payment_events (
  id TEXT PRIMARY KEY,
  payment_id TEXT REFERENCES payments(id),
  provider TEXT NOT NULL,
  event_type TEXT NOT NULL,
  payload_digest TEXT NOT NULL,
  verified INTEGER NOT NULL DEFAULT 0,
  result TEXT NOT NULL,
  message TEXT NOT NULL DEFAULT '',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS refunds (
  id TEXT PRIMARY KEY,
  payment_id TEXT NOT NULL REFERENCES payments(id),
  order_id TEXT NOT NULL REFERENCES orders(id),
  provider TEXT NOT NULL,
  merchant_refund_no TEXT NOT NULL UNIQUE,
  provider_refund_id TEXT,
  amount_fen INTEGER NOT NULL,
  reason TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  attempts INTEGER NOT NULL DEFAULT 0,
  next_retry_at TEXT,
  last_error TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS inventory_movements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_slug TEXT NOT NULL,
  order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  movement_type TEXT NOT NULL,
  quantity INTEGER NOT NULL,
  stock_after INTEGER NOT NULL,
  reference_id TEXT NOT NULL,
  actor TEXT NOT NULL DEFAULT 'system',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (product_slug, movement_type, reference_id)
);

CREATE TABLE IF NOT EXISTS shipments (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
  carrier_code TEXT NOT NULL,
  carrier_name TEXT NOT NULL,
  tracking_number TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT '已发货',
  tracking_url TEXT NOT NULL DEFAULT '',
  shipped_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  delivered_at TEXT,
  last_synced_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS shipment_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  shipment_id TEXT NOT NULL REFERENCES shipments(id) ON DELETE CASCADE,
  event_time TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  status TEXT NOT NULL,
  description TEXT NOT NULL,
  location TEXT NOT NULL DEFAULT '',
  source TEXT NOT NULL DEFAULT 'admin',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS inventory_movements_order_idx ON inventory_movements (order_id, created_at DESC);
CREATE INDEX IF NOT EXISTS inventory_movements_product_idx ON inventory_movements (product_slug, created_at DESC);
CREATE INDEX IF NOT EXISTS shipments_tracking_idx ON shipments (tracking_number);
CREATE INDEX IF NOT EXISTS shipment_events_shipment_idx ON shipment_events (shipment_id, event_time DESC);

CREATE TABLE IF NOT EXISTS notification_settings (
  channel TEXT PRIMARY KEY,
  display_name TEXT NOT NULL,
  enabled INTEGER NOT NULL DEFAULT 0,
  provider TEXT NOT NULL,
  sender_name TEXT NOT NULL DEFAULT 'PUSY.CN',
  sender_address TEXT NOT NULL DEFAULT '',
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS notification_templates (
  key TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  email_subject TEXT NOT NULL DEFAULT '',
  email_body TEXT NOT NULL DEFAULT '',
  sms_body TEXT NOT NULL DEFAULT '',
  enabled INTEGER NOT NULL DEFAULT 1,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS notification_jobs (
  id TEXT PRIMARY KEY,
  event_key TEXT NOT NULL,
  entity_type TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  template_key TEXT NOT NULL REFERENCES notification_templates(key),
  channel TEXT NOT NULL,
  recipient TEXT NOT NULL,
  payload_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0,
  scheduled_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  next_retry_at TEXT,
  provider_message_id TEXT,
  last_error TEXT,
  sent_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS notification_delivery_events (
  id TEXT PRIMARY KEY,
  provider_message_id TEXT NOT NULL,
  event_type TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS product_reviews (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_slug TEXT NOT NULL,
  member_id INTEGER REFERENCES members(id),
  reviewer_name TEXT NOT NULL,
  rating INTEGER NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  verified_purchase INTEGER NOT NULL DEFAULT 0,
  images_json TEXT NOT NULL DEFAULT '[]',
  status TEXT NOT NULL DEFAULT 'pending',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE product_reviews ADD COLUMN IF NOT EXISTS images_json TEXT NOT NULL DEFAULT '[]';

CREATE TABLE IF NOT EXISTS site_content (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS content_revisions (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  snapshot_json TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft',
  publish_at TEXT,
  published_at TEXT,
  created_by TEXT NOT NULL DEFAULT 'system',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS content_revisions_status_idx ON content_revisions (status, publish_at, created_at DESC);

INSERT INTO site_content (key, value) VALUES
  ('show_announcement', '1'),
  ('hero_cta_label', '立即探索'),
  ('hero_cta_url', '/catalog/products'),
  ('hero2_eyebrow', 'PÚSY 神秘礼盒'),
  ('hero2_title', '装下这个夏天\n需要的一切'),
  ('hero2_cta_label', '了解更多'),
  ('hero2_cta_url', '/catalog/sekretnye-boksy'),
  ('show_featured', '1'),
  ('featured_subtitle', '从当季新品开始，找到你的下一件日常心动。'),
  ('featured_cta_label', '查看全部'),
  ('show_categories', '1'),
  ('categories_title', '按心情探索'),
  ('category_1_label', '彩妆'),
  ('category_1_url', '/catalog/makiyazh'),
  ('category_2_label', '护肤'),
  ('category_2_url', '/catalog/uhod'),
  ('category_3_label', '家居'),
  ('category_3_url', '/catalog/dlya-doma'),
  ('show_reels', '1'),
  ('reels_title', '你与 PÚSY'),
  ('reels_subtitle', '真实灵感、使用方式与热门单品。'),
  ('show_newsletter', '1'),
  ('newsletter_title', '订阅邮件，立享 9 折'),
  ('newsletter_success', '订阅成功，欢迎加入 PÚSY CLUB。')
ON CONFLICT (key) DO NOTHING;

CREATE UNIQUE INDEX IF NOT EXISTS product_reviews_member_product_idx ON product_reviews (product_slug, member_id) WHERE member_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS support_threads (
  id TEXT PRIMARY KEY,
  mailbox TEXT NOT NULL DEFAULT 'service',
  subject TEXT NOT NULL,
  customer_email TEXT NOT NULL,
  customer_name TEXT NOT NULL DEFAULT '',
  customer_phone TEXT NOT NULL DEFAULT '',
  customer_wechat TEXT NOT NULL DEFAULT '',
  member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  order_id TEXT REFERENCES orders(id) ON DELETE SET NULL,
  return_id TEXT REFERENCES returns(id) ON DELETE SET NULL,
  status TEXT NOT NULL DEFAULT 'unread',
  priority TEXT NOT NULL DEFAULT 'normal',
  assigned_to TEXT,
  assigned_admin_id TEXT,
  starred SMALLINT NOT NULL DEFAULT 0,
  archived_at TEXT,
  deleted_at TEXT,
  first_response_due_at TEXT,
  resolution_due_at TEXT,
  first_responded_at TEXT,
  resolved_at TEXT,
  reopened_count INTEGER NOT NULL DEFAULT 0,
  last_message_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS support_messages (
  id TEXT PRIMARY KEY,
  thread_id TEXT NOT NULL REFERENCES support_threads(id) ON DELETE CASCADE,
  direction TEXT NOT NULL,
  source TEXT NOT NULL DEFAULT 'email',
  provider_email_id TEXT UNIQUE,
  provider_message_id TEXT,
  from_email TEXT NOT NULL,
  to_email TEXT NOT NULL,
  subject TEXT NOT NULL DEFAULT '',
  text_body TEXT NOT NULL DEFAULT '',
  html_body TEXT NOT NULL DEFAULT '',
  headers_json TEXT NOT NULL DEFAULT '{}',
  attachments_json TEXT NOT NULL DEFAULT '[]',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE returns ADD COLUMN IF NOT EXISTS support_thread_id TEXT REFERENCES support_threads(id) ON DELETE SET NULL;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS attachments_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS request_type TEXT NOT NULL DEFAULT 'refund';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS items_json TEXT NOT NULL DEFAULT '[]';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS requested_amount_fen INTEGER;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS resolution TEXT NOT NULL DEFAULT '';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS refund_id TEXT REFERENCES refunds(id) ON DELETE SET NULL;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS return_carrier TEXT NOT NULL DEFAULT '';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS return_tracking_number TEXT NOT NULL DEFAULT '';
ALTER TABLE returns ADD COLUMN IF NOT EXISTS reviewed_at TEXT;
ALTER TABLE returns ADD COLUMN IF NOT EXISTS completed_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS starred SMALLINT NOT NULL DEFAULT 0;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS archived_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS deleted_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS customer_phone TEXT NOT NULL DEFAULT '';
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS customer_wechat TEXT NOT NULL DEFAULT '';
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS assigned_admin_id TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS first_response_due_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS resolution_due_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS first_responded_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS resolved_at TEXT;
ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS reopened_count INTEGER NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS return_events (
  id TEXT PRIMARY KEY,
  return_id TEXT NOT NULL REFERENCES returns(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  from_status TEXT,
  to_status TEXT,
  note TEXT NOT NULL DEFAULT '',
  actor TEXT NOT NULL DEFAULT 'system',
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS support_threads_status_idx ON support_threads (status, last_message_at DESC);
CREATE INDEX IF NOT EXISTS support_threads_customer_idx ON support_threads (customer_email, last_message_at DESC);
CREATE INDEX IF NOT EXISTS support_threads_phone_idx ON support_threads (customer_phone, last_message_at DESC);
CREATE INDEX IF NOT EXISTS support_threads_order_idx ON support_threads (order_id);
CREATE INDEX IF NOT EXISTS support_threads_folder_idx ON support_threads (deleted_at, archived_at, status, last_message_at DESC);
CREATE INDEX IF NOT EXISTS support_messages_thread_idx ON support_messages (thread_id, created_at);
CREATE INDEX IF NOT EXISTS return_events_return_idx ON return_events (return_id, created_at);

CREATE TABLE IF NOT EXISTS invoices (
  id TEXT PRIMARY KEY,
  order_id TEXT NOT NULL UNIQUE REFERENCES orders(id) ON DELETE RESTRICT,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE RESTRICT,
  invoice_type TEXT NOT NULL DEFAULT 'personal',
  title TEXT NOT NULL,
  tax_number TEXT NOT NULL DEFAULT '',
  recipient_email TEXT NOT NULL,
  amount INTEGER NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending',
  invoice_number TEXT NOT NULL DEFAULT '',
  file_url TEXT NOT NULL DEFAULT '',
  rejection_reason TEXT NOT NULL DEFAULT '',
  admin_note TEXT NOT NULL DEFAULT '',
  requested_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  issued_at TEXT,
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE support_threads ADD COLUMN IF NOT EXISTS due_at TEXT;

CREATE TABLE IF NOT EXISTS support_canned_replies (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL UNIQUE,
  content TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS invoices_member_idx ON invoices (member_id, requested_at DESC);
CREATE INDEX IF NOT EXISTS invoices_status_idx ON invoices (status, requested_at DESC);
CREATE INDEX IF NOT EXISTS support_threads_due_idx ON support_threads (due_at, status);
CREATE INDEX IF NOT EXISTS support_threads_assignee_idx ON support_threads (assigned_admin_id, status, last_message_at DESC);
CREATE INDEX IF NOT EXISTS support_threads_first_response_sla_idx ON support_threads (first_response_due_at, status);
CREATE INDEX IF NOT EXISTS support_threads_resolution_sla_idx ON support_threads (resolution_due_at, status);

CREATE TABLE IF NOT EXISTS admin_users (
  id TEXT PRIMARY KEY,
  email TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  role TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'active',
  password_hash TEXT NOT NULL,
  password_salt TEXT NOT NULL,
  session_version INTEGER NOT NULL DEFAULT 0,
  last_login_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS admin_users_status_idx ON admin_users (status, role);

ALTER TABLE admin_users ADD COLUMN IF NOT EXISTS session_version INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS email_verified INTEGER NOT NULL DEFAULT 0;
ALTER TABLE members ADD COLUMN IF NOT EXISTS phone_verified INTEGER NOT NULL DEFAULT 0;
UPDATE members SET email_verified = 1 WHERE email <> '' AND email_verified = 0;
CREATE UNIQUE INDEX IF NOT EXISTS members_phone_unique_idx ON members ((regexp_replace(phone, '[[:space:]-]', '', 'g'))) WHERE phone <> '';

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  admin_id TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  actor_role TEXT NOT NULL,
  action TEXT NOT NULL,
  entity_id TEXT NOT NULL DEFAULT '',
  summary TEXT NOT NULL DEFAULT '',
  request_ip TEXT NOT NULL DEFAULT '',
  outcome TEXT NOT NULL DEFAULT 'attempted',
  error_text TEXT NOT NULL DEFAULT '',
  completed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

ALTER TABLE admin_audit_logs ADD COLUMN IF NOT EXISTS outcome TEXT NOT NULL DEFAULT 'attempted';
ALTER TABLE admin_audit_logs ADD COLUMN IF NOT EXISTS error_text TEXT NOT NULL DEFAULT '';
ALTER TABLE admin_audit_logs ADD COLUMN IF NOT EXISTS completed_at TEXT;

CREATE INDEX IF NOT EXISTS admin_audit_logs_created_idx ON admin_audit_logs (created_at DESC);
CREATE INDEX IF NOT EXISTS admin_audit_logs_actor_idx ON admin_audit_logs (actor_email, created_at DESC);

INSERT INTO notification_templates (key, name, email_subject, email_body, sms_body, enabled) VALUES
  ('order_confirmed', '支付成功通知', '订单 {{orderId}} 支付成功', '你好 {{customer}}，订单 {{orderId}} 已支付成功，实付 {{amount}}。我们正在为你准备商品。', 'PUSY.CN：订单 {{orderId}} 已支付成功。', 1),
  ('order_shipped', '发货通知', '订单 {{orderId}} 已发货', '你好 {{customer}}，订单 {{orderId}} 已通过 {{carrier}} 发出，物流单号 {{trackingNumber}}。查询物流：{{trackingUrl}}', 'PUSY.CN：订单 {{orderId}} 已发货，{{carrier}} {{trackingNumber}}。', 1),
  ('refund_completed', '退款完成通知', '订单 {{orderId}} 退款已完成', '你好 {{customer}}，订单 {{orderId}} 的 {{refundStatus}} 已完成，退款金额 {{refundAmount}}。到账时间以支付渠道为准。', 'PUSY.CN：订单 {{orderId}} 退款 {{refundAmount}} 已完成。', 1),
  ('order_cancelled', '订单取消通知', '订单 {{orderId}} 已取消', '你好 {{customer}}，订单 {{orderId}} 已取消。原因：{{reason}}。如已支付，退款将按原支付渠道退回。', 'PUSY.CN：订单 {{orderId}} 已取消。', 1),
  ('return_updated', '售后进度通知', '售后单 {{returnId}} 状态更新', '你好 {{customer}}，订单 {{orderId}} 的售后单 {{returnId}} 已更新为“{{status}}”。{{note}}', 'PUSY.CN：售后单 {{returnId}} 已更新为 {{status}}。', 1),
  ('low_stock_alert', '低库存提醒', '库存预警：{{productName}}', '商品 {{productName}}（{{productSlug}}）当前库存 {{stock}} 件，已达到预警阈值 {{threshold}} 件，请及时补货。', '', 1),
  ('payment_reminder', '未付款订单提醒', '你的 PUSY.CN 订单 {{orderId}} 即将释放', '你好 {{customer}}，订单 {{orderId}} 尚未支付，金额为 {{amount}} 元。库存将在 {{expiresAt}} 后释放，如需购买请尽快完成支付。', 'PUSY.CN：订单 {{orderId}} 尚未支付，请在 {{expiresAt}} 前完成支付。', 1),
  ('repurchase_reminder', '复购提醒', '{{productName}} 可能快用完了', '你好 {{customer}}，距你购买 {{productName}} 已有一段时间。现在回购，可继续享受熟悉的使用体验：{{productUrl}}', 'PUSY.CN：你购买的 {{productName}} 可能快用完了，欢迎回购。', 1),
  ('new_product', '新品通知', 'PUSY.CN 新品：{{productName}}', '你好 {{customer}}，新品 {{productName}} 已上架。查看详情：{{productUrl}}', 'PUSY.CN 新品 {{productName}} 已上架。', 1),
  ('product_restock', '补货通知', '{{productName}} 已补货', '你好 {{customer}}，你关注的 {{productName}} 已经补货，现在可以购买：{{productUrl}}', 'PUSY.CN：你关注的 {{productName}} 已补货。', 1),
  ('price_drop', '降价通知', '{{productName}} 已降价', '你好 {{customer}}，你关注的 {{productName}} 已从 {{oldPrice}} 元降至 {{newPrice}} 元：{{productUrl}}', 'PUSY.CN：{{productName}} 已降至 {{newPrice}} 元。', 1),
  ('targeted_coupon', '专属优惠券', '你的 PUSY.CN 专属优惠券：{{couponCode}}', '你好 {{customer}}，我们为你准备了专属优惠券 {{couponCode}}。优惠内容：{{benefit}}，使用条件：{{condition}}。有效期至 {{endsAt}}。', 'PUSY.CN：专属优惠券 {{couponCode}} 已到账，有效期至 {{endsAt}}。', 1),
  ('gift_card_sent', '电子礼品卡发送通知', '{{senderName}} 送你一张 PUSY.CN 电子礼品卡', '你好 {{recipientName}}，{{senderName}} 送你一张 {{amount}} 的 PUSY.CN 电子礼品卡。礼品卡号：{{giftCode}}。祝福：{{message}}。结账时输入卡号即可使用，请妥善保管。', '', 1)
ON CONFLICT (key) DO NOTHING;

CREATE TABLE IF NOT EXISTS community_profiles (
  member_id INTEGER PRIMARY KEY REFERENCES members(id) ON DELETE CASCADE,
  public_id TEXT NOT NULL UNIQUE,
  display_name TEXT NOT NULL,
  bio TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'hidden')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS community_posts (
  id TEXT PRIMARY KEY,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  client_request_id TEXT NOT NULL,
  title TEXT NOT NULL DEFAULT '',
  body TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'hidden')),
  moderation_note TEXT NOT NULL DEFAULT '',
  moderated_by TEXT,
  moderated_at TEXT,
  published_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE UNIQUE INDEX IF NOT EXISTS community_posts_member_request_idx ON community_posts (member_id, client_request_id);
CREATE INDEX IF NOT EXISTS community_posts_feed_idx ON community_posts (status, published_at DESC, created_at DESC);
CREATE INDEX IF NOT EXISTS community_posts_member_idx ON community_posts (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_media (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0 AND position < 4),
  mime_type TEXT NOT NULL CHECK (mime_type IN ('image/jpeg', 'image/png', 'image/webp')),
  byte_size INTEGER NOT NULL CHECK (byte_size > 0 AND byte_size <= 450000),
  bytes BYTEA NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (post_id, position)
);

CREATE INDEX IF NOT EXISTS community_post_media_post_idx ON community_post_media (post_id, position);

CREATE TABLE IF NOT EXISTS community_moderation_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  reason TEXT NOT NULL DEFAULT '',
  admin_id TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_moderation_events_post_idx ON community_moderation_events (post_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_follows (
  follower_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  followed_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (follower_member_id, followed_member_id),
  CHECK (follower_member_id <> followed_member_id)
);

CREATE INDEX IF NOT EXISTS community_follows_followed_idx ON community_follows (followed_member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_topics (
  id TEXT PRIMARY KEY,
  slug TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL,
  description TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'active', 'archived')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE TABLE IF NOT EXISTS community_post_topics (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  topic_id TEXT NOT NULL REFERENCES community_topics(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, topic_id)
);

CREATE INDEX IF NOT EXISTS community_post_topics_topic_idx ON community_post_topics (topic_id, created_at DESC);

INSERT INTO community_topics (id, slug, name, description, status)
VALUES
  ('TPC-DAILYMAKEUP01', 'daily-makeup', '今日妆容', '记录今天的色彩、光泽与妆容灵感。', 'active'),
  ('TPC-LIPDIARY0001', 'lip-diary', '唇色日记', '分享真实唇色、质地和使用场景。', 'active'),
  ('TPC-EMPTIES00001', 'real-empties', '真实空瓶', '用完之后再说感受，让选择更有依据。', 'active'),
  ('TPC-BODYCARE0001', 'body-care', '身体护理', '身体护理、香气与日常仪式。', 'active'),
  ('TPC-HAIRIDEAS001', 'hair-inspiration', '发丝灵感', '发型、护理与发丝状态记录。', 'active')
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  status = 'active',
  updated_at = CURRENT_TIMESTAMP::TEXT;

CREATE TABLE IF NOT EXISTS community_notifications (
  id TEXT PRIMARY KEY,
  recipient_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  event_key TEXT NOT NULL,
  event_type TEXT NOT NULL,
  actor_member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  entity_type TEXT NOT NULL DEFAULT 'post',
  entity_id TEXT NOT NULL DEFAULT '',
  post_id TEXT REFERENCES community_posts(id) ON DELETE CASCADE,
  payload_json TEXT NOT NULL DEFAULT '{}',
  read_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (recipient_member_id, event_key)
);

CREATE INDEX IF NOT EXISTS community_notifications_member_idx ON community_notifications (recipient_member_id, read_at, created_at DESC);
CREATE INDEX IF NOT EXISTS community_notifications_unread_idx ON community_notifications (recipient_member_id, created_at DESC) WHERE read_at IS NULL;

CREATE TABLE IF NOT EXISTS community_post_likes (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, member_id)
);

CREATE INDEX IF NOT EXISTS community_post_likes_member_idx ON community_post_likes (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_bookmarks (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, member_id)
);

CREATE INDEX IF NOT EXISTS community_post_bookmarks_member_idx ON community_post_bookmarks (member_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_comments (
  id TEXT PRIMARY KEY,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  parent_comment_id TEXT REFERENCES community_comments(id) ON DELETE SET NULL,
  body TEXT NOT NULL CHECK (char_length(body) BETWEEN 2 AND 500),
  status TEXT NOT NULL DEFAULT 'visible' CHECK (status IN ('visible', 'hidden', 'deleted')),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_comments_post_idx ON community_comments (post_id, status, created_at ASC);
CREATE INDEX IF NOT EXISTS community_comments_parent_idx ON community_comments (parent_comment_id, created_at ASC) WHERE parent_comment_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS community_reports (
  id TEXT PRIMARY KEY,
  reporter_member_id INTEGER NOT NULL REFERENCES members(id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('post', 'comment')),
  entity_id TEXT NOT NULL,
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  comment_id TEXT REFERENCES community_comments(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('spam', 'abuse', 'misinformation', 'commercial', 'other')),
  detail TEXT NOT NULL DEFAULT '',
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'resolved', 'dismissed')),
  resolution_note TEXT NOT NULL DEFAULT '',
  reviewed_by TEXT,
  reviewed_at TEXT,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  UNIQUE (reporter_member_id, entity_type, entity_id),
  CHECK ((entity_type = 'post' AND comment_id IS NULL) OR (entity_type = 'comment' AND comment_id IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS community_reports_queue_idx ON community_reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS community_reports_post_idx ON community_reports (post_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_report_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id TEXT NOT NULL REFERENCES community_reports(id) ON DELETE CASCADE,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('resolve', 'dismiss')),
  note TEXT NOT NULL DEFAULT '',
  admin_id TEXT NOT NULL,
  actor_email TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_report_events_report_idx ON community_report_events (report_id, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_products (
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  product_slug TEXT NOT NULL REFERENCES products(slug) ON DELETE RESTRICT,
  position INTEGER NOT NULL DEFAULT 0 CHECK (position >= 0 AND position < 3),
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  PRIMARY KEY (post_id, product_slug),
  UNIQUE (post_id, position)
);

CREATE INDEX IF NOT EXISTS community_post_products_product_idx ON community_post_products (product_slug, created_at DESC);

CREATE TABLE IF NOT EXISTS community_post_promotions (
  post_id TEXT PRIMARY KEY REFERENCES community_posts(id) ON DELETE CASCADE,
  placement TEXT NOT NULL CHECK (placement IN ('featured', 'pinned')),
  sort_order INTEGER NOT NULL DEFAULT 0 CHECK (sort_order >= 0 AND sort_order <= 999),
  note TEXT NOT NULL DEFAULT '',
  promoted_by TEXT NOT NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  updated_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT)
);

CREATE INDEX IF NOT EXISTS community_post_promotions_feed_idx ON community_post_promotions (placement, sort_order DESC, updated_at DESC);

CREATE TABLE IF NOT EXISTS community_content_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_key TEXT NOT NULL UNIQUE,
  event_type TEXT NOT NULL CHECK (event_type IN ('post_impression', 'product_click', 'add_to_cart')),
  post_id TEXT NOT NULL REFERENCES community_posts(id) ON DELETE CASCADE,
  product_slug TEXT REFERENCES products(slug) ON DELETE SET NULL,
  member_id INTEGER REFERENCES members(id) ON DELETE SET NULL,
  created_at TEXT NOT NULL DEFAULT (CURRENT_TIMESTAMP::TEXT),
  CHECK ((event_type = 'post_impression' AND product_slug IS NULL) OR (event_type IN ('product_click', 'add_to_cart') AND product_slug IS NOT NULL))
);

CREATE INDEX IF NOT EXISTS community_content_events_post_idx ON community_content_events (post_id, event_type, created_at DESC);
CREATE INDEX IF NOT EXISTS community_content_events_product_idx ON community_content_events (product_slug, event_type, created_at DESC) WHERE product_slug IS NOT NULL;

COMMIT;
